### ISSUE TITLE
Setup schema error table prefix

### ISSUE THREAD

**Issue by wesselstam** [tig-nl/postnl-magento2#1]
The bin/magento setup:upgrade returns database errors while installing the schema:

[Zend_Db_Statement_Exception]
SQLSTATE[42S02]: Base table or view not found: 1146 Table '***.sales_shipment_grid' doesn't exist, query was: DESCRIBE `sales_shipment_grid`

[PDOException]
SQLSTATE[42S02]: Base table or view not found: 1146 Table '***.sales_shipment_grid' doesn't exist

The error is caused beacause i use table prefixes.

**Comment by tig-michielgerritsen** [comment]
Hi @wesselstam,

Sorry for the late response. Somehow Github we did not get an notification. We have already fixed this issue, as more people noticed this. The fix will be available in the next release.

**Comment by tig-michielgerritsen** [comment]
Hi @wesselstam,

The new release is available. This includes the fix for the table prefix.

**Comment by tig-martijndull** [comment]
Github comment test
