### ISSUE TITLE
Na kiezen ophalen krijg je bij betaalmethode te zien dat afleveradres gelijk is al factuuradres

### ISSUE THREAD

**Issue by maartenv1** [tig-nl/postnl-magento2#10]
Na het kiezen van de optie "ophalen" krijg je bij betaalmethode te zien dat afleveradres gelijk is al factuuradres. Dat klopt niet. Je hebt namelijk een stap eerder gekozen dat het afleveradres een postnl afleverpunt is.

**Comment by tig-jaspersmits** [comment]
Hi Maarten,

Dat klopt inderdaad. Hier zie je in het afrekenproces geen bevestiging van. Echter word het op de 3de adresregel van de factuur getoond. Hier zou je eventueel nog terug kunnen vinden hoe je het afhaaladres kan laten tonen in de transactionele e-mails: https://confluence.tig.nl/x/0oSC

Jasper
