### ISSUE TITLE
error with the shipping method when tig postnl module is installed

### ISSUE THREAD

**Issue by alexsonsuaves** [tig-nl/postnl-magento2#100]
### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**

- step 1
   I installed the latest version of Amasty_Checkout : 2.5.0
     installed the latest version of the tig_postnl module : 1.7.3
- step 2 
   after emptying cache and setup:upgrade.
- Step 3
 
  place order and enter de checkout step after setting shipping information. 
 
   error number one:
   if I dont remove  
   in the 'vendor/tig/postnl- 
   magento2/view/frontend/web/template/Compatibility/amasty_checkout/methods.html'
   
  I would get de js error .
  "Message: Unable to process binding "ifnot: function(){return 
   $parent.canUsePostnlDeliveryOptions(method) }"
   Message: $parent.canUsePostnlDeliveryOptions is not a function"

if I remove the 

il will get the error:

State.js:102 Uncaught TypeError: Cannot read property 'carrier_code' of null

- Expected result

  Expected result is that I am able to continue with placing the order.   

- Actual result (Please provide screenshots if applicable)
  
  is the error message and the shipping amount doesnt get updated

- Workaround (If available, otherwise just write "None")

**Comment by tig-daanvandenbergh** [comment]
@alexsonsuaves,

Have you tried using our latest version? 1.7.4 was release a while ago. 

If this doesn't fix your issue. Could you let me know? And perhaps clarify the issue you're having?

**Comment by alexsonsuaves** [comment]
the latest version fix the problem. thanks
