### ISSUE TITLE
Not (de)selecting correct radio input on change

### ISSUE THREAD

**Issue by FrankHarland** [tig-nl/postnl-magento2#101]
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.
### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with the TIG PostNL Magento extension)

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
1: Go to checkout
2: Fill in correct Dutch address information, get shipping options
3: Select a PostNL Shipping option, (either home delivery or pick up in store)
4: Select a diffrent, non-PostNL shipping option
5: Re-select  **the same** previously selected PostNL shipping option
6: Now both the PostNL option and the previously selected non-PostNL option will be active, the 'top-level' PostNL option is no longer selected

Please see this video for a more clear example: http://images.h-o.nl/b741e6e8bdc8

**Comment by tig-jeffreybranderhorst** [comment]
Hi @FrankHarland 

Thank you for submitting this issue. Seems like this is still happening even in the newest version. I'm gonna put this issue on the backlog so it gets fixed. Thank you again for submitting the issue!

If you wanna know the progress of the issue you could contact us and ask for the status of POSTNLM2-794

Regards,
Jeffrey

**Comment by tig-daanvandenbergh** [comment]
This is similar to https://github.com/tig-nl/postnl-magento2/issues/108 and has been fixed. The fix will be included in the next release.

I'm closing this issue.
