### ISSUE TITLE
Other shipping method is still selected after re-selecting previously selected day or pick-up point

### ISSUE THREAD

**Issue by simonjanguapa** [tig-nl/postnl-magento2#108]
---
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [x] This issue does not contain any security sensitive information
---

**We're using Magento 2.3.1, Commerce Cloud.**
1. Enable the PostNL shipping method with the test credentials. Enable the dayselector + pickup
2. Enable another shipping method, for example: "Free shipping" (Magento core).
3. Visit the checkout, enter your information and select a day or pick-up point (but remember which day or which pick-up point). 
4. After you've selected a day or pick-up point, select the other shipping method ("Free shipping" in our case).
5. After you've confirmed the other shipping method is selected, re-select the previously selected day or pick-up point (make sure it's the same).
6. Your shipping method is _not_ updated. You've actually still selected the other shipping method ("Free shipping") in our case. 

**Expected results**
- My shipping method (+ address for pick-up points) is updated, because I've re-selected the previously selected day or pick-up point.

**Actual results**
- My shipping method is _not_ updated, the other shipment ("Free shipping") is still selected. This is clear when I moved on to the payment step. 

**Possible issue**
- The "selectedOption" observable is not updated, thus the .subscribe function is not triggered (Delivery.js and Pickup.js.
- quote.shippingmethod.subscribe (State.js) is not triggered when postNL is re-selected.

**Possible solution**
Adding the following line codesnippet to State.js (web/js/Helper) on line 56:

```
if (shippingMethod.carrier_code !== 'tig_postnl') { 
  currentSelectedShipmentType(shippingMethod.carrier_code)
}
```

**Comment by tig-daanvandenbergh** [comment]
Hi @simonjanguapa,

Thank you for your report. I'll try to reproduce this locally and test your suggested fix. 

I'll keep you posted.

**Comment by tig-daanvandenbergh** [comment]
@simonjanguapa,

I've implemented your suggested solution and verified that it resolves this issue. I'll implement it in the next release!

Thanks again!
