### ISSUE TITLE
Track and Trace mail - wrong order_id

### ISSUE THREAD

**Issue by SilvanLaroo** [tig-nl/postnl-magento2#11]
Hi,

We're using your PostNL extension. If we send the track and trace mail the order id is displayed in this mail. The problem is that the var order_id in the file track_and_trace.html is not the order_id but the shippment_id. 

See this file: https://github.com/tig-nl/postnl-magento2/blob/master/Helper/Tracking/Mail.php#L135, should be: `$shipment->getOrder()->getRealOrderId()`.

**Comment by tig-jaspersmits** [comment]
Hi Silvan,

Sorry for the delayed reaction. I will ask my colleague @tig-michielgerritsen to take a look at this. 

Jasper

**Comment by tig-timsibbald** [comment]
Hi Silvan,

Thank you for your notice, the fix for this problem will be included in the upcoming release.

Best Regards,
Tim
