### ISSUE TITLE
Post office locations error + Temando_Shipping

### ISSUE THREAD

**Issue by kaybeudeker** [tig-nl/postnl-magento2#112]
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [ ] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [x] Other

---

- [x] This issue does not contain any security sensitive information

---

For those who, after upgrading to M2.3.1. and/or V1.7.4, are having a problem placing an order with a post office location selected, and face this 'blank error';

**Page ('blank error'?):**

![blankerror](https://user-images.githubusercontent.com/31165120/58077092-1b0dee80-7bac-11e9-94bb-59b9616b8800.png)

**Console:**

<img width="1175" alt="Schermafbeelding 2019-05-21 om 08 40 47" src="https://user-images.githubusercontent.com/31165120/58077100-1ea17580-7bac-11e9-8f6f-b59415b43ab3.png">

**Report api/1457123258461:**

`"Fatal Error: 'Uncaught Error: Call to a member function getStoreId() on null in \/home\/domain.nl\/folder\/public_html\/vendor\/temando\/module-shipping-m2\/Plugin\/Quote\/Address\/ToOrderAddressPlugin.php:74\nStack trace:\n#0 \/home\/domain.nl\/folder\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): Temando\\Shipping\\Plugin\\Quote\\Address\\ToOrderAddressPlugin->afterConvert(Object(Magento\\Quote\\Model\\Quote\\Address\\ToOrderAddress\\Interceptor), Object(Magento\\Sales\\Model\\Order\\Address), Object(Magento\\Quote\\Model\\Quote\\Address))\n#1 \/home\/domain.nl\/folder\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Quote\\Model\\Quote\\Address\\ToOrderAddress\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Quote\\Model\\Quote\\Address))\n#2 \/home\/domain.nl\/folder\/public_html\/generated\/code\/Magento\/Quote\/Model\/Quote\/Address\/ToOrderAddress\/Interceptor.php(26): Magento\\Quote\\Model\\Quote\\Address\\ToOrderAddress\\Intercep' in '\/home\/domain.nl\/folder\/public_html\/vendor\/temando\/module-shipping-m2\/Plugin\/Quote\/Address\/ToOrderAddressPlugin.php' on line 74"`

Disabling the Temando_Shipping module will make the error disappear and it's possible to place an order with a post office location again.

**Comment by tig-jaspersmits** [comment]
Hi @kaybeudeker,

Thanks for your message. We are aware of this and listed it on our backlog. At this moment we recommend users to disable the Temando Shipping module.

Kind regards,

Jasper
