### ISSUE TITLE
Rewrite TIG Postcode plugins

### ISSUE THREAD

**Issue by vshatylo** [tig-nl/postnl-magento2#113]
Hello we updated PostNL module to latest version and found some troubles: 
PostNL module rewrites plugins 
postcodeGuestPaymentInformationManagement 
postcodePaymentInformationManagement
postcodeMageplazaCheckoutInformation

of TIG Postcode module. 
we have disabled option
tig_postnl/addresscheck/enable_postcodecheck 

as result billing address has empty house number.

**Comment by tig-daanvandenbergh** [comment]
Hi @vshatylo,

I'm not sure I understand you completely. Are you saying that when you disable 'enable Postcode check' the house number of the billing address returns empty? What happens when you enable the Postcode Check? Is the house number field filled correctly?

**Comment by vshatylo** [comment]
Hello, 
Billing address has empty house number in case we disable 'enable Postcode check' 

When we enable this option we get another one problem described in 'Shipping address in one line #114'

**Comment by tig-daanvandenbergh** [comment]
Thank you, @vshatylo.

We'll try to reproduce this issue and get back to you.

**Comment by tig-jeffreybranderhorst** [comment]
Hello @vshatylo,

I Just tested the newest PostNL extension with the Postcode check turned on and off. Both of the times the housenumber was sent with it to the backend. 
What are you disabling exactly? Could you send a screenshot of it to us of maybe call us, so we can talk about the problem?

Or could you sent us the steps to reproduce it?

Best regards,
Jeffrey

**Comment by vshatylo** [comment]
Magento EE 2.2.7
 steps to reproduce
 - enable TIG Postcode autocomplete
 - disable option TIG Postnl tig_postnl/addresscheck/enable_postcodecheck
 - go to store front 
 - add product to cart
 - go to checkout 
 - add shipping address
 - go to step 2 
 - enable custom billing address and add it
 - place order
 - check order in back office

**Comment by tig-jeffreybranderhorst** [comment]
Hello @vshatylo,

I cannot reproduce this on our testing sites, I tested with both extension on, with PosTNL check off and the TIG one on and the other way around. But the house number never disappears for us, I will put this issue on Cannot reproduce because I think its maybe a conflict with theme or another extension. 
We can still help you figure out why your house number disappears, if you can send an e-mail to support@tig.nl we can look at your problem. 

Best regards,
Jeffrey
