### ISSUE TITLE
Shipping address in one line

### ISSUE THREAD

**Issue by vshatylo** [tig-nl/postnl-magento2#114]
hello we updated TIG PostNL module to latest version 
we faced with problem that shipping address become in one line. 

we use TIG Postcode module and enabled option tig_postnl/addresscheck/enable_postcodecheck 

Please, take into account that address should be splited based on config street Lines Count

**Comment by tig-daanvandenbergh** [comment]
Hi @vshatylo,

Thank you for notifying me of this issue. I'll have to look into the code, to see if the Street Lines Count is taken into account.

I'll keep you posted.

**Comment by tig-jeffreybranderhorst** [comment]
Hey @vshatylo,

In the TIG Postcode Check there are option to split the address. If you didn't change these then it will be all on 1 line, if you change the options the address will be split up. 

![image](https://user-images.githubusercontent.com/23314965/58947246-d5464e00-8787-11e9-9455-6dce0ebc89cc.png)
These are the TIG Postcode service options, not the magento customer configuration. 

Kind regards,
Jeffrey

**Comment by tig-daanvandenbergh** [comment]
@vshatylo,

Since this is not a bug. I'm closing this issue.
