### ISSUE TITLE
Postnl Shipment Create issue using API

### ISSUE THREAD

**Issue by nadeefit6** [tig-nl/postnl-magento2#115]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [ x] This issue does not contain any security sensitive information

---

### If the purpose of your issue is a *feature request*
- As a *..certain type of user..* I’d like to *..describe what you want..* in order to *..write goal(s)..*
- Suggestions and background: 
  If you have ideas for the solution write them down here. Include images, a picture is more worth than 1,000 words. If none, remove this line.

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Step 1: Place an order with Postnl shipping method
- Step 2: Create shipment with postnl API (Not using backend)
Note : Version is 1.7.0. But i could not find any fix for the below issue in latest version.
Could you please confirm.

- Expected result
Create shipment 
There should be a record in tig_postnl_shipment table.

- Actual result 
Shipment is created.
But no records found in tig_postnl_shipment table for the relevant order.
Because of this issue, when open the order in back-office and click on "Track Order" link ->its not working.
- Workaround (If available, otherwise just write "None")

### If the purpose of your issue is about anything else, please describe your issue here
- Explain your issue here

### TIG support

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.
- If you want support with installing the PostNL extension, please contact citservicedesk@postnl.nl for free support, or contact us directly at support@tig.nl for paid support plans.

**Comment by nadeefit6** [comment]
Hi,
Shipment  through API is not created with the newest version 1.7.4.
Any update on this?

**Comment by tig-dennisvanderhammen** [comment]
Hi @nadeefit6,
Which Magento version are you using, and are you trying to create a Magento shipment and expecting a tig_postnl_shipment to be created, or are you making use of the tIGPostNLShipmentRepositoryV1 call?

What are the parameters that you are sending to our API? Are you receiving any errors when trying to use the API?

Kind regards,
Dennis van der Hammen

**Comment by boldhedgehog** [comment]
Hi @tig-dennisvanderhammen ,
We call Magento's standard order management API to ship orders. Magento version is 2.2.7.
When orders are created in the back office, a record as added to `tig_postnl_shipment`; however, when orders are created via REST, probably some observer is missing in your module, and no records are added to the table. It can be reproduced with Magento's Swagger.

**Comment by tig-dennisvanderhammen** [comment]
Hi @boldhedgehog,

It is intentional that there are no records created, because in that flow we're not sure yet what options should be used in the tig_postnl_order / tig_postnl_shipment table. The PostNL extension has its own API functionalities to fill these tables.

The recommended flow is to do the following:
1. Create an order with the Magento Order repository
2. Create a TIG PostNL order with the tIGPostNLOrderRepositoryV1
3. Create a shipment with the Magento Shipment repository
4. Create a TIG PostNL shipment with the tIGPostNLShipmentRepositoryV1

**Comment by boldhedgehog** [comment]
Hi @tig-dennisvanderhammen ,
Could you please give more details on this? 

> Create a TIG PostNL shipment with the tIGPostNLShipmentRepositoryV1

The preference for `TIG\PostNL\Api\Data\ShipmentInterface` is missing in `di.xml`, and `/V1/postnl/shipments` **POST** request cannot instantiate this interface.

**Comment by tig-daanvandenbergh** [comment]
Hoi @boldhedgehog,

We've fixed the issues with the API in version 1.8.1.

Thank you for notifying us!
