### ISSUE TITLE
Sales order grid data blank when async indexing is enabled

### ISSUE THREAD

**Issue by StevenGuapaBV** [tig-nl/postnl-magento2#116]
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x] This issue does not contain any security sensitive information

---

### If the purpose of your issue is a *bug report*
The sales order grid does not contain the data from the order except for the custom PostNL fields. This only happens when the "dev/grid/async_indexing" is set to 1 (enabled)

**Step 1:** 
- Enable the async indexing under Stores > Configuration > Advanced > Developer > Grid Settings > Asynchronous indexing

**Step 2:**
- Place a new order on the frontend 

**Step 3:**
- Check the data in the backend Sales > Orders

**Expected result:** 
The sales order grid contains all the data of orders

**Actual result:**
- The grid will only show the ship_at, product_code and confirmed data from PostNL
- The sales_order_grid table will also only contain the custom data from PostNL.

**Workaround:**
For now the workaround is to disable the async_indexing. But this is a nice feature from Magento that we are keen to use.

**Comment by igorwulff** [comment]
Hi @tig-jaspersmits  Can you give an estimate when this will be? It has been a few months now and we should like to keep on using async_indexing for ours order grids.

**Comment by tig-jaspersmits** [comment]
Hi @igorwulff , as far as I can see it should be available in the next release. But I don't have an estimate right now. I would say it will take at least one more month for a release, but it could be more. When I receive more detailed information I'll let you know.

**Comment by tig-jaspersmits** [comment]
Hi @igorwulff ,

I haven't tested this yet, but the fix should be like this: https://www.screencast.com/t/PLtonBVFjtC
You could give it a try if you want. Otherwise it will be available in the next release.

Kind regards,
Jasper

**Comment by tig-dennisvanderhammen** [comment]
Hi @igorwulff,

We have released a version where async indexing is supported. You can install version 1.9.0 for this. Thank you again for bringing this to our attention.
