### ISSUE TITLE
Can not upgrade to Magento 2.3.2 because of tig postnl module 

### ISSUE THREAD

**Issue by richardreen** [tig-nl/postnl-magento2#117]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [ ] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [x ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [ ] This issue does not contain any security sensitive information

---

#
Magento  released version 2.3.2. Because this release contains lots of bugfixes and a better performance we tried to upgrade to this version.But the Tig PostNL module (version 1.7.4) makes it impossible.

**Comment by tig-daanvandenbergh** [comment]
Hi @richardreen,

Obviously this is on our radar. As Magento 2.3.2 was released today (technically: yesterday night, after office hours) we're currently updating our testing environments to make sure the module is stable on Magento 2.3.2. After that, we will release a new version of this extension supporting 2.3.2.

Thanks.

**Comment by igorwulff** [comment]
Hi TIG, I understand 2.3.2 needs to be tested, but can at least a RC be provided just like previous times?

**Comment by tig-daanvandenbergh** [comment]
RC's actually proved to be an annoyance for most of our PostNL-users -- leading to many complaints towards PostNL as well as ourselves. Most PostNL-users apparently interpret RC's as a new stable release. So we decided not to release RC's anymore.

We're currently working on the stable release for 2.3.2.

**Comment by tig-daanvandenbergh** [comment]
We've just released v1.8.0 of the PostNL-extension, adding new features, including compatibility with Magento 2.1.18, 2.2.9 and 2.3.2.

Thank you for your patience. I'm closing this issue.
