### ISSUE TITLE
GraphQl or Rest Api

### ISSUE THREAD

**Issue by dheesbeen** [tig-nl/postnl-magento2#118]
Hello Tig,

Are there any plans to move some of the api like frontend controller actions to the Magento api.  Preferably GraphQL. For example the delivery dates call? This so we can implement it in the pwa-studio checkout. Or are there other best practices for implementation in a PWA?

Thanks in advanced for your answer.

Derrick

**Comment by tig-daanvandenbergh** [comment]
Hi @dheesbeen,

Great suggestion! We're indeed looking into possibilities to make this module better usable in a PWA environment.

We're going to discuss this with our PostNL representative.

I'll keep you posted.

**Comment by tig-jaspersmits** [comment]
Because of a clean-up action we will close this ticket. The ticket has been on our backlog and is still open. This indicates that PostNL decided to not give priority to this case. There is a chance we will still look into this for a future release.
