### ISSUE TITLE
Unable to place orders: Call to a member function getAdditionalInformation() on null 

### ISSUE THREAD

**Issue by hnsr** [tig-nl/postnl-magento2#120]
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

Running version 1.8.0

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x] This issue does not contain any security sensitive information

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Run Magento 2.3.2
- Using onestepcheckout, add a product to cart
- Go to checkout and after filling out address information and selecting shipment, payment methods, place order
- A fatal error is triggered when the payment-information is saved, and the order can not be placed

The fatal error is: 

```
Fatal Error: 'Uncaught Error: Call to a member function getAdditionalInformation() on null in /data/web/deployment_live/releases/20190710085958/vendor/magento/module-sales/Model/OrderRepository.php:182

Stack trace:
#0 /data/web/deployment_live/releases/20190710085958/vendor/magento/module-sales/Model/OrderRepository.php(144): Magento\Sales\Model\OrderRepository->setPaymentAdditionalInfo(Object(Magento\Sales\Model\Order\Interceptor))
#1 /data/web/deployment_live/releases/20190710085958/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\OrderRepository->get('44')
#2 /data/web/deployment_live/releases/20190710085958/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\OrderRepository\Interceptor->___callParent('get', Array)
#3 /data/web/deployment_live/releases/20190710085958/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}('44')
#4 /data/web/deployment_live/releases/20190' in '/data/web/deployment_live/releases/20190710085958/vendor/magento/module-sales/Model/OrderRepository.php' on line 182"
```

As a quick fix I've disabled the `\TIG\PostNL\Observer\TIGPostNLOrderSaveBefore\SetDefaultData` observer which seems to trigger this error by attempting to load the order through the order repository. At this point the order has no payment yet, while the order repository assumes that it does (see `\Magento\Sales\Model\OrderRepository::setPaymentAdditionalInfo`)

While writing this I found an apparent duplicate issue: https://github.com/tig-nl/postnl-magento2/issues/99

However this particular error was fixed in 1.7.4, while I'm running 1.8.0

**Comment by tig-dennisvanderhammen** [comment]
Hi @hnsr,

This is peculiar. This was indeed fixed in a previous version. The cause of this was the getShippingAddress function on line 220. This calls the \TIG\PostNL\Service\Order\MagentoOrder::get function.

The function would then call the order repository which contained an entity id, but no payment, just like you stated.

We fixed this by placing this code in a try/catch which catches an \Error (as seen on line 222 in the SetDefaultData class), although it seems that in your case the error is not being caught.

Could it be that a certain PHP setting is stopping the Error from being caught? If not, could you try changing the catch (\Error $e) to catch (Throwable $e) and see if that fixes the problem for you?

**Comment by hnsr** [comment]
Hey @tig-daanvandenbergh, thanks for your response! Will see if \Throwable allows me to catch it and report back as soon as I can

**Comment by hnsr** [comment]
Hey @tig-dennisvanderhammen,

Tried again today, and it seems the fix was correct after all, not sure what happened when I was testing 1.8.0 previously. Apologies! Will close this PR

(also apologies for accidently tagging daan in my previous comment)

**Comment by tig-dennisvanderhammen** [comment]
Hey @hnsr,

No problem at all, thank you for posting a clear and easy to understand issue. Glad to hear that you managed to get it working :)
