### ISSUE TITLE
Tracking link without TIG PostNL entity

### ISSUE THREAD

**Issue by boldhedgehog** [tig-nl/postnl-magento2#123]
**Please rephrase the following line:**

As a shop merchant I'd like to add return tracking code to shipments without creating TIG shipment entity. At this moment it is impossible, and adding a tracking code via Magento API only leads to an exception page in the tracking window.

**Suggestions and background**

Dutch orders receive a free returnlabel with their order for PostNL carrier. So, when order is shipped PostNL provides 2 tracking codes: one is for the shipment (and we can add a tracking code via Magento API and then create TIG shipment, see #115 ); however, the link for the return shipment cannot be created in the same way, because the return shipment can be performed in the future (or can be not created ever). I checked the code, the shipments are looked up by main_barcode https://github.com/tig-nl/postnl-magento2/blob/eca72ef4f79b50751b8bdc27e91c1201d531ec9d/Helper/AbstractTracking.php#L113

Questions:
- can you change the code so we can use return tacking codes without TIG shipment in the database?
- can we create tig shipment with more then one barcode, and then get PostNL tracking link for this additional barcode?

**Comment by tig-daanvandenbergh** [comment]
Hi @boldhedgehog,

Return shipments in PostNL for Magento 2 is a task very highly prioritized on our backlog.

Thank you for this suggestion. I'll add this to the backlog item, so it'll be considered when the solution is implemented.

**Comment by tig-jaspersmits** [comment]
Hi @boldhedgehog ,

Just to inform you. We will release this functionality in the upcoming version. I don't have a date yet, but you can keep an eye on our release notes page: https://confluence.tig.nl/x/3YSC

Kind regards,
Jasper

**Comment by boldhedgehog** [comment]
Hi @tig-jaspersmits,
Was it included in 1.8.1?

**Comment by tig-jaspersmits** [comment]
Hi @boldhedgehog ,
It should be in the next release of the extension. 

Kind regards,
Jasper
