### ISSUE TITLE
[BUG] Call to member function on NULL when billing address is not present

### ISSUE THREAD

**Issue by Dragiyski** [tig-nl/postnl-magento2#124]
**To Reproduce**
1. Go to directory: dev/tests/integration
2. Setup integration tests as suggested by Magento2.
3. Execute: php ../../../vendor/bin/phpunit ./testsuite/Magento/Checkout/Api/PaymentInformationManagementTest.php

**Expected result**
The integration test passes.

**Actual result**
```
Magento\Checkout\Api\PaymentInformationManagementTest::testSavePaymentInformationAndPlaceOrderWithErrors with data set #0 ('frontend', array(91511, 'fake_code'), 'Transaction has been declined...later.')
Failed asserting that exception of type "Error" matches expected exception "\Magento\Framework\Exception\CouldNotSaveException". Message was: "Call to a member function getExtensionAttributes() on null" at
./vendor/tig/postnl-magento2/Plugin/Postcodecheck/Management/Payment.php:70
./vendor/magento/framework/Interception/Interceptor.php:121
...
```

**Workaround**
The method signature ``TIG\PostNL\Plugin\Postcodecheck\Management\Payment::beforeSavePaymentInformation`` clearly suggests that the billing address could be ``NULL``. The first statement immediately uses ``T_OBJECT_OPERATOR`` on a value that can be ``NULL``. The interceptor must not throw such an exception.

** Version information**
- Magento version: 2.3.2
- PHP version: PHP 7.2.19-0ubuntu0.18.04.2
- TIG PostNL version: 1.8.0

**Comment by tig-jaspersmits** [comment]
Hi @Dragiyski ,

Thanks for your letting us know! Me or my colleague will look into this and get back to you. When I have more information available I'll let you know.

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Because of a clean-up action we will close this ticket. The ticket has been on our backlog but has been closed. This indicates that it is either solved or PostNL decided to not give priority to this case.
