### ISSUE TITLE
Unable to update to Magento 2.3.2-p2

### ISSUE THREAD

**Issue by igorwulff** [tig-nl/postnl-magento2#127]
Hello Tig,

Magento provided an recent patch update to version 2.3.2-p1 and 2.3.2-p2. Currently we are unable to update our Magento shops and make sure they are up to date with the latest security updates.

Can magento/framework be changed to include 102.0.2-p1 and 102.0.2-p2?

We require this change as soon as possible.

**Comment by tig-dennisvanderhammen** [comment]
Hi Igor,

I just created a quick release for people who want to apply the 2.3.2-p2 version.
Using the following commands I managed to update:

composer require magento/product-community-edition:2.3.2-p2 --no-update
composer require tig/postnl-magento2 --no-update
composer update
