### ISSUE TITLE
[BUG] Don't use quote load during calculation PostNL rates

### ISSUE THREAD

**Issue by vshatylo** [tig-nl/postnl-magento2#128]
Hello, 
we faced with problem that some customer get error 'Max execution time exceed' on our project.
After research we found that problem caused of usage two modules. 
Amasty Free Gift 
PostNL module.

We know that it is customization but it will help to resolve potential problems of customers.
Amasty module allow to create cart price rule with adding free products. 

**To Reproduce**
pre-condition. Amasty Free Gift module should be installed and enabled
Persistent shopping cart should be enabled 

- add product to cart  
- add one more product to cart
- go to checkout (fill shipping address) 
- go to product page 
- configure cart price rule "Auto add promo item for whole cart"  (customization from Amasty module)
- enable rule and wait for index 
- disable one of product of your cart (during test, it was not a bundle) 
- refresh product page 
!important. sections load triggered not always (manually it could be run via dev console require("Magento_Customer/js/customer-data").reload(['cart'], false);) 

 Customer sections request will fail with error 'max execution time'

**Expected result**
Response should have status 200

**Actual result**
Fatal error

**Workaround**
We changed code of PostNL module. 
- get quote_id from checkout session
- extract quote items from rate request

**Screenshots**

** Please complete the following information**
- Magento version: Magento EE 2.2.7
- PHP version: 7.1.32
- TIG PostNL version: 1.7.4

**Comment by tig-jaspersmits** [comment]
Good morning @vshatylo ,

Thanks for letting us know! I'll discuss with the development team what we want to do with this. By default, there isn't any support for that extension. It's up to our developers and PostNL if we want to add this support. When I have more information I'll get back to you!

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Because of a clean-up action we will close this ticket. The ticket has been on our backlog but has been closed. This indicates that it is either solved or PostNL decided to not give priority to this case.
