### ISSUE TITLE
Error creating credit memo

### ISSUE THREAD

**Issue by SilvanLaroo** [tig-nl/postnl-magento2#13]
Hi TIG,

We're using version v1.1.4-alpha of your extension. When we try to create a credit memo, we get an error that refers to the PostNL extension.

Steps to reproduce
--
1. Install v1.1.4-alpha
2. Place order using PostNL as shipment provider
3. Make sure order is payed (status Processing)
4. Go to single view of order in Magento 2 backend
5. Select 'Credit Memo'

Expected result
--
1. Credit Memo generated

Actual result
--
1. Redirected back to order
2. Error shown with this message:
`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`staging`.`tig_postnl_order`, CONSTRAINT `TIG_POSTNL_ORDER_QUOTE_ID_QUOTE_ENTITY_ID` FOREIGN KEY (`quote_id`) REFERENCES `quote` (`entity_id`) ON DELETE SET NULL), query was: INSERT INTO `tig_postnl_order` (`order_id`, `quote_id`, `product_code`, `created_at`, `updated_at`) VALUES (?, ?, ?, '2017-08-17 08:22:54', '2017-08-17 08:22:54')`

**Comment by JavierYD** [comment]
I'm having the same problem.

**Comment by tig-jeffreybranderhorst** [comment]
Hello SilvanLaroo and JavierYD,

Sorry to hear that you are both having the same problem!
This is not a known error and I cannot reproduce it on my own website. 

If you still have the problem with version v1.1.4-Alpha can you contact us via servicedesk@tig.nl with your environment details (login credentials etc.), so we can have a look at it?

**Comment by tig-jaspersmits** [comment]
Good morning,

I also tried to reproduce this, just to make sure. But no problems here as well. My colleague Vincent recommended checking if you have any deleted orders. This can cause the foreign key problem.

If you both are still experiencing this problem you can always send us an e-mail: servicedesk@tig.nl.

Kind regards,

Jasper
