### ISSUE TITLE
[BUG] AddressEnhacer produce 500 error

### ISSUE THREAD

**Issue by vshatylo** [tig-nl/postnl-magento2#130]
Timeframes and locations requests retrieves 500 error on checkout
Notice: Undefined index: housenumber in /var/www/html/vendor/tig/postnl-magento2/Helper/AddressEnhancer.php on line 177

**To Reproduce**
1. Go to checkout (postcode check feature should be disabled)
2. fill only postcode value, house number should be empty 
3. view response 

**Expected result**
500 error

**Actual result**
Timeframes and locations successfully processed.

**Workaround**
we removed conflicting code.

** Please complete the following information**
- Magento version: Magento EE 2.3.2
- PHP version: 7.2
- TIG PostNL version: 1.8.1

**Comment by tig-daanvandenbergh** [comment]
Hi @vshatylo,

Thanks for notifying us!

You're right. There should be a check if 'housenumber' exists. There isn't now. I'll add it to our backlog!

**Comment by tig-daanvandenbergh** [comment]
The cause of this issue is the same as GITHUB-134

**Comment by tig-jaspersmits** [comment]
Hi @vshatylo ,

Just to inform you. We will release this functionality in the upcoming version. I don't have a date yet, but you can keep an eye on our release notes page: https://confluence.tig.nl/x/3YSC

Kind regards,
Jasper
