### ISSUE TITLE
Compatibility with AheadWorks Smart One Step Checkout for Magento 2

### ISSUE THREAD

**Issue by webtekindo** [tig-nl/postnl-magento2#132]
Is there any plan to make the module compatible with the popular AheadWorks Smart One Step Checkout for Magento 2:

https://ecommerce.aheadworks.com/magento-2-extensions/one-step-checkout

Thank you.

**Comment by tig-jaspersmits** [comment]
Hi @webtekindo ,

Thanks for contacting us. We will look into this and put it on our feature request list. Currently there are no plans, but we will forward it to PostNL to see if they want this compatibility.

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Because of a clean-up action we will close this ticket. The ticket has been on our backlog and is still open. This indicates that we will work on it in the future or once PostNL decides to give priority to this compatibility.
