### ISSUE TITLE
[BUG] Missing house number

### ISSUE THREAD

**Issue by jacky-raimond** [tig-nl/postnl-magento2#134]
If a customer tries to checkout with a pre-saved address, the PostNL delivery timeframes aren't showing. There's one option possible "Eerst volgende mogelijkheid".

**To Reproduce**
1. Go to 'account'
2. Create new address in address book
3. Add product to cart
3. Go to checkout

**Expected result**
Showing a list of delivery timeframes

**Actual result**
No list of delivery timeframes. Only one option "Eerst volgende mogelijkheid"

**Workaround**
If you disable the address validation in the back end the problem does not occur anymore in the front end.

**Screenshots**
_Before (address validation enabled)_
<img width="1103" alt="Before" src="https://user-images.githubusercontent.com/54097545/68471655-ed326a00-021e-11ea-832d-4622a3a02a16.png">

_After (address validation disabled)_
<img width="1045" alt="After" src="https://user-images.githubusercontent.com/54097545/68471654-ed326a00-021e-11ea-9e97-ee8daf7f46ed.png">

**Please complete the following information**
- Magento version: Magento CE 2.3.3 (problem also exists on 2.3.2)
- PHP version: 7.2.24-1
- TIG PostNL version: 1.8.1

**Comment by tig-jaspersmits** [comment]
Hi @jacky-raimond ,

Thanks for letting us know. We will test this and get back to you with our findings.

Kind regards,
Jasper
TIG

**Comment by tig-daanvandenbergh** [comment]
The cause of this is the same as issue #130.

**Comment by tig-jaspersmits** [comment]
Hi @jacky-raimond  ,

Just to inform you. We will release this functionality in the upcoming version. I don't have a date yet, but you can keep an eye on our release notes page: https://confluence.tig.nl/x/3YSC

Kind regards,
Jasper
