### ISSUE TITLE
[BUG] Evening fee is applied to second order immediately placed after.

### ISSUE THREAD

**Issue by dheesbeen** [tig-nl/postnl-magento2#137]
**To Reproduce**
0. Process as described is with a logged in Customer,
1. Add product to the cart, go to the checkout. In the checkout choose evening delivery at additional cost (2 euro)
2. Place the order. After that go ahead and place another order. When we get in the checkout evening delivery fee is already calculated without selecting it.

**Expected result**
Evening delivery value needs to be cleared after placing the order. Somehow it is applied on the next order if this order is placed directly afterwards

**Actual result**
The evening fee is directly applied when placing a second order directly after the first order

**Workaround**
None

**Screenshots**
None

** Please complete the following information**
- Magento version: 2.3.2
- PHP version: 7.2.0
- TIG PostNL version: 1.8.0

**Comment by tig-jaspersmits** [comment]
Hi @dheesbeen ,

Thanks for letting us know. I have just tested this, I'm unable to reproduce this problem. Did you experience this on a clean Magento environment? Are you using a specific checkout by any chance?

Kind regards,
Jasper

**Comment by dheesbeen** [comment]
Hi @tig-jaspersmits,
Good question. We are using the clean checkout and Magento Commerce
Thanks

**Comment by tig-jaspersmits** [comment]
Hi @dheesbeen ,

Do you mean the default Magento checkout or literally the Clean Checkout (https://github.com/danslo/CleanCheckout)? If yes, are you able to test this without that checkout enabled?

Kind regards,
Jasper

**Comment by tig-daanvandenbergh** [comment]
Changed title of issue to something more appropriate.

**Comment by tig-jaspersmits** [comment]
@dheesbeen ,

Do you perhaps have an answer on the question I've asked 17 days ago? Thanks in advance!

Kind regards,
Jasper
