### ISSUE TITLE
Error creating single shipment

### ISSUE THREAD

**Issue by SilvanLaroo** [tig-nl/postnl-magento2#14]
Hi TIG,

In some cases, if we try to create a single shipment, we get an almost blank page.

Steps to reproduce
--
1. Install version 1.1.4
2. Create order
3. Go to orders in backend
4. Open single order
5. Click on 'Ship'

Expected result
--
1. Page shown to create shipment

Actual result
--
1. Almost blank page
2. Error in logs (see below)

```
2017/08/21 15:28:28 [error] 13134#13134: *11980 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getProductCode() on null in /data/web/magento2/vendor/tig/postnl-magento2/Block/Adminhtml/Shipment/Options/Create.php:101
Stack trace:
#0 [internal function]: TIG\PostNL\Block\Adminhtml\Shipment\Options\Create->getProductCode()
#1 /data/web/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array)
#2 /data/web/magento2/vendor/tig/postnl-magento2/view/adminhtml/templates/shipment/create/options.phtml(62): Magento\Framework\View\TemplateEngine\Php->__call('getProductCode', Array)
#3 /data/web/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/data/web/magen...')
#4 /data/web/magento2/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(TIG\PostNL\Block\Adminhtml\Shipment\Options\Create), '/data/web/magen...', Array)
#5 /data/web/magento2/vendor/magento/framework/View/Element/Template.php(279): Magento\Frame" while reading response header from upstream, client: 217.100.11.114, server: , request: "GET /beheer/admin/order_shipment/new/order_id/38737/key/f08145a0aab41ace0e6cd838a3eca4717e526b839b6ed005e86a3e1e27e9e21a/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.sebwite.nl", referrer: "https://www.sebwite.nl/beheer/sales/order/view/order_id/38737/key/1c4469f0cb8ac8adb98a1f8eb42cf75073ad2b2d272a1094324c32d65b050eab/"
```

**Comment by tig-jaspersmits** [comment]
Hi SilvanLaroo,

Unfortunate to hear you are experiencing this problem. I just tried to reproduce it on our test environment, but everything worked as expected. What i would like to recommend is to contact PostNL about this. 

You can contact them trough e-mail on citservicedesk@postnl.nl or call PostNL on phone number 088-2255652.

If they are unable to provide you with a solution they will forward the problem to us. We will then contact you and investigate it further.

Met vriendelijke groet,

Jasper Smits
Customer Care Specialist

servicedesk@tig.nl
020 - 21 81 001
TIG.nl - Wij ontwikkelen extensies, webshops en maatwerk commerce platformen.

**Comment by SilvanLaroo** [comment]
This problem is still active, this is the flow of the customer:
- Customer adds products to cart
- Customer navigates to checkout and selects PostNL
- Customer cancels his order
- Customer changes products in cart
- Customer now completes his order
- Error 500 (as shown in the issue) is thrown

**Comment by tig-jaspersmits** [comment]
Hi Silvan,

Where exactly does the customer cancel the order? On the payment page of the bank or within Magento itself? I will try to reproduce if you can provide me with this info.

**Comment by SilvanLaroo** [comment]
Just found out that this problem is still active, no new record is available in the TIG order table. There is a record for the old, canceled order. I canceled the order on the payment page of the bank.

**Comment by tig-jeffreybranderhorst** [comment]
Hi SilvanLaroo,

I just tried to reproduce it with the steps you said in your last message. But I cannot reproduce this. 
Could you contact us on servicedesk@tig.nl so we speak via the mail and find out what is happening?

Best Regards,
Jeffrey Branderhorst
