### ISSUE TITLE
[BUG] Tablerates with condition_name 'package_value_with_discount' aren't imported correctly

### ISSUE THREAD

**Issue by igorwulff** [tig-nl/postnl-magento2#140]
**To Reproduce**
1. Go the System Configuration for Shipping Methods and then to POSTNL and try to upload a csv for tablerates with the condition set to "Price vs Destination"

**Expected result**
Have my file uploaded with success and when exporting get an similar csv back as download.
We also expect to see the tablerates applied for use in the frontend, based on the criteria in the csv.

**Actual result**
When trying to export the csv for tablerates, only headers are shown. 
We are unable to re-upload the same csv file due to mysql duplicate errors in the system.log
We don't see any changes on the frontend where we expect tablerates to be applied.

**Workaround**
We see the value in tig_postnl_tablerate.condition_name to have 'package_value_with_d' instead of 'package_value_with_discount'.

Perform an mySQL command:
ALTER TABLE tig_postnl_tablerate MODIFY condition_name VARCHAR(30);

To increase the columns size to be able to include the full value of 'package_value_with_discount'

** Please complete the following information**
- Magento version: 2.3.3
- PHP version: 7.2.0
- TIG PostNL version: 1.8.0

**Comment by tig-jaspersmits** [comment]
Hi @igorwulff ,

I was able to reproduce this problem. This has just been placed on our backlog.
We will fix this for a future release. You can keep an eye on the release notes here: https://confluence.tig.nl/x/3YSC

Kind regards,
Jasper

**Comment by igorwulff** [comment]
@tig-jaspersmits good to hear and I hope to hear soon from you!

**Comment by tig-dennisvanderhammen** [comment]
@igorwulff,

In 1.9.0 we have added a setup script that changes the condition_name from 20 to 30 characters. You might want to re-upload your csv file to get it to work.

Thank you for bringing this to our attention.
