### ISSUE TITLE
[BUG] Performance issues when generating multi colli

### ISSUE THREAD

**Issue by Paasi-gs** [tig-nl/postnl-magento2#141]
**To Reproduce**
1. Ship order, set coli to 2 or up
2. Print barcode

**Expected result**
No performance issue

**Actual result**
When having over 32k records in barcode table, printing label takes over 60 seconds. 

**Background**
Issue traced back to this function: https://github.com/tig-nl/postnl-magento2/blob/23eff8acfcdeed356a646adf29f05b3e7cfd6351/Service/Handler/BarcodeHandler.php#L136

When creating a multi colli the complete barcode collection is loaded (in our env ~31k records), not sure if this is intended? 

https://github.com/tig-nl/postnl-magento2/blob/23eff8acfcdeed356a646adf29f05b3e7cfd6351/Service/Handler/BarcodeHandler.php#L139-L140

And then complete collection is saved again:

https://github.com/tig-nl/postnl-magento2/blob/23eff8acfcdeed356a646adf29f05b3e7cfd6351/Service/Handler/BarcodeHandler.php#L154

Just switched from collection to factory and processing time dropped from ~60 seconds to just 2 seconds.

**Comment by tig-jaspersmits** [comment]
Hi @Paasi-gs ,

Thanks for submitting this. I'll test this as soon as possible and get back to you.

Kind regards,
Jasper

**Comment by tig-jaspersmits** [comment]
Hi @Paasi-gs ,

What you could do (make a backup though) is empty that database table. Remove the labels for older orders that you no longer need. But I understand that you prefer not to do that. Therefore we will look into this and I've put it on our backlog to see if we can optimize the code.

Kind regards,
Jasper

**Comment by Paasi-gs** [comment]
Hi @tig-jaspersmits thank you for looking into this! If this table can be cleaned up, think it is better to add this as a scheduled task?

**Comment by tig-jaspersmits** [comment]
Hi @Paasi-gs , for some reason I just noticed your comment.. better late than never I would say. You could do that, but keep in mind that you won't be able to open the labels for the removed orders any more.

Kind regards,
Jasper

**Comment by tig-support** [comment]
Note from Jen: Automatically assigned Jasper Smits to this issue as no one was assigned.

**Comment by Paasi-gs** [comment]
Hi @tig-jaspersmits why is this issue closed? Still see the complete collection being loaded: https://github.com/tig-nl/postnl-magento2/blob/master/Service/Handler/BarcodeHandler.php#L171

Any update on this? As 60 seconds to generate a barcode and php spiking is far from optimal.

**Comment by tig-jaspersmits** [comment]
Hi @Paasi-gs ,

I think I closed it by accident. We are trying out a new way to sync Github with our ticket system. I'll reopen it. Will discuss this again with my colleagues. Will let you know when there is more I can say about it.

Kind regards,
Jasper

**Comment by tig-jaspersmits** [comment]
Just put it on the backlog to add indexer to that table.

Kind regards,
Jasper

**Comment by Paasi-gs** [comment]
Hi @tig-jaspersmits, thanks. In all due respect an indexer won't solve this issue, please check the links i've supplied it it loading and saving the **complete barcode collection**. So when setting the label qty to 2, it is loading all the barcodes from the complete history (not just that shipment), adding 1 item and then saving the complete history again. It is not filtering anything on the collection. Adding an index won't do much good. Think this is a big deal. Try adding 20k of dummy records to the table and generate a multi colli shipment.

**Comment by tig-jaspersmits** [comment]
Hi @Paasi-gs ,

Thanks for your response. I'll inform our development team about this.
I will try to do some testing with the dummy records.

Kind regards,
Jasper

**Comment by tig-jaspersmits** [comment]
Hi @Paasi-gs ,

Is it possible for you to provide such a database to test with? We can test it, but we need to create a script to create that amount of orders first. If you can provide me a database like that I would be able to test it earlier. (preferably with no customer data of course).

Kind regards,
Jasper

**Comment by tig-jaspersmits** [comment]
Hi @Paasi-gs ,

My colleague made a fix for this which will be tested soon. This will most likely be released in the next version of the extension. You can keep an eye on the release notes here: https://docs.tig.nl/x/3YSC

If you have any questions, please let me know!

Kind regards,
Jasper

**Comment by tig-jaspersmits** [comment]
This should be fixed in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG
