### ISSUE TITLE
[BUG] Unable to create labels for "avondlevering"

### ISSUE THREAD

**Issue by Paasi-gs** [tig-nl/postnl-magento2#147]
**To Reproduce**
1. Create Shipment with option "avond levering"
2. Create label, returns blank label

**Expected result**
Correct shipping label

**Actual result**
Exception: `110103: Validation failed for shipment: xxxxx, Messages: xxxx: {[110103] Phone number of Receiver is required}`

Soap data contains phone number (redacted):

```
<ns1:Contact>
  <ns1:ContactType>01</ns1:ContactType>
  <ns1:Email>x@xxx.nl</ns1:Email>
  <ns1:TelNr>030xxxxxx</ns1:TelNr>
</ns1:Contact>
```

** Please complete the following information**
- Magento version: 2.3.2
- PHP version: 7.2.x
- TIG PostNL version: 1.8.0

**Comment by tig-dennisvanderhammen** [comment]
Hi @Paasi-gs,

This seems to be an issue within the PostNL api. We have confirmed the issue and have contacted PostNL about this.

**Comment by Paasi-gs** [comment]
@tig-dennisvanderhammen If this makes the search any easier; this client went live 2 months ago and I've traced this issue back from the start, so it looks like this wasn't functioning for atleast two months.

**Comment by tig-dennisvanderhammen** [comment]
Hi @Paasi-gs,

Thank you for mentioning this.
We have passed your information on to PostNL. They got back to us as well and mentioned that they fixed the issue.

I've confirmed this with my test order, I am now able to generate an evening label again, without receiving an error.

**Comment by Paasi-gs** [comment]
Hi @tig-dennisvanderhammen, yes can confirm this is working again. Thank you for the quick follow-up and fix, customer is happy!
