### ISSUE TITLE
[FEATURE] Support Post Office BE

### ISSUE THREAD

**Issue by sirajea** [tig-nl/postnl-magento2#148]
As an end-user I'd like to be able to generate Post Office Pickup labels for Belgium in order to ship parcels to Pickup Post Offices in Belgium.

**Suggestions and background**
- PostNL documentation: https://developer.postnl.nl/browse-apis/send-and-track/products/#destination-belgium
- DownPartnerID and DownPartnerLocation are required as shipment properties for these products. They can be retrieved from the Location webservice response as RetailNetworkID and LocationCode

**Comment by tig-jaspersmits** [comment]
Hi @sirajea ,

Thanks for contacting us with this feature request! We appreciate your feedback in how you would like to see the PostNL extension improve. Currently, we do have this feature on our backlog. Our developers are working hard on it and it should be available in an upcoming release of the extension. 

I would recommend keeping an eye on our release notes page and/or subscribe yourself on that page (https://confluence.tig.nl/x/3YSC). If you do that you will receive an update once a new version is released.

If you have any further questions, please let me know!

Kind regards,
Jasper
TIG

**Comment by sirajea** [comment]
@tig-jaspersmits Thank you. Would it speed-up the release if I implement it and open a pull request with the required changes?

**Comment by tig-jaspersmits** [comment]
Hi @sirajea ,

Yes absolutely. This can help us and it is possible that it shortens the development time. Feel free to open such a pull request.

Kind regards,
Jasper
TIG

**Comment by GuiltyNL** [comment]
That would be very appreciated @sirajea , we are waiting for this feature too :)

**Comment by sirajea** [comment]
@tig-jaspersmits Please have a look at #157 Thanks!

**Comment by tig-jaspersmits** [comment]
Thanks @sirajea !
I will inform our developers about your PR and let them have a look at it. Your input is highly appreciated!

Kind regards,
Jasper

**Comment by tig-support** [comment]
Note from Jen: Automatically assigned Jasper Smits to this issue as no one was assigned.

**Comment by tig-jaspersmits** [comment]
@sirajea ,

Let's continue any follow-ups in the PR: https://github.com/tig-nl/postnl-magento2/pull/157
I will close this ticket and my colleagues will take over the PR implementation.

Kind regards,
Jasper

**Comment by sirajea** [comment]
@tig-jaspersmits Thanks for the feedback and thank you guys a lot for the cake as well, what a pleasant surprise! :yum: :tada:

**Comment by GuiltyNL** [comment]
Did they deliver a cake to you guys? 🙌

**Comment by tig-jaspersmits** [comment]
@sirajea you are welcome! Thanks again for your help!

**Comment by sirajea** [comment]
@GuiltyNL Yep!

Since TIG has decided to implement this later after some PostNL API changes, I've created a release on my fork that is identical to the latest official release (v1.9.0.1) but added the changes required for PakjeGemak Belgium to work, for those who cannot wait (**Not official, so use at your own risk**).
**Release**: https://github.com/E-fulfilment-Shop/postnl-magento2/releases/tag/v1.9.0.1-PGBE
**Compare**: https://github.com/tig-nl/postnl-magento2/compare/v1.9.0.1...E-fulfilment-Shop:v1.9.0.1-PGBE

**Comment by tig-daanvandenbergh** [comment]
> Did they deliver a cake to you guys? 🙌

Hell yeah! It's not often that we receive such a complete and well-written feature/pull request. So that deserves some appreciaten! 👍

**Comment by GuiltyNL** [comment]
Hats off! @sirajea 

So merge to master asap @tig-daanvandenbergh  😁

**Comment by tig-daanvandenbergh** [comment]
Hi @GuiltyNL,

I'm afraid it's not that simple (https://github.com/tig-nl/postnl-magento2/pull/157#issuecomment-585753556), but it's on our radar!
