### ISSUE TITLE
[QUESTION] Magento 2.3.4 compatibility (magento/framework ~102.0.4)

### ISSUE THREAD

**Issue by igorwulff** [tig-nl/postnl-magento2#150]
**Question**
Magento has made a 2.3.4 pre-release available for their partners along with a 2.3.3-1 version. Can you create a release candidate / beta version that changes the restriction in the composer.json for this? We want to start testing our projects and this issue is currently blocking this.

**Comment by tig-dennisvanderhammen** [comment]
Hi @igorwulff,

We are currently testing this ourselves as well. Because we have had negative experiences creating RC's with customers installing them on their production environment without testing, we have decided not to create RC's anymore, at least for now.

If you would like to test the extension on 2.3.4 on your own environment, I recommend creating a fork off our repository to change the composer version.

**Comment by igorwulff** [comment]
Hi @tig-dennisvanderhammen , I still disagree with this method, since developers should know what a RC is and the possible impact for releasing this on a production environment.

When do you expect to be able to release a 'stable' version?

**Comment by tig-dennisvanderhammen** [comment]
While I personally completely agree that developers should know the possible impacts, it seems that not everybody realises the dangers of installing a RC on a production environment. We have had complaints about this in the past.

We have had a few discussions about this internally as well, but I'll try to bring this up within our team again to see what we can do about this.

About your question regarding the stable version, our testing team is currently working hard to see if they can find any unexpected behaviours in our extension. We have also included bug-fixes in our extension, so they have to be tested thoroughly.

As soon as we release a new version we will also update our release notes. We have a button at the top right corner to watch this page. You'll receive an e-mail as soon as the release notes gets updated if you set yourself as a watcher:

https://confluence.tig.nl/x/3YSC

**Comment by igorwulff** [comment]
Hi @tig-dennisvanderhammen thanks for the explanation and clear up. We've updated our fork and changed the requirements so we can continue. I will close this issue then.
