### ISSUE TITLE
[BUG] When insert a table-rate no prices are visible 

### ISSUE THREAD

**Issue by rsp-vicus** [tig-nl/postnl-magento2#151]
**To Reproduce**
1. Import Table Rates in Shpping Method  PostNL in backend
2. Go to Chekout
3. Select PostNL as sender

**Expected result**
The shipping price of the table rate

**Actual result**
Price is 0, onevery address

**Workaround**
None

**Screenshots**

** Please complete the following information**
- Magento version: Magento 2.3.3
- PHP version: 7.2.0
- TIG PostNL version: 1.8.1
![Checkout](https://user-images.githubusercontent.com/31655295/72975399-0cc64100-3dd1-11ea-8de0-e56b334c1eed.png)

**Comment by rsp-vicus** [comment]
Prices are correct in Table 'tig_postnl_tablerate'

**Comment by tig-dennisvanderhammen** [comment]
Hi @rsp-vicus ,

Thank you for mentioning this. Could this be your issue?
https://github.com/tig-nl/postnl-magento2/pull/136

**Comment by rsp-vicus** [comment]
In the  `tig_postnl_tablerate` `condition_name` = package_weight, komt niet aan die lengte

**Comment by tig-dennisvanderhammen** [comment]
Yes, that is the issue that is described in #136. This is already on our backlog.
A workaround for you would be opening your database and changing the length from 20 to 30.

Because we are already aware of this issue, and will be fixed in an upcoming release, I will be closing this issue.
