### ISSUE TITLE
[BUG] column condition_name too short for value

### ISSUE THREAD

**Issue by appdezign** [tig-nl/postnl-magento2#153]
**To Reproduce**
1. Go to 'Stores > Configuration > Sales > Shipping Methods'
2. Click on 'PostNL'
3. Scroll down to 'Rate Type' and select 'table'

**Expected result**
When I upload the CSV while the Condition is set to 'Price vs Destination', the data is inserted in the table called tig_postnl_tablerate. The 'condition' is inserted in the column called 'condition_name'. When the condition is set to 'Price vs Destination', the value that is inserted should be 'package_value_with_discount'.

**Actual result**
However, because the lenth of this string is 27 characters, and the column is a varchar(20) the value is cutoff and is inserted as 'package_value_with_d'.
The result is that the row is not recognized, and the frontend now shows shipping costs of 0 (zero).

**Workaround**
I have manually changed the column to a varchar 255, and imported the CSV again. Now it works as expected.

**Screenshots**

** Please complete the following information**
- Magento version: Magento 2.3.1
- PHP version: 7.1
- TIG PostNL version: 1.8.1

**Comment by tig-dennisvanderhammen** [comment]
Hi @appdezign,

Thank you for submitting this. This is a known issue, and will be fixed in the next release.

https://github.com/tig-nl/postnl-magento2/issues/151. I'll be closing this issue as this will be fixed in the upcoming release.
