### ISSUE TITLE
[BUG] Unable to place orders because PostCodeCheck plugins assume 3 addresslines are configured.

### ISSUE THREAD

**Issue by CsSatter** [tig-nl/postnl-magento2#158]
**To Reproduce**
1. Configure Magento to only show 1 address line in the checkout
2. Attempt to place an order using PostNL as the shipping method (also have the address check enabled)
3. Place the order

**Expected result**
Magento will redirect you to the PSP

**Actual result**
An error is thrown because the addresses don't pass Magento's validation

**Workaround**
Patch your PostcodeCheck plugins to glue the address data instead of parsing them as seperate values in the setStreet method.

** Please complete the following information**
- Magento version: 2.3.4 Community
- PHP version: 7.2
- TIG PostNL version: 1.9.0

**Comment by tig-jaspersmits** [comment]
Hi @CsSatter ,

Thanks for submitting this. I just had a look at it and tried to reproduce but was unable to do so. I'm not experiencing any problems with these settings. Are you testing this on a default Magento environment without any extensions and themes active?

Kind regards,
Jasper

**Comment by CsSatter** [comment]
Hi @tig-jaspersmits ,
This is in combination with the Amasty Onestep Checkout module. We're currently building a work-around for this issue.

**Comment by tig-jaspersmits** [comment]
Hi @CsSatter ,

I see. Okay. Do you plan on building a work-around within your extension or something we would need to apply to our code? Looking forward to your response.

Kind regards,
Jasper

**Comment by CsSatter** [comment]
Hi @tig-jaspersmits,
Our current work-around is that we've changed the configuration back to 3 address lines but through frontend changes are hiding the added address fields :).

**Comment by tig-jaspersmits** [comment]
Hi @CsSatter ,
Thanks for your response. Is this just a separate piece of code, or added to the Amasty or PostNL extension?

Kind regards,
Jasper

**Comment by tig-jaspersmits** [comment]
This should be fixed in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG

**Comment by CsSatter** [comment]
Hi @tig-jaspersmits , I'm unsure as to why I didn't respond to your question. Possibly a busy schedule.

Thanks for fixing the issue!

P.S. If I recall correctly it was done in the PostNL module

**Comment by tig-jaspersmits** [comment]
Hi @CsSatter ,
Correct, it's about the PostNL extension.

Kind regards,
Jasper
TIG
