### ISSUE TITLE
Not able to send orders on sunday

### ISSUE THREAD

**Issue by JRM93** [tig-nl/postnl-magento2#16]
When trying to process a shipment on sundays the following error message is shown. Therefor merchant is not able to process shipments on sundays.

![image](https://user-images.githubusercontent.com/6276759/29773435-cf652e34-8bfd-11e7-9eee-a0d59ce4f23c.png)

**Comment by tig-jaspersmits** [comment]
Hi JRM93,

Unfortunate to hear that you are experiencing this problem. My colleague Dennis will try to reproduce this on a test environment. Once he tested this we will inform you about this.

Kind regards,

Jasper

**Comment by tig-dennisvanderhammen** [comment]
Hi JRM93,

I managed to reproduce your issue on a core environment and I've created a backlog item for this. It is up to PostNL to set the priority for this issue.

If you want to keep yourself up-to-date you can either following issue https://jira.tig.nl/browse/POSTNLM2-337 or watch our release notes page: https://confluence.tig.nl/x/3YSC

**Comment by tig-dennisvanderhammen** [comment]
Hi JRM93,

Yesterday we released our latest version of the PostNL extension. I'm currently unable to reproduce your issue. Could you tell me if you still encounter this problem? If so, can you tell me how I could try to reproduce this?
