### ISSUE TITLE
After selecting the orders we are getting this error.

### ISSUE THREAD

**Issue by Tanuja0202** [tig-nl/postnl-magento2#160]
Fatal error: Uncaught TypeError: Argument 2 passed to TIG\PostNL\Service\Handler\BarcodeHandler::canAddReturnBarcodes() must implement interface TIG\PostNL\Api\Data\ShipmentInterface, null given, called in /var/www/vhosts/stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php on line 322 and defined in /var/www/vhosts/stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php:294 Stack trace: #0 /var/www/vhosts/stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php(322): TIG\PostNL\Service\Handler\BarcodeHandler->canAddReturnBarcodes('BE', NULL) #1 /var/www/vhosts/stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php(138): TIG\PostNL\Service\Handler\BarcodeHandler->validateShipment('139683', 'BE') #2 /var/www/vhosts/stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Controller/Adminhtml/Shipment/MassPrintPackingslip.php(125): TIG\PostNL\Service\Handler\BarcodeHandler->prepa in /var/www/vhosts/stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php on line 294

**Comment by tig-jaspersmits** [comment]
Hi @Tanuja0202 ,

Just posting an error message is not really a question. Please give detailed information about when this is happening etc. Thank you.

**Comment by Tanuja0202** [comment]
select orders -----> then go to the action section ----> Choose postnl
print methods

**Comment by tig-jaspersmits** [comment]
@Tanuja0202 this seems more like something that should be submitted as a bug issue.
You can use the following template and create a new issue:



**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'

**Expected result**
A clear and concise description of what you expected to happen.

**Actual result**
Describe the actual result

**Workaround**
Describe the temporarily workaround or if none exists write "None"

**Screenshots**
If applicable, add screenshots to help explain your problem.

** Please complete the following information**
- Magento version: [e.g. Magento 2.3.1]
- PHP version: [e.g. 7.2.0]
- TIG PostNL version: [e.g. 1.8.1]
