### ISSUE TITLE
Sales Grid Action dropdown error - PostNL create shipment, print label & confirm

### ISSUE THREAD

**Issue by mohdali27** [tig-nl/postnl-magento2#161]
I am using the postnl extension with magento latest version 2.3.4. I installed the extension using the git composer . Extension is installed successfully but in order sales grid when i select the option " PostNL create shipment, print label & confirm" without selecting any record. Then it is giving the below error - Please check and fix the issue - It should give the validation message when i did not select any order from order grid.
`1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): An item needs to be selected. Select and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): An item needs to be selected. Select and try again.
<pre>#1 TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels->createShipmentsAndLoadLabels() called at [vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php:115]
#2 TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels->execute() called at [generated/code/TIG/PostNL/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels/Interceptor.php:24]
#3 TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#4 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#) called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#5 Magento\Backend\App\AbstractAction->dispatch(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#6 TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#7 TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#) called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#8 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(&TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels\Interceptor#0000000071fb6e420000000059630c82#, &Closure#0000000071fb6e4f0000000059630c82#, &Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#9 TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#), NULL) called at [generated/code/TIG/PostNL/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels/Interceptor.php:39]
#11 TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#) called at [vendor/magento/framework/App/FrontController.php:159]
#12 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#, &TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels\Interceptor#0000000071fb6e420000000059630c82#) called at [vendor/magento/framework/App/FrontController.php:98]
#13 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#14 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#15 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#), array(array('default_store_se...', 'page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#17 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000071fb0aa70000000059630c82#) called at [vendor/magento/framework/App/Http.php:116]
#18 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#19 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#20 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000071fb0df70000000059630c82#) called at [index.php:39]`

**Comment by tig-jaspersmits** [comment]
Hi @mohdali27 ,

Thanks for your message. This is a known problem and was submitted earlier this week: https://github.com/tig-nl/postnl-magento2/issues/159
This is on our backlog and will fixed in a future update.

Kind regards,
Jasper
TIG
