### ISSUE TITLE
[FEATURE] PostNL layout handles in transactional e-mails

### ISSUE THREAD

**Issue by ZIPITRO** [tig-nl/postnl-magento2#162]
Hi!

Please add the following option to the module.

In Magento 1 we have the option to add {{layout handle="postnl_email_order_pakjegemak_address" order=$order}} to add the postoffice location in the emails and thank you page, so that the customer is seeing where his/her package is shipped to instead of the shipping address of the customer.

Reference from M1 TIG PostNL module:https://docs.tig.nl/display/SDPOSTNL/PostNL+layout+handles+opnemen+in+transactionele+e-mails

Thanks a lot!

**Comment by tig-jaspersmits** [comment]
Hi @ZIPITRO ,

Thanks for your message. We agree and aware of this. We currently have this as a feature request on our backlog under this ticket number: POSTNLM2-944

PostNL determines the priority for the backlog feature requests. I expect that we will do something with this in the future.

Kind regards,
Jasper
TIG

**Comment by ZIPITRO** [comment]
Hi @tig-jaspersmits  Thanks! Great module for M2, thanks for developing!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ZIPITRO,

You should be able to show shipping address also in M2, have you seen the following article?  https://docs.tig.nl/x/q4SC
Or are you still missing information?

Kind regards,
Jeffrey

**Comment by ZIPITRO** [comment]
Hi Jeffrey,

Sorry for late reply, I didn't noticed an update, sorry!
Will try and let you know if this will cover the missing information.

Thanks!

Kind Regards,

Paul

**Comment by ZIPITRO** [comment]
Hi Jeffrey,
Thanks for your solution, this works also for us, but some customers might not be able to be satisfied by this, cause its a bit more technical. But this helped me, please consider fixing it in the future.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ZIPITRO,

Great to read! You are welcome for the solution no problem. 

Have a great day and weekend!
Jeffrey
