### ISSUE TITLE
Missing MSI support stock check delivery options

### ISSUE THREAD

**Issue by Jurhillebrink** [tig-nl/postnl-magento2#163]
The stock check doesn't have support for MSI. 'pakjegemak' locations are not displayed when the product doesn't have stock quantity and is_in_stock set on source 'default'.

**To Reproduce**
1. Go to admin -> config -> sales -> Postnl and set 'Activate post office location' to 'yes'.
2. Set also 'Stock Settings' to 'Only for products that are in stock' .
3. Setup multiple custom sources (MSI).
4. Assign positive quantity to on one of the new sources and remove source 'default' on the product.
5. Set stock quantity to 0 and is_in_stock to 0 in table cataloginventory_stock_item and quantity to 0 and stock_status to 0 in cataloginventory_stock_status for the product if it has quantity (if the product had a default source in the past). These tables are used for products with source 'default', but aren't used when MSI is enabled and the product is **not** assigned to source 'default'.
6. Ensure that the product is salable.
7. Add the product to cart.
8. Go to shipping options in checkout.
9. Add your address information.

**Expected result**
'Pakjegemak' locations will displayed.

**Actual result**
'pakjegemak' locations are not displayed.

**Workaround**
None

**Screenshots**

** Please complete the following information**
- Magento version: Magento 2.3.4
- PHP version: 7.2.
- TIG PostNL version: 1.9.0

**Comment by tig-jaspersmits** [comment]
Hi @Jurhillebrink ,

Thanks for letting us know. We are aware that PostNL isn't working correctly with MSI. I'll test this specific case and follow up on it when I can tell you more about it.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @Jurhillebrink ,

Just tried to reproduce it, but I'm still getting pakjegemak locations. Can you maybe share some screenshot of your MSI, product and inventory settings? I will try and replicate the exact same scenario.

Kind regards,
Jasper
TIG

**Comment by Jurhillebrink** [comment]
The screenshots shows the circumstance when the 'pakjesgemak' locations are hidden.
FYI: ProductId 625223 links to SKU td_30.19986-187-USNM09. qty and is_in_stock needs to be set to 0:
<img width="1020" alt="Screenshot 2020-04-01 at 11 52 02" src="https://user-images.githubusercontent.com/14016931/78124272-bfd59b00-740f-11ea-8c58-463025cda0c3.png">

You can see below that the product has quantity and is saleable with MSI:

<img width="1287" alt="Screenshot 2020-04-01 at 11 46 45" src="https://user-images.githubusercontent.com/14016931/78124448-fa3f3800-740f-11ea-8b32-7bcd2f7c90e7.png">

<img width="1050" alt="Screenshot 2020-04-01 at 11 53 06" src="https://user-images.githubusercontent.com/14016931/78124472-01fedc80-7410-11ea-84b6-0a785881abcb.png">

<img width="1094" alt="Screenshot 2020-04-01 at 11 53 28" src="https://user-images.githubusercontent.com/14016931/78124483-075c2700-7410-11ea-900f-60a662980217.png">

**Comment by tig-jaspersmits** [comment]
Hi @Jurhillebrink ,

I gave it another go, but can't replicate yet "unfortunately". I made some screenshots of the the database tables you shared, if you see anything I'm doing wrong, please let me know.

Cataloginventory_stock_item: https://www.screencast.com/t/VzsIO3Sos
Product in backend: https://www.screencast.com/t/87ykhDA2aFk
Inventory_stock2: https://www.screencast.com/t/YTlldPguYS
Inventory_source_item: https://www.screencast.com/t/Fq8hUKRR
PostNL in checkout: https://www.screencast.com/t/r05T8rrW

Kind regards,
Jasper
TIG

**Comment by Jurhillebrink** [comment]
@tig-jaspersmits  hmm that's strange.
Below you can see that the shippingoptioptions_active (Config/Provider/CheckoutConfiguration.php) becomes is false when the product has no stock:
![image](https://user-images.githubusercontent.com/14016931/78247169-b1a87d00-74ea-11ea-9cf4-a6535120f251.png)

When the product has quantity it becomes true:
![image](https://user-images.githubusercontent.com/14016931/78247406-1e237c00-74eb-11ea-8c6a-df7ebdba90f3.png)

The shippingoptioptions_active is set in Config/CheckoutConfiguration/IsShippingOptionsActive.php where the validateStockOptions is called.

**Comment by tig-jaspersmits** [comment]
Hi @Jurhillebrink ,

Thanks for your response. My colleague will dive deeper into this during the new sprint.
You will receive a response when he can tell you more about this and/or if it will be fixed.

Kind regards,
Jasper
TIG

**Comment by Jurhillebrink** [comment]
Hi @tig-jaspersmits ,

Do you have any update regarding this issue?

I hope to hear from you.

Kind regards,

Jur

**Comment by tig-jaspersmits** [comment]
Hi @Jurhillebrink ,

I see we didn't follow up on this yet. Our developers have made a pull requests for this to get it solved. It's currently undergoing testing and it will most likely be available in the next release.

Kind regards,
Jasper
TIG

**Comment by Jurhillebrink** [comment]
Hi @tig-jaspersmits 

Do you have insight when the release is planned?

Kind regards,

Jur

**Comment by tig-jaspersmits** [comment]
Hi @Jurhillebrink ,

I would say the next release. But I don't have any confirmation on that yet. I'll see if I can get an update.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
This should be fixed in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG
