### ISSUE TITLE
Magento 2.2.11- error during setup:upgrade

### ISSUE THREAD

**Issue by mtjweb** [tig-nl/postnl-magento2#164]
I tried to install this module on Magento 2.2.11.

Steps:

1. composer require tig/postnl-magento2
2. php bin/magento setup:upgrade

When it gets to the module an error occurs:
Notice: Undefined index: v1.1.0 in .../vendor/tig/postnl-magento2/Setup/InstallSchema.php on line 67

**Comment by tig-jaspersmits** [comment]
Hi @mtjweb ,

Thanks for your message and unfortunate to hear you are experiencing this problem. I just tried to reproduce the problem on a clean Magento 2.2.11 environment. The installation succeeded without the error you mentioned. Seems like it is somehow related to your environment.

What I would recommend is that you contact PostNL about this. They will try to help you out but if they are unable to provide a solution, they can decide to transfer it to us. We will then ask for credentials for the environment, so we can take a look at it.

You can contact them on digitaleklantsupport@postnl.nl or call them on 088-2255651. 

But like mentioned, this doesn't seem to be a problem with the extension itself.

Kind regards,
Jasper
