### ISSUE TITLE
[BUG] Amasty One Step Checkout 3.0.1

### ISSUE THREAD

**Issue by martijn-bigbridge** [tig-nl/postnl-magento2#166]
**To Reproduce**
1. Install the latest Amasty One Step Checkout
2. Install the latest Tig PostNL
3. Go to the checkout

**Expected result**
A working checkout (no page crash)

**Actual result**
Javascript errors

knockout.js:3381 Uncaught TypeError: Unable to process binding "foreach: function(){return { data:rates(),as:'method'} }"
Message: Unable to process binding "ifnot: function(){return $parent.isModernDesign() }"
Message: Unable to process binding "if: function(){return ($parent.isPostNlEnable() && $parent.canUsePostnlDeliveryOptions(method)) }"
Message: $parent.canUsePostnlDeliveryOptions is not a function
    at if (eval at createBindingsStringEvaluator (knockout.js:2982), <anonymous>:3:99)
    at ko.computed.disposeWhenNodeIsRemoved (knockout.js:4381)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout.js:2173)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.js:2140)
    at Function.evaluateImmediate (knockout.js:2101)
    at Object.ko.computed.ko.dependentObservable (knockout.js:1954)
    at init (knockout.js:4380)
    at knockout.js:3358
    at Object.ignore (knockout.js:1470)
    at knockout.js:3357

This file vendor/amasty/module-single-step-checkout/view/frontend/web/template/onepage/shipping/methods.html is changed in the last 2 years.

This is the old one.
https://github.com/tig-nl/postnl-magento2/blob/master/view/frontend/web/template/Compatibility/amasty_checkout/methods.html

Trying to merge is without success.

**Workaround**
None

** Please complete the following information**
- Magento version: 2.3.4
- PHP version: 7.3.0
- TIG PostNL version: 1.9.1
- Amasty One Step Checkout: 3.0.1

**Comment by tig-jeffreybranderhorst** [comment]
Hi @martijn-bigbridge,

PostNL does not support any OSC yet for Magento 2. The current support inside the extension have been Pull request of other merchants,  If you know that methods.html is the fix I would like to ask you to also make a pull request for this so we could check the pull request and add it to the extension. 

Have a great day,
Jeffrey

**Comment by tig-jaspersmits** [comment]
This should be fixed in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG
