### ISSUE TITLE
[QUESTION] Support for Magento 2.3.5

### ISSUE THREAD

**Issue by jellesiderius** [tig-nl/postnl-magento2#168]
Installation for 2.3.5 will fail, since tig/postnl-magento2 is only compatible to framework 102.0.4. Magento 2.3.5 uses framework 102.0.5.

**To Reproduce**
Try installing Magento 2.3.5 through composer.

**Expected result**
Magento upgrades correctly and the PostNL module works with 2.3.5.

**Actual result**
Upgrade command fails since requirements can't be met.

**Workaround**
None

**System information**
Magento version: 2.3.5
PHP version: 7.3.0
TIG PostNL version: 1.9.1.1

**Comment by tig-jaspersmits** [comment]
Hi @jellesiderius ,

Thanks for creating this issue. We are aware of compatibility that needs to be added for Magento 2.3.5. We are working on it and will release it once it's been tested and approved. Best thing to do would be keeping an eye on the release notes: https://docs.tig.nl/x/3YSC

Kind regards,
Jasper
TIG

**Comment by Serializator** [comment]
Hi @tig-jaspersmits,

When I try to upgrade from 2.3.4 to 2.3.4-p2 I seem to get a problem with version constraint relating to `tig/postnl-magento2` not being compatible with `magento/framework:102.0.4-p2`.

```
tig/postnl-magento2 1.9.1 requires magento/framework >=100.1.0,<=100.1.18|>=101.0.0,<=101.0.11|>=102.0.0,<=102.0.4 -> satisfiable by magento/framework[ 
    102.0.4, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12, 101.0.3, 100.1.13, 101.0.4, 101.0.5, 100.1.14, 100.1.15, 101.0.6, 100.1.16, 101.0.7, 102.0.0, 100.1.17, 102.0.1, 101.0.8, 102.0.2, 100.1.18, 101.0.9, 102.0.3, 101.0.10, 102.0.2-p2, 101.0.11, 102.0.3-p1 
]
```

Is it possible for the version constraint to get updated to support 102.0.4-p2 for the short term in case the support for 2.3.5 takes longer than expected?

I don't want to clutter an "unrelated issue" but it felt a bit over the top to create an additional issue for this.

With kinda regards,
Julian

**Comment by jkwakman** [comment]
2.3.4-p2 is a security release and should be backwards compatible with 2.3.4. Can you please ensure we can upgrade our Magento stores again via composer?

Security issues:
https://helpx.adobe.com/security/products/magento/apsb20-22.html

  Problem 1
    - Installation request for tig/postnl-magento2 1.9.1.1 -> satisfiable by tig/postnl-magento2[1.9.1.1].
    - Conclusion: don't install magento/framework 102.0.4-p2
    - magento/product-community-edition 2.3.4-p2 requires magento/framework 102.0.4-p2 -> satisfiable by magento/framework[102.0.4-p2].
    - magento/product-community-edition 2.3.4-p2 requires magento/framework 102.0.4-p2 -> satisfiable by magento/framework[102.0.4-p2].

The tig/postnl composer repo is now blocking the upgrade.

Kind regards,

Jack Kwakman

**Comment by tig-jaspersmits** [comment]
Hi @Serializator and @jkwakman ,

I will discuss this with our team and get back to you as soon as I can.

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
Hi @Serializator @jkwakman and @jellesiderius ,

We have released a new version of the PostNL extension. In this version we have made the constrains a little bit more loose. Whenever 2.3.6 gets released, you should be able to uninstall that one immediately as well.

Please note that we have changed "versions supported" to "versions tested with" in the backend.
We will test upcoming versions as you're used to, but from now on, you won't be stopped by us to install the latest minor.
