### ISSUE TITLE
[BUG] Shipment not an object

### ISSUE THREAD

**Issue by CompactCodeEU** [tig-nl/postnl-magento2#169]
**To Reproduce**
1. Go to 'order mass actions'
2. Click on 'click on any mass action from this extension'
3. When the `$this->createShipment` returns a boolean(false) or null it results in an 503 page since later on it when the labels are loaded it assumes this is an object.

**Expected result**
Should be checked before using a function on the object like this :
```
vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php
        $address = $this->canaryConverter->convert(**$shipment->getShippingAddress()**);
```

**Actual result**
It is not so it returns an 503 page without errors

**Workaround**
Change 
```
vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php
        foreach ($shipments as $shipment) {
           ++ if($shipment){
                $this->loadLabel($shipment);
            ++}
        }
```

** Please complete the following information**
- Magento version: [e.g. Magento 2.3.1]
- PHP version: [e.g. 7.2.1]
- TIG PostNL version: [1.9.1]

**Comment by tig-jaspersmits** [comment]
Hi @CompactCodeEU ,

Thanks for you letting us know. I'll test this as soon as I can and will come back to you with a response.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @CompactCodeEU ,

I wanted to let you know we've added this to our backlog. Keep an eye on the release since we will update it one of the upcoming releases.

Thanks again for informing us.

Kind regards,
Jasper
TIG

**Comment by CompactCodeEU** [comment]
Just a suggestion is to move that function to another class since you have multiple controllers with the same functionality.

**Comment by tig-jaspersmits** [comment]
Hi @CompactCodeEU ,

Thanks for the feedback. I'll add this as extra information to the backlog ticket.

Kind regards,
Jasper
TIG

**Comment by jkwakman** [comment]
Dear Jasper,

Is there an update about this bug? Mass printing labels has become a real challenge. 

Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getShippingAddress() on bool in /vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrint

Magento version 2.3.4-p2
Plugin 1.9.1.1
PHP 7.3

Can you please provide an ETA?

**Comment by tig-jaspersmits** [comment]
Hi @jkwakman ,

The fix for this is currently in code review. We are planning to release this in version 1.9.3.
I'm not entirely sure, but I think the plan is to release that version this month.

Please keep an eye on our release notes page: https://docs.tig.nl/x/3YSC

Kind regards,
Jasper
TIG

**Comment by jkwakman** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'order mass actions'
> 2. Click on 'click on any mass action from this extension'
> 3. When the `$this->createShipment` returns a boolean(false) or null it results in an 503 page since later on it when the labels are loaded it assumes this is an object.
> 
> **Expected result**
> Should be checked before using a function on the object like this :
> 
> ```
> vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php
>         $address = $this->canaryConverter->convert(**$shipment->getShippingAddress()**);
> ```
> 
> **Actual result**
> It is not so it returns an 503 page without errors
> 
> **Workaround**
> Change
> 
> ```
> vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php
>         foreach ($shipments as $shipment) {
>            ++ if($shipment){
>                 $this->loadLabel($shipment);
>             ++}
>         }
> ```
> 
> ** Please complete the following information**
> 
> * Magento version: [e.g. Magento 2.3.1]
> * PHP version: [e.g. 7.2.1]
> * TIG PostNL version: [1.9.1]

Workaround seems to work for mass printing the labels. Thanx!

**Comment by tig-jaspersmits** [comment]
@jkwakman ,

Good te hear the workaround works for you!

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
This should be fixed in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG
