### ISSUE TITLE
[QUESTION] Please summarize your question here

### ISSUE THREAD

**Issue by KoenSlagter** [tig-nl/postnl-magento2#170]
Hi,

A client of us has an issue with sending a package to another country.
It says 'Verzending van deze productoptie voor deze bezorgdatum is niet meer mogelijk.'.
In the XML it has the deliveryDate of 1 day from now, so it is reasonable to assume that this date can't be met by sending.

I'm using the latest version of the module and magento 2.3.4

`Check CIFException in the detail section - 2060: Verzending van deze productoptie voor deze bezorgdatum is niet meer mogelijk. <<<< Request XML >>>> <?xml version="1.0" encoding="UTF-8"?> <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://postnl.nl/cif/domain/DeliveryDateWebService/" xmlns:ns2="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:ns3="http://postnl.nl/cif/services/DeliveryDateWebService/"> <env:Header/> <env:Body> <ns3:GetSentDateRequest> <ns1:GetSentDate> <ns1:AllowSundaySorting>false</ns1:AllowSundaySorting> <ns1:City>Berlin</ns1:City> <ns1:CountryCode>NL</ns1:CountryCode> <ns1:DeliveryDate>05-05-2020</ns1:DeliveryDate> <ns1:HouseNr/> <ns1:HouseNrExt/> <ns1:Options> <ns2:string>Daytime</ns2:string> </ns1:Options> <ns1:PostalCode>2132WT</ns1:PostalCode> <ns1:ShippingDuration>1</ns1:ShippingDuration> <ns1:Street/> </ns1:GetSentDate> <ns1:Message> <ns1:MessageID>9d217a370d4bcf4af560db0af9b82db1</ns1:MessageID> <ns1:MessageTimeStamp>04-05-2020 16:39:53</ns1:MessageTimeStamp> </ns1:Message> </ns3:GetSentDateRequest> </env:Body> </env:Envelope> <<<< Response XML >>>> <?xml version="1.0"?> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"> <s:Body> <s:Fault> <faultcode>s:CIF Framework Message Interceptor</faultcode> <faultstring xml:lang="en-US">Check CIFException in the detail section</faultstring> <detail> <CifException xmlns="http://postnl.nl/cif/services/common/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"> <Errors> <ExceptionData> <Description i:nil="true"/> <ErrorMsg>Verzending van deze productoptie voor deze bezorgdatum is niet meer mogelijk.</ErrorMsg> <ErrorNumber>2060</ErrorNumber> </ExceptionData> </Errors> </CifException> </detail> </s:Fault> </s:Body> </s:Envelope>`

**Comment by rhaselager** [comment]
Hi! For a client we're experiencing exactly the same thing since today.

**Comment by tig-jaspersmits** [comment]
Hi @KoenSlagter and @rhaselager ,

Thanks for your message. Unfortunate to hear that these problems were experienced. We are working on this together with PostNL to find a solution. I think this problem should not occur any more today. Can you confirm that?

Kind regards,
Jasper
TIG

**Comment by rhaselager** [comment]
Thanks for your reply. The customer didn't experience any issues yesterday. But to be safe I updated the PostNL module to it's latest version yesterday.

**Comment by tig-jaspersmits** [comment]
Hi @rhaselager ,

Good to hear. We are still looking into a solution for this, so it doesn't happen again next year. It was related to the 5th of May not being a date on which deliveries could take place.

Kind regards,
Jasper
TIG

**Comment by jemico** [comment]
Hi all,

I have the same problem here with m2.3.3 and tig1.9.2. I even have it with shipping for netherlands.

When an customer select shipping 7may i cann't send it on 8may (payment was to late). The stranges thing is that it only fails on live production.

`Check CIFException in the detail section - 2060: Verzending van deze productoptie voor deze bezorgdatum is niet meer mogelijk. <<<< Request XML >>>> <?xml version="1.0" encoding="UTF-8"?> <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://postnl.nl/cif/domain/DeliveryDateWebService/" xmlns:ns2="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:ns3="http://postnl.nl/cif/services/DeliveryDateWebService/"> <env:Header/> <env:Body> <ns3:GetSentDateRequest> <ns1:GetSentDate> <ns1:AllowSundaySorting>false</ns1:AllowSundaySorting> <ns1:City>Vlissingen</ns1:City> <ns1:CountryCode>NL</ns1:CountryCode> <ns1:DeliveryDate>05-05-2020</ns1:DeliveryDate> <ns1:HouseNr/> <ns1:HouseNrExt/> <ns1:Options> <ns2:string>Pickup</ns2:string> </ns1:Options> <ns1:PostalCode>4384HD</ns1:PostalCode> <ns1:ShippingDuration>1</ns1:ShippingDuration> <ns1:Street/> </ns1:GetSentDate> <ns1:Message> <ns1:MessageID>635891be7fc876345fcc61c1c8a0baba</ns1:MessageID> <ns1:MessageTimeStamp>09-05-2020 17:54:37</ns1:MessageTimeStamp> </ns1:Message> </ns3:GetSentDateRequest> </env:Body> </env:Envelope> <<<< Response XML >>>> <?xml version="1.0"?> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"> <s:Body> <s:Fault> <faultcode>s:CIF Framework Message Interceptor</faultcode> <faultstring xml:lang="en-US">Check CIFException in the detail section</faultstring> <detail> <CifException xmlns="http://postnl.nl/cif/services/common/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"> <Errors> <ExceptionData> <Description i:nil="true"/> <ErrorMsg>Verzending van deze productoptie voor deze bezorgdatum is niet meer mogelijk.</ErrorMsg> <ErrorNumber>2060</ErrorNumber> </ExceptionData> </Errors> </CifException> </detail> </s:Fault> </s:Body> </s:Envelope>`

**Comment by tig-jaspersmits** [comment]
Hi @jemico ,

Thanks for letting us know. We also saw problems with addresses not based in the Netherlands. So, we are aware of this as well. As mentioned in my previous message, we are still looking into this together with PostNL.

Kind regards
Jasper
TIG

**Comment by tjitsejdevries** [comment]
@tig-jaspersmits 

Has it been fixed yet? There's another holiday comming up thursday and one on first of june.

**Comment by tig-jaspersmits** [comment]
Hi @tjitsejdevries ,

This is something on the PostNL side that needs be changed. It's not coming from the extension. We informed PostNL about this and they are looking into it. I expect to give a follow up response on this tomorrow.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @tjitsejdevries ,

PostNL will send out an e-mail informing everyone about how to handle the orders. They will probably recommend handling the orders the next day. For more information I recommend contacting PostNL about this.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @tjitsejdevries ,

This is the official message PostNL has sent to all the merchants. It's in Dutch, but I don't think that is a problem.

_"Beste klant,

Als een consument vandaag (20-05-2020) een bestelling plaats met de
bezorgoptie ‘Eerst volgende mogelijkheid’ en de webshop-eigenaar deze
bestelling vandaag wilt voormelden, dan wordt er een foutmelding getoond.

Het is een bekend probleem en heeft te maken met het feit dat PostNL niet
op Hemelvaartsdag bezorgd. Wij doen ons uiterste best om dit zo snel
mogelijk op te lossen.

Als je deze foutmelding ontvangt bij het voormelden van een bestelling, dan
raden wij u aan deze bestelling morgen voor de melden.

Excuus voor het ongemak. Wij hopen je voldoende geïnformeerd te hebben. Heb
je nog vragen? Neem dan contact op met ons.

Wij zijn bereikbaar via digitaleklantsupport@postnl.nl en 088 225 56 51.

Met vriendelijke groet/Kind regards,

Digitale Klant Support"_

Kind regards,
Jasper
TIG

**Comment by jemico** [comment]
I do not think this will solve or work like an workaround. We still have orders we cann't complete because of this error. If i try to ship i get this message and is not depending on when i try to ship in magento.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jemico,

Together with PostNL we are still looking for the right solution. You should be able to make order via mijn.postnl if this happens again.  Are you still having problems with the orders today?

Have a great day,
Jeffrey

**Comment by jemico** [comment]
I have for example an order from the last time that gives this error, i cannot proces that order. How can i fix this? maybe beter to e-mail directly?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jemico,

Yes, in this case it would be beter to e-mail directly, could you mail us on support@tig.nl ?

Have a great day,
Jeffrey

**Comment by tig-jaspersmits** [comment]
I will close this ticket.
I'm guessing you followed up on this through mailing us.

Kind regards,
Jasper
TIG

**Comment by atty31** [comment]
I 'm getting the same issue: 
This is registered in the postnl logs:

```
<<<< Request XML >>>>
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://postnl.nl/cif/domain/DeliveryDateWebService/" xmlns:ns2="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:ns3="http://postnl.nl/cif/services/DeliveryDateWebService/">
  <env:Header/>
  <env:Body>
    <ns3:GetSentDateRequest>
      <ns1:GetSentDate>
        <ns1:AllowSundaySorting>true</ns1:AllowSundaySorting>
        <ns1:City>Rotterdam</ns1:City>
        <ns1:CountryCode>NL</ns1:CountryCode>
        <ns1:DeliveryDate>08-08-2020</ns1:DeliveryDate>
        <ns1:HouseNr/>
        <ns1:HouseNrExt/>
        <ns1:Options>
          <ns2:string>Daytime</ns2:string>
        </ns1:Options>
        <ns1:PostalCode>3025AR</ns1:PostalCode>
        <ns1:ShippingDuration>1</ns1:ShippingDuration>
        <ns1:Street/>
      </ns1:GetSentDate>
      <ns1:Message>
        <ns1:MessageID>ce1821ac5b3e7e582d2a1179dad78322</ns1:MessageID>
        <ns1:MessageTimeStamp>07-08-2020 10:19:30</ns1:MessageTimeStamp>
      </ns1:Message>
    </ns3:GetSentDateRequest>
  </env:Body>
</env:Envelope>


<<<< Response XML >>>>
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <s:Fault>
         <faultcode>s:CIF Framework Message Interceptor</faultcode>
         <faultstring xml:lang="en-US">Check CIFException in the detail section</faultstring>
         <detail>
            <CifException xmlns="http://postnl.nl/cif/services/common/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
               <Errors>
                  <ExceptionData>
                     <Description i:nil="true"/>
                     <ErrorMsg>Verzending van deze productoptie voor deze bezorgdatum is niet meer mogelijk.</ErrorMsg>
                     <ErrorNumber>2060</ErrorNumber>
                  </ExceptionData>
               </Errors>
            </CifException>
         </detail>
      </s:Fault>
   </s:Body>
</s:Envelope>
 [] []
```

I am using Magento 2.3.4 and version: 1.9.0.1 of the tig/postnl-magento2 module. All I did is to create a new order from the backoffice and select a source and when I submit the shipment, I got redirected back to the page where I need to select a source. 
Any idea ? What is the exact reason of this feedback ? Also the error code: 2060 it is not either in this list: https://developer.postnl.nl/browse-apis/send-and-track/error-codes/

**Comment by tig-dennisvanderhammen** [comment]
Hi @atty31 ,

Recently PostNL changed a part in their API where they handle the DeliveryDate. DeliveryDate is required to have a timestamp now.
Currently your DeliveryDate contains the value 08-08-2020. If you change this to 08-08-2020 00:00:00, the PostNL API will accept your call.

In most cases this is fixed in 1.9.4, but there are still cases where the mass-actions send a date without a timestamp. This will be fixed in the upcoming release.

**Comment by atty31** [comment]
Hi @tig-dennisvanderhammen , 
Thnx for your fast reply 👍  . Do you know when is your next release planned ?

**Comment by tig-dennisvanderhammen** [comment]
Hi @atty31,

Our aim is next Monday, but I can't promise anything!
