### ISSUE TITLE
[BUG] Select option in action menu on order grid, drops koElement.actions is not a function

### ISSUE THREAD

**Issue by ZIPITRO** [tig-nl/postnl-magento2#173]
Hi Guys!

Please help to fix the following.
When you open the order grid in Magento, select an order, select an action other than a PostNL items in the action menu which is a submenu item (see screenshot) it drops an error. 
When the PostNL module is disabled it works as expected.

**To Reproduce**
1. When you open the order grid
2. And select an order
3. Select an action other than a PostNL items in the action menu which is a sub item (see screenshot) it drops below message:
![export-werkt-niet-zonder-postnl-mod](https://user-images.githubusercontent.com/22952492/81798046-39d16780-9518-11ea-9262-b463276c8553.png)
Uncaught TypeError: koElement.actions is not a function
    at getPostNLAction ((index):230)
    at HTMLSpanElement.<anonymous> ((index):184)
    at HTMLBodyElement.dispatch (jquery.min.js:338)
    at HTMLBodyElement.elemData.handle (jquery.min.js:311)
getPostNLAction @ (index):230
(anonymous) @ (index):184
dispatch @ jquery.min.js:338
elemData.handle @ jquery.min.js:311

**Expected result**
1. When you open the order grid
2. And select an order
3. Select an action other than a PostNL items in the action menu which is a sub item it shows the actual sub menu ( see second screenshot )
![export-werkt-zonder-postnl-mod](https://user-images.githubusercontent.com/22952492/81798053-3c33c180-9518-11ea-8fda-ca65f3abc272.png)
**Actual result**
Below you will find in the console as output:
Uncaught TypeError: koElement.actions is not a function
    at getPostNLAction ((index):230)
    at HTMLSpanElement.<anonymous> ((index):184)
    at HTMLBodyElement.dispatch (jquery.min.js:338)
    at HTMLBodyElement.elemData.handle (jquery.min.js:311)
getPostNLAction @ (index):230
(anonymous) @ (index):184
dispatch @ jquery.min.js:338
elemData.handle @ jquery.min.js:311

**Workaround**
None found yet

**Screenshots**
Added :-)

** Please complete the following information**
- Magento version: 2.3.5-p1
- PHP version: 7.2
- TIG PostNL version: 1.9.2

Thanks a lot for your advice and expertise!

#staysafe! #staystrong!

Paul

**Comment by tig-dennisvanderhammen** [comment]
Hey @ZIPITRO ,

Interesting. i personally don't use the non-PostNL mass actions, so I wonder when these actually broke. I'll create a backlog item to fix this issue.

A temporary workaround might be removing the part causing the error, which is found in the following file:
view/adminhtml/templates/order/grid/DownloadPdfAction.phtml
remove line 89 to 93 (the ko.utils.arrayForEach part).

Please test this out carefully, because I'm not sure what unintended consequences this might have. We'll have to see what exactly goes wrong, but after removing this I managed to use the other options.

**Comment by ZIPITRO** [comment]
Hi Dennis,

Indeed, I also remember it was working before.
Ah in the DownloadPdfAction file :-) I will test this workaround and let you know!

Thanks for your time and effort!

Ciao,

Paul

**Comment by ZIPITRO** [comment]
Hi!
No errors and works indeed, no side-effects so far for us, only wonder why it positions the submenu on the bottom of the page, sounds familiar? Can fix this with CSS, but I think something else is causing this.
Thanks!

**Comment by tig-dennisvanderhammen** [comment]
To be fair, I didn't even know it was possible to create submenu's in mass-actions. Is this also a problem with the PostNL extension disabled?

**Comment by ZIPITRO** [comment]
Hi! 
When the PostNL extension is disabled its showing the submenu in the middle of the page, therefore I think its caused by something else, but need to look into it as well as shown in the second screenshot I've send before. 
Of course I can add a top:412px;  for .action-submenu CSS and that will fix that as well, but its ugly.

Thanks for your time!

**Comment by tig-jaspersmits** [comment]
Hi @ZIPITRO ,

It's been some time, but do we still need to do something? Look into this?
Or did you manage to find a solution for this?

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
I'll close this issue.
If there is anything else, feel free to open a new one.

Kind regards,
Jasper
TIG
