### ISSUE TITLE
Track & Trace URL is missing a language parameter

### ISSUE THREAD

**Issue by evs-xsarus** [tig-nl/postnl-magento2#174]
**To Reproduce**
1. Create a new order for a Dutch locale store
2. Ship it so the Track & Trace URL is set 
3. Follow the URL

**Expected result**
The PostNL track & trace page is shown in Dutch.

**Actual result**
The PostNL track & trace page is shown in English

**Workaround**
Not tested yet, but I was thinking of adding the paramter 'L=NL' to the URL for this store locale. This could be automated.

** Please complete the following information**
- Magento version: 2.3.4
- PHP version: 7.3.0
- TIG PostNL version: 1.9.0.1

NB The workaround is based on information received in https://jira.tig.nl/servicedesk/customer/portal/9/SDPOSTNL-11803 and this file:

[stappenkaart-track-trace-directe-links-jan2017_tcm15-66060.pdf](https://github.com/tig-nl/postnl-magento2/files/4633232/stappenkaart-track-trace-directe-links-jan2017_tcm15-66060.pdf)

**Comment by tig-jaspersmits** [comment]
Hi @evs-xsarus ,

Thanks for your message. I will let our developer take a look at it.
When there is more information, I will share it with you.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @evs-xsarus ,

I've created a backlog ticket for this. We will implement this in an upcoming release. You can keep an eye on the release notes here: https://docs.tig.nl/x/3YSC

If you have any questions about this, please let me know.

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
The URL mentioned in the SDPOSTNL issue has the following querystring added:
"D=NL", This country code is based on the address its country ID. 

Now I assume D stands for Destination. I'm wondering if PostNL ever did something with the destination for language, or if they can do anything with that. Anyway, adding "L=NL" to the querystring does send me to the Dutch version. If you want to create a patch for your client, you can try adding this querystring param in the following code:

method: generateTrackAndTraceUrl
file: app/code/TIG/PostNL/Helper/AbstractTracking.php

Please test this carefully on a staging before deploying this on a production website.

We'll get in touch with PostNL about whether we'll add a "L=NL", or see if they can redirect based on the destination.

**Comment by evs-xsarus** [comment]
@tig-dennisvanderhammen als je de informatie hebt ontvangen en een change hebt gemaakt, dan wil ik die graag testen.

**Comment by tig-dennisvanderhammen** [comment]
Hi @evs-xsarus,

The code is still in internal review, but here is the patch file for the PR that I've created on our private repository.

[locale_in_tracktrace.txt](https://github.com/tig-nl/postnl-magento2/files/4770151/locale_in_tracktrace.txt)

**Comment by tig-jaspersmits** [comment]
This should be fixed in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG
