### ISSUE TITLE
Class TIG\PostNL\Config\Provider\ProductType does not exist

### ISSUE THREAD

**Issue by BitweenTech** [tig-nl/postnl-magento2#178]
I get the following error when I installed the module via the steps shown in the readme:

Class TIG\PostNL\Config\Provider\ProductType does not exist. Class TIG\\PostNL\\Config\\Provider\\ProductType does not exist at /magento/releases/1/vendor/magento/framework/Code/Reader/ClassReader.php:26.

Does anyone have any idea how I can fix this issue?

**Comment by tig-jaspersmits** [comment]
Hi @BitweenTech ,

Thanks for contacting us. Could you please use the template the next time when you create an issue like this? Thanks in advance!

What Magento version are you using?

Kind regards,
Jasper
TIG

**Comment by mtjweb** [comment]
I have the same problem. Installled the module with composer to test it and after that uninstalled it with composer. Error is showing when you open a product in admin.

I'm using Magento 2.2.11.

**Comment by tig-jaspersmits** [comment]
Good morning @mtjweb ,

I just set up a clean Magento 2.2.11 environment, installed PostNL and opened a product from the backend. I don't see any errors show up. Where do you see this error exactly?

Kind regards,
Jasper

**Comment by mtjweb** [comment]
Uninstall the app with composer (composer remove tig/postnl-magento2). Then go to Catalog -> Products and open a product. Then you see the error.

**Comment by tig-jaspersmits** [comment]
Thanks for your response @mtjweb ,

I've just added this to our backlog. We will work on a fix and implement it in an upcoming release.

Kind regards,
Jasper
TIG

**Comment by mtjweb** [comment]
Is there a way to solve the error in de webshop now?

**Comment by tig-jaspersmits** [comment]
HI @mtjweb , 

I'll ask but I don't think there is a fix just yet.
Will let you know when I have more information.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @mtjweb ,

Just received a response from my colleague.
You should be able to use this workaround:

`delete from from eav_attribute where source_model like ‘%PostNL%’;`

Kind regards,
Jasper
TIG

**Comment by mtjweb** [comment]
Thanks, that solved it for me.

**Comment by tig-jaspersmits** [comment]
@mtjweb no problem! Glad to hear it solved your problem.

Kind regards,
Jasper

**Comment by atty31** [comment]
I also confirm this issue and work around suggested by @tig-jaspersmits worked for me!
