### ISSUE TITLE
[BUG] Printing label from the sales order grid 

### ISSUE THREAD

**Issue by atty31** [tig-nl/postnl-magento2#179]
Hi,

**Description of the issue**
I would like to print my generated label from the sales order grid using the default Magento option, called: **Print Shipping Labels**. If I select an order and press the **Print Shipping Labels** option from Actions dropdown, I am getting the following message: _"There are no shipping labels related to selected orders."_ 
Also the **shipping_label** column from the sales_shipment table , its value remains null (that's why that meesage). 

**To Reproduce**
1. Create an order and shipment
2. Generate the label from the shipment page.
3. After the label is generated , go to the sales order grid and press select from the Actions dropdown the **Print Shipping Labels** option. 

**Expected result**
Should download the pdf label/s

**Actual result**
Getting the _"There are no shipping labels related to selected orders."_ message

**Workaround**
Select from the Actions dropdown the **PostNL - Create shipments, print labels & confirm** option. But this is very confusing, since I already generated a label and i have a shipment.  Maybe you should have another option, with just the **Print the labels**. 

**Please complete the following information**
- Magento version: 2.3.3 and 2.3.4
- PHP version: 7.2
- TIG PostNL version: 1.9.0.1

**Comment by tig-jeffreybranderhorst** [comment]
Hi @atty31,

This is true, on the shipment grid you also got PostNL - Print labels & confirm the system will not confirm it again, it will only print the labels. I will put the functie of only PostNL - Print labels on the backlog, thank you for submitting this feature and helping us!

Have a great day,
Jeffrey

**Comment by atty31** [comment]
Hi @tig-jeffreybranderhorst ,

So will you add another option (with just having the _printing label_ ) ? or do you intend also to fix  the default Magento functionality with the **Print Shipping Labels** option ? and making sure the shipping_label column will not be empty or null  once a postnl label is generated. Looking forward hearing from you and thank you

Cheers!

**Comment by tig-jaspersmits** [comment]
Hi @atty31 ,

This is a delayed reaction to your question but, we will keep it the way it is for now.
We appreciate your input though! Thank for that.

Kind regards,
Jasper
TIG
