### ISSUE TITLE
Elke save op order = extra pakje gemak adres.

### ISSUE THREAD

**Issue by Mark-Sherpaan** [tig-nl/postnl-magento2#18]
Het `sales_order_save_after` event zorgt ervoor dat er na elke save van een order er een extra pakjegemak adres wordt opgeslagen. Dit kan meerdere keren gebeuren, wat resulteert in een hoop extra adressen.
https://github.com/tig-nl/postnl-magento2/blob/701483ddec08058c7578f49eb1962c81bf9c9d4b/Observer/SalesOrderSaveAfter/AddressToOrder.php#L89

Is het misschien netter om daarvoor het event `sales_order_place_after` te gebruiken, of een 'after' plugin op `\Magento\Sales\Api\OrderManagementInterface::place`?

**Comment by tig-jaspersmits** [comment]
Good morning Mark,

I have created a issue on our backlog for this. You can follow the progress trough this url: https://jira.tig.nl/projects/POSTNLM2/issues/POSTNLM2-377 PostNL will decide the priority of the issues on this backlog so it is up to them when they want us to implement it.

I recommend following that issue to stay up-to-date about the status.

Kind regards,

Jasper
TIG

**Comment by tig-jeffreybranderhorst** [comment]
Hello Mark-Sherpaan,

I just looked up this issue. And it should be in our newest version of the extension. Because of that, I will close this issue.

Best regards,
Jeffrey
