### ISSUE TITLE
[BUG] Selected delivery/pickup options was gone after reload page

### ISSUE THREAD

**Issue by fu4d** [tig-nl/postnl-magento2#181]
After select the PostNL options then reload or go back to shipping method page, we won't find the selected option before (But shipping fee has calculated).

**To Reproduce**
1. Select product
2. Go to checkout page
3. Choose Netherlands or Belgium valid address
4. Choose PostNL one of Delivery or Pickup options
5. Reload your checkout page

**Expected result**
Our chosen option should be still selected

**Actual result**
No PostNL option selected

**Comment by tig-jeffreybranderhorst** [comment]
Goodmorning,

Thank you for submitting this, we will put it on the backlog. In the newest version 1.9.3 there will be a fix that delivery options are obligated so customers are gonna need to select a day even if selected value is deselected. 

Have a great day,
Jeffrey

**Comment by tig-jaspersmits** [comment]
This should be fixed in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG
