### ISSUE TITLE
[BUG] Generating a label for multiple orders prints each label on a seperate a4 page

### ISSUE THREAD

**Issue by one1note** [tig-nl/postnl-magento2#183]
**To Reproduce**
1. Go to 'Sales > Orders'
2. Select 2 or more orders
3. Under actions click "PostNL create shipment print labels and confirm."

**Expected result**
Multiple labels are fit on a single A4 page (same as in the PostNL Web app). 

**Actual result**
Each a6 label is printed on a separate a4 page.

**Workaround**
none

**Screenshots**

** Please complete the following information**
- Magento version: 2.3.5
- PHP version: 7.3
- TIG PostNL version: 1.9.3

**Comment by tig-jaspersmits** [comment]
Hi @one1note ,

Thanks for opening this issue. I'll see if I can reproduce this and get back to you.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @one1note ,

I just tried to reproduce this, but the labels all show up on one A4.
Are you running any other extensions by any chance?

Kind regards,
Jasper
TIG

**Comment by one1note** [comment]
Hi @tig-jaspersmits 

Thanks for looking into this. 

I just found out that It probably is a browser related issue. It works in Chrome (Ubuntu), but the print option to fit multiple pages in 1 is missing in Firefox (Ubuntu).

**Comment by tig-jaspersmits** [comment]
Hi @one1note .

Thanks for your response! I've just tested this on Firefox as well, but.. no problems here.
Not running any other extensions which could impact this?

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
I'd like to shine in a bit as well,

It's actually the extension that merges all the PostNL labels into one A4.
To be more exact, it's this piece of code that starts working on putting everything in one A4:
\TIG\PostNL\Service\Shipment\Label\Merge\A4Merger::files

It seems weird that a browser could affect this in any way.

Could you please confirm that Extra Settings -> Printer settings -> Label format is set to A4? Maybe it's set to A6 and your browser shows the PDFs as A4?
You could also check if your code reaches line 109 in app/code/TIG/PostNL/Service/Shipment/Label/Merge/A4Merger.php
This if-statement is where the extension checks if the PDF requires a new page, which should return false a few times, and only true if a new page is required.

**Comment by one1note** [comment]
@tig-dennisvanderhammen 

Thank you Dennis, I misinterpreted this setting thinking the A4 setting would print each label in A4.

It is working properly now without having to change the print options. 

Thanks a lot for the quick response.
