### ISSUE TITLE
[BUG] Please summarize your bug issue here

### ISSUE THREAD

**Issue by dheesbeen** [tig-nl/postnl-magento2#184]
**To Reproduce**
1. Configure Magento to use 3 address lines (streetline 1 streetname) (streetline 2 number) (streetline 3 addition) 
2. Disable address check (getIsAddressCheckEnabled)
3. Go to the checkout and use the following address

Schiedamseweg Beneden, 527, 01R
3028BV Rotterdam

**Expected result**
Delivery Timeframes wil show up in the checkout

**Actual result**
Delivery Timeframes fail to load because the address is not fount.

Helper/AddressEnhancer.php

Wil try to extract the house number with a regex. The request will be done with housenumber 01 instead of 529 

**Workaround**
\TIG\PostNL\Helper\AddressEnhancer::extractHousenumber
In case of a three line address we always execute the extractIndividual method to fix this for now

**Screenshots**
--

** Please complete the following information**
- Magento version: 2.3.3-p1
- PHP version: 7.2
- TIG PostNL version: 1.9.2.1

**Comment by tig-jaspersmits** [comment]
Hi @dheesbeen ,

Thanks for submitting this. I discussed this with the team and unfortunately there is not much we can do about this. In this situation we can only advise to use the Address Check or to use less address  lines.

Kind regards,
Jasper
TIG

**Comment by dheesbeen** [comment]
@tig-jaspersmits  I do not agree that this is not something you guys can't fix. My opinion is that you should fix it. Imploding to one line and applying a regex is not needed when jou already work with separate fields. This is some you can control by a simple setting.

I will inform the client that this bug won't be fixed by POSTNL / TIG. 

Thanks for you response.

Derrick

**Comment by tig-jaspersmits** [comment]
Hi @dheesbeen ,

Thanks for your response and sharing your view on this. Appreciated. There are many users of the PostNL extension and everybody uses it in different ways. 

The way it’s coded right now is how we agreed upon with PostNL. We would need to make a lot of changes to change it to the way you are suggesting. The workaround would be to enable the Address Check.

We are open on receiving feedback on how you would fix this in the code. If you have thoughts about this, please submit a pull request so we can take a look at it.

Thanks again!

Kind regards,

Jasper
TIG
