### ISSUE TITLE
[BUG] ScopeType is invalid bug in v1.9.4 of generateTrackAndTraceUrl

### ISSUE THREAD

**Issue by comaxxdevelopment** [tig-nl/postnl-magento2#186]
**To Reproduce**
1. Set up multiple stores in magento. 
2. Change the default store's storecode (in Stores->All Stores) to 'nl' (example).
3. Create a valid order for PostNL
4. Go to the order overview in the backend.
5. Select the recently made order and use the action 'PostNL - Create shipments, print labels & confirm'.

**Expected result**
Shipment is made successfully without errors.

**Actual result**
The overview displays an error [POSTNL-0252] - There are no valid labels generated. Please check the logs for more information'
The following stack trace can be found in the logs:
`{"0":"Invalid scope type 'nl'","1":"#1 Magento\\Framework\\App\\Config\\ScopeCodeResolver->resolve() called at [vendor\/magento\/framework\/App\/Config.php:69]\n#2 Magento\\Framework\\App\\Config->getValue() called at [vendor\/tig\/postnl-magento2\/Helper\/AbstractTracking.php:178]\n#3 TIG\\PostNL\\Helper\\AbstractTracking->generateTrackAndTraceUrl() called at [vendor\/tig\/postnl-magento2\/Helper\/AbstractTracking.php:161]\n#4 TIG\\PostNL\\Helper\\AbstractTracking->getTrackAndTraceUrl() called at [vendor\/tig\/postnl-magento2\/Helper\/Tracking\/Track.php:267]\n#5 TIG\\PostNL\\Helper\\Tracking\\Track->sendTrackAndTraceEmail() called at [vendor\/tig\/postnl-magento2\/Helper\/Tracking\/Track.php:175]\n#6 TIG\\PostNL\\Helper\\Tracking\\Track->send() called at [vendor\/tig\/postnl-magento2\/Observer\/TIGPostNLSetConfirmedAtBefore\/SendTrackAndTraceEmail.php:61]\n#7 TIG\\PostNL\\Observer\\TIGPostNLSetConfirmedAtBefore\\SendTrackAndTraceEmail->execute() called at [vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php:88]\n#8 Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod() called at [vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php:74]\n#9 Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch() called at [vendor\/magento\/framework\/Event\/Manager.php:66]\n#10 Magento\\Framework\\Event\\Manager->dispatch() called at [generated\/code\/Magento\/Framework\/Event\/Manager\/Proxy.php:95]\n#11 Magento\\Framework\\Event\\Manager\\Proxy->dispatch() called at [vendor\/tig\/postnl-magento2\/Model\/Shipment.php:627]\n#12 TIG\\PostNL\\Model\\Shipment->setConfirmedAt() called at [vendor\/tig\/postnl-magento2\/Service\/Shipment\/Labelling\/GenerateAbstract.php:121]\n#13 TIG\\PostNL\\Service\\Shipment\\Labelling\\GenerateAbstract->getLabel() called at [vendor\/tig\/postnl-magento2\/Service\/Shipment\/Labelling\/Generate\/WithConfirm.php:91]\n#14 TIG\\PostNL\\Service\\Shipment\\Labelling\\Generate\\WithConfirm->get() called at [vendor\/tig\/postnl-magento2\/Service\/Shipment\/Labelling\/GenerateLabel.php:72]\n#15 TIG\\PostNL\\Service\\Shipment\\Labelling\\GenerateLabel->get() called at [vendor\/tig\/postnl-magento2\/Service\/Shipment\/Labelling\/GetLabels.php:145]\n#16 TIG\\PostNL\\Service\\Shipment\\Labelling\\GetLabels->getLabels() called at [vendor\/tig\/postnl-magento2\/Service\/Shipment\/Labelling\/GetLabels.php:113]\n#17 TIG\\PostNL\\Service\\Shipment\\Labelling\\GetLabels->get() called at [vendor\/tig\/postnl-magento2\/Controller\/Adminhtml\/LabelAbstract.php:122]\n#18 TIG\\PostNL\\Controller\\Adminhtml\\LabelAbstract->setLabel() called at [vendor\/tig\/postnl-magento2\/Controller\/Adminhtml\/Order\/CreateShipmentsConfirmAndPrintShippingLabels.php:187]\n#19 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels->loadLabel() called at [vendor\/tig\/postnl-magento2\/Controller\/Adminhtml\/Order\/CreateShipmentsConfirmAndPrintShippingLabels.php:167]\n#20 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels->loadLabels() called at [vendor\/tig\/postnl-magento2\/Controller\/Adminhtml\/Order\/CreateShipmentsConfirmAndPrintShippingLabels.php:143]\n#21 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels->createShipmentsAndLoadLabels() called at [vendor\/tig\/postnl-magento2\/Controller\/Adminhtml\/Order\/CreateShipmentsConfirmAndPrintShippingLabels.php:114]\n#22 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#23 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#24 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#25 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#26 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#27 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#28 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#29 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->___callPlugins() called at [generated\/code\/TIG\/PostNL\/Controller\/Adminhtml\/Order\/CreateShipmentsConfirmAndPrintShippingLabels\/Interceptor.php:26]\n#30 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#31 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#32 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#33 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#34 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#35 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#36 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#37 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#38 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n","url":"\/admin\/postnl\/order\/CreateShipmentsConfirmAndPrintShippingLabels\/key\/e80089a737e18aaeb38793b60f76faf7e22acf9f90ded36a9e9359edd18a473a\/","script_name":"\/index.php","report_id":"238562309181b9d5f9b650aaccedc8db387d83c7d5f3d8e4495f11434a21a1db"}`

**Workaround**
To explain: in postnl-magento2/Helper/AbstractTracking.php:178 (see error log). The code uses the $store of the order and gets the code belonging to it. However the code is a custom field which can be changed to 'nl' in our case (since we have multiple stores). 
Magento i believe only knows 'default', 'website' and 'store'. 
So a config workaround would be to only use one of these as your custom storecode (magento uses 'default' i think if you have a fresh install which is why this bug might of been missed). 
For an override: Since the third parameter already provides the storeId the bug can be solved by using ScopeInterface::SCOPE_STORES as the 2nd parameter instead of $store->getCode() in an override. 

**Screenshots**
-

** Please complete the following information**
- Magento version: 2.3.4
- PHP version: 7.2.19
- TIG PostNL version: 1.9.4

**Comment by tig-jaspersmits** [comment]
Hi @comaxxdevelopment ,

Thanks for letting us know and unfortunate to hear you are running into this problem.
We will test this as soon as possible and get back to you.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @comaxxdevelopment ,

I just followed your exact steps, but I'm not getting an error when trying to reproduce this. 
But, I'll ask a developer to take a look at this at well.

@tig-dennisvanderhammen can you take a look at this?

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @comaxxdevelopment ,

This should fix it:

File: /Helper/AbstractTracking.php
Replace contents of file with:
`<?php
/**
 *
 *          ..::..
 *     ..::::::::::::..
 *   ::'''''':''::'''''::
 *   ::..  ..:  :  ....::
 *   ::::  :::  :  :   ::
 *   ::::  :::  :  ''' ::
 *   ::::..:::..::.....::
 *     ''::::::::::::''
 *          ''::''
 *
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License.
 * It is available through the world-wide-web at this URL:
 * http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to servicedesk@tig.nl so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for your
 * needs please contact servicedesk@tig.nl for more information.
 *
 * @copyright   Copyright (c) Total Internet Group B.V. https://tig.nl/copyright
 * @license     http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 */
namespace TIG\PostNL\Helper;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Sales\Api\Data\OrderAddressInterface;
use Magento\Store\Model\ScopeInterface;
use TIG\PostNL\Model\ShipmentRepository as PostNLShipmentRepository;
use TIG\PostNL\Model\Shipment as PostNLShipment;
use TIG\PostNL\Config\Provider\Webshop;
use TIG\PostNL\Logging\Log;
use Magento\Framework\App\Helper\AbstractHelper;
use Magento\Framework\App\Helper\Context;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\Framework\Api\AbstractExtensibleObject;
use TIG\PostNL\Api\ShipmentBarcodeRepositoryInterface;

abstract class AbstractTracking extends AbstractHelper
{
    /**
     * @var PostNLShipmentRepository
     */
    //@codingStandardsIgnoreLine
    protected $postNLShipmentRepository;

    /**
     * @var SearchCriteriaBuilder
     */
    //@codingStandardsIgnoreLine
    protected $searchCriteriaBuilder;

    /**
     * @var Webshop
     */
    //@codingStandardsIgnoreLine
    protected $webshopConfig;

    /**
     * @var Log
     */
    //@codingStandardsIgnoreLine
    protected $logging;

    /**
     * @var ShipmentBarcodeRepositoryInterface
     */
    //@codingStandardsIgnoreLine
    protected $shipmentBarcodeRepositoryInterface;

    /**
     * @param Context                            $context
     * @param PostNLShipmentRepository           $postNLShipmentRepository
     * @param SearchCriteriaBuilder              $searchCriteriaBuilder
     * @param Webshop                            $webshop
     * @param Log                                $logging
     * @param ShipmentBarcodeRepositoryInterface $shipmentBarcodeRepositoryInterface
     * @param ScopeConfigInterface               $scopeConfig
     */
    public function __construct(
        Context $context,
        PostNLShipmentRepository $postNLShipmentRepository,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        Webshop $webshop,
        Log $logging,
        ShipmentBarcodeRepositoryInterface $shipmentBarcodeRepositoryInterface,
        ScopeConfigInterface $scopeConfig
    ) {
        $this->postNLShipmentRepository           = $postNLShipmentRepository;
        $this->searchCriteriaBuilder              = $searchCriteriaBuilder;
        $this->webshopConfig                      = $webshop;
        $this->logging                            = $logging;
        $this->shipmentBarcodeRepositoryInterface = $shipmentBarcodeRepositoryInterface;
        $this->scopeConfig                        = $scopeConfig;
        parent::__construct($context);
    }

    /**
     * @param $shipmentId
     *
     * @return AbstractExtensibleObject[]
     */
    //@codingStandardsIgnoreLine
    protected function getPostNLshipments($shipmentId)
    {
        $searchCriteria = $this->searchCriteriaBuilder->addFilter('shipment_id', $shipmentId);
        /** @var \Magento\Framework\Api\SearchResults $list */
        $list = $this->postNLShipmentRepository->getList($searchCriteria->create());
        return $list->getItems();
    }

    /**
     * @param $trackingNumber
     *
     * @return AbstractExtensibleObject|\Magento\Framework\Api\SearchResults|\TIG\PostNL\Api\Data\ShipmentInterface
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    //@codingStandardsIgnoreLine
    protected function getPostNLshipmentByTracking($trackingNumber)
    {
        $searchCriteria = $this->searchCriteriaBuilder->addFilter('main_barcode', $trackingNumber);
        $searchCriteria->setPageSize(1);
        /** @var \Magento\Framework\Api\SearchResults $list */
        $list = $this->postNLShipmentRepository->getList($searchCriteria->create());

        if (!$list->getItems()) {
            $searchCriteria = $this->searchCriteriaBuilder->addFilter('value', $trackingNumber);
            $searchCriteria->setPageSize(1);
            $shipmentBarcode = $this->shipmentBarcodeRepositoryInterface->getList($searchCriteria->create());
            $shipmentId = $shipmentBarcode->getItems()[0]->getParentId();
            $list = $this->postNLShipmentRepository->getById($shipmentId);

            return $list;
        }

        return $list->getItems()[0];
    }

    /**
     * @param        $trackingNumber
     * @param string $type
     *
     * @return string
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    //@codingStandardsIgnoreLine
    protected function getTrackAndTraceUrl($trackingNumber, $type = 'C')
    {
        /** @var PostNLShipment $postNLShipment */
        $postNLShipment = $this->getPostNLshipmentByTracking($trackingNumber);
        /** @var \Magento\Sales\Api\Data\OrderAddressInterface $address */
        $address = $postNLShipment->getShippingAddress();

        return $this->generateTrackAndTraceUrl($address, $trackingNumber, $type);
    }

    /**
     * Generate the Track&Trace url based on an address.
     *
     * @param OrderAddressInterface $address
     * @param                       $trackingNumber
     * @param                       $type
     *
     * @return string
     */
    // @codingStandardsIgnoreLine
    protected function generateTrackAndTraceUrl(OrderAddressInterface $address, $trackingNumber, $type)
    {
        $order = $address->getOrder();
        $store = $order->getStore();
        $storeLocale = $this->scopeConfig->getValue('general/locale/code', ScopeInterface::SCOPE_STORE, $store->getStoreId());
        $language = substr($storeLocale, 3, 2);
        $params = [
            'B' => $trackingNumber,
            'D' => $address->getCountryId(),
            'P' => str_replace(' ', '', $address->getPostcode()),
            'T' => $type,
            'L' => $language
        ];

        return $this->webshopConfig->getTrackAndTraceServiceUrl() . http_build_query($params);
    }
}`

Let me know if this fixed it. This will be released in the next PostNL version.

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
Hi @comaxxdevelopment,

We just released version v1.9.4.1 which fixes this issue.
Thanks for letting us know!
