### ISSUE TITLE
[FEATURE] Take VAT settings into account for (matrix) shipping

### ISSUE THREAD

**Issue by downforce80** [tig-nl/postnl-magento2#188]
B2B Magento webshops in general work with excluding VAT catalog setting.
And if you are shipping internationally worldwide or within the EU you can also apply 0% VAT depending on the situation.

**Suggestions and background**
It would be great if the postNL shipping methods (matrix)rate would take the general magento VAT (inc/excl) setting into account when deciding what matrixrate to apply for the shipping.

Now we have to put the shipping price including VAT in the shipping matrixrates table.
This works in a situation where you deliver to B2B customers within the Netherlands.

For instance, you can set 121 euro (€ 100 + 21%) in the shipping matrix if you want to offer free shipping from 100 euro excl VAT. That works. 

But when dealing with B2B EU customers or worldwide (thus charged 0% VAT) they then have to spend 121 euro (0% tax) before they are offered free shipping.

It would be great if the function of the shipping methods (matrix)rate would look at the setting in stores > configuration > sales > tax > Calculation Settings. And from thereon decides if the shipping price in the (matrix)rate has to be considered with or without tax.

Related docs
https://docs.magento.com/user-guide/tax/tax-cross-border-price.html
https://docs.magento.com/user-guide/tax/vat.html

**Comment by tig-jaspersmits** [comment]
Hi @downforce80 ,

Thanks for your message. We appreciate feature request inputs like this.
I will ask my colleague @tig-dennisvanderhammen to take a look at this. If he also think this is a good idea (and realizable) we will put it on our backlog as a feature request and ask PostNL if they want to add this to the extension.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @downforce80 ,

I've added this to our backlog as a feature request. PostNL will determine if they want to add this to the extension. You can keep an eye on the release notes here: https://docs.tig.nl/x/3YSC

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
I will close this issue since there is no response from PostNL yet regarding this feature request.
If you want more information you could contact PostNL CIT about this.

Kind regards,
Jasper
TIG
