### ISSUE TITLE
[BUG] Pickup point address not saved when having telephone disabled in checkout

### ISSUE THREAD

**Issue by tbaltissen** [tig-nl/postnl-magento2#189]
**To Reproduce**
1. Place an order without logging in with telephone disabled in checkout. 
2. Choose "ophaalpunt" and proceed to checkout

**Expected result**
Name and address of ophaalpunt are shown at shipping address

**Actual result**
Shipping address of customer is used instead

Notice: Undefined index: telephone in /xxxxx/vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php on line 141

**Workaround**
On line 141 of Helper/DeliveryOptions/PickUpAddress.php comment $address->setTelephone($pgData['customer']['telephone']); 

** Please complete the following information**
- Magento version: 2.3.5
- PHP version: 7.2
- TIG PostNL version:  1.9.4

**Comment by tig-jaspersmits** [comment]
Hi @tbaltissen ,

Thanks for letting us know. I've just been able to reproduce this and I've added it to our backlog to be fixed. This should be fixed in an upcoming release of the extension. You can keep an eye on the release notes here: https://docs.tig.nl/x/3YSC

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
Hi @tbaltissen,

We just released version v1.9.4.1 which fixes this issue. Thank you again for pointing this out!
