### ISSUE TITLE
setasign/fpdi-fpdf is abondended and direct dependencies should be made

### ISSUE THREAD

**Issue by igorwulff** [tig-nl/postnl-magento2#193]
Direct dependencies are advised according to the meta package:
https://github.com/Setasign/FPDI-FPDF

`ABANDONED! We decided to abandon the meta package because of inconsistencies in the version systems used by the PDF generation libraries. As it is up to the developers to define which PDF generation library is used in their code it should be configured as a direct dependency in their own composer.json file too.

Please remove this package from your composer.json and replace it by direct dependencies to setasign/fpdi and setasign/fpdf.`

**Comment by tig-jaspersmits** [comment]
Hi @igorwulff ,

Thanks for sharing this with us. I'll put it on the backlog so we can take a look at this.

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
Hi @igorwulff ,

Thank you again for pointing this out. We've updated (or should I say reverted back to the old situation?) this and we now require the individual packages again. This was included in version 1.9.5 which just got released.
