### ISSUE TITLE
[FEATURE] Search bar for pick-up points

### ISSUE THREAD

**Issue by StijnSnijder** [tig-nl/postnl-magento2#197]
**Please rephrase the following line:**

As a certain type of user I'd like to describe what you want in order to write goal(s)

**Suggestions and background**

If you have ideas for the solution write them down here. Include images, a picture is more worth than 1,000 words. If none, remove this line.

Can you please ad a search bar for the Post NL pick-up points function. Now only the 5 nearby pick-up points are shown. We want to give our visitors the option that they can search pick-up points based on placename or zipcode.

![Schermafbeelding 2020-08-18 om 11 56 56](https://user-images.githubusercontent.com/69846517/90499535-f6574c80-e149-11ea-8c20-a6bae65a465a.png)
![Schermafbeelding 2020-08-18 om 11 56 38](https://user-images.githubusercontent.com/69846517/90499543-f7887980-e149-11ea-920e-7ffd9f2cc9a6.png)

**Comment by tig-jaspersmits** [comment]
Hi @StijnSnijder ,

Thanks for submitting this to us. I will place this on our backlog as a feature request and we will discuss this with PostNL. It's up to them to agree on the implementation of  this feature. When/if we add this in a future release, you can find it in the release notes here: https://docs.tig.nl/x/3YSC

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
I will close this issue as it is up to PostNL to decide if this should be implemented.
If there is anything else feel free to reopen the issue or create a new one.

Kind regards,
Jasper
TIG
