### ISSUE TITLE
Invalid Blocktype TIG\PostNL\Block\Sales\Order\Fee

### ISSUE THREAD

**Issue by SilvanLaroo** [tig-nl/postnl-magento2#2]
Hi Tig,

We've installed your extension via composer. In the frontend, when we view an order as customer we get this error:
`TIG\PostNL\Block\Sales\Order\Fee`

The block is not available in the module.

**Comment by tig-berendlantink** [comment]
Hi @SilvanLaroo,

Thanks for your feedback. We confirmed this issue and will fix it. 
Internal issue: POSTNLM2-232

**Comment by jghaanstra** [comment]
Any news on when this will be fixed? This is a pretty bad one for user experience.

**Comment by tig-berendlantink** [comment]
The issue is on our backlog and will be released together with some other issues.

**Comment by tig-berendlantink** [comment]
@jghaanstra Fix is ready and we will release Monday version 1.1.3.

**Comment by tig-michielgerritsen** [comment]
Hi @SilvanLaroo and @jghaanstra,

The 1.1.3 version of the extension is released yesterday. You can check the [release notes](https://confluence.tig.nl/display/TIGSD/Release+notes+van+de+PostNL+Magento+2+extensie) for more info. Updating the extension can be done by running:

``composer update tig/postnl-magento2``

**Comment by tig-martijndull** [comment]
test
