### ISSUE TITLE
After enabling additional PostNL options and letterpost the checkout breaks

### ISSUE THREAD

**Issue by martijnrmediact** [tig-nl/postnl-magento2#200]
After enabling additional PostNL options and selecting letterpost the checkout breaks and shows a blank page with only the header. When additional shipping options are disabled the checkout works as expected.

We are on the latest version of the module and using Magento Commerce 2.3.5.p2 .

**Comment by tig-jaspersmits** [comment]
Hi @martijnrmediact ,

Thanks for your message. Could you please use the template that is available for submitting these  in the future?
Could you maybe include some screenshots of what exactly is happening? I want to try and reproduce this on a test environment.

Kind regards,
Jasper
TIG

**Comment by martijnrmediact** [comment]
After the upgrade to PostNL version 1.9.4 the checkout is not loading correct anymore and throws a js error when enabling the additonal delivery settings.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to backend of magento -> store->configurations->sales->PostNL
2. Go to "delivery" and set "Activate delivery settings" to yes
3. Scroll down to 'letterpost' an set that to yes

**Expected result**
The checkout should work as expected in the frontend.

**Actual result**
The checkout shows a blank page with online the header of the shop and a javascript error is shown.

** Please complete the following information**
- Magento version: 2.3.5p2
- PHP version: 7.2
- TIG PostNL version: 1.9.4 

**The following js error is shown:**

`main.min.js:2 TypeError: Cannot read property 'quoteData' of undefined
    at quote.min.js:2
    at Object.execCb (require.min.js:112)
    at Module.check (require.min.js:56)
    at Module.enable (require.min.js:73)
    at Module.init (require.min.js:54)
    at callGetModule (require.min.js:74)
    at Object.completeLoad (require.min.js:103)
    at HTMLScriptElement.onScriptLoad (require.min.js:112)`

**Comment by tig-jaspersmits** [comment]
@martijnrmediact I see you closed this. Did you manage to find a solution?

Kind regards,
Jasper
TIG

**Comment by martijnrmediact** [comment]
@tig-jaspersmits yes, we saw we are on 1.9.4 and not yet on 1.9.4.1 the issue that causes this could be related to the changes done to msi in 1.9.4.1 we will check that out first and let you know. Btw, we could also reproduce this issue for multiple project which where also on 1.9.4.

**Comment by tig-jaspersmits** [comment]
@martijnrmediact alright, thanks for letting me know.
If you still run into problems with 1.9.4.1 you know where to find us.

Kind regards,
Jasper
TIG

**Comment by martijnrmediact** [comment]
@tig-jaspersmits we just deployed the 1.9.4.1 version to our staging environment and the issue still is there. The following error comes up in the log:

`[2020-08-21 07:58:39] report.CRITICAL: Can't create directory /app/35l634i5kkaqi_stg/generated/code/Magento/InventoryCatalogAdminUi/Model/.
Class \Magento\InventoryCatalogAdminUi\Model\GetSourceItemsDataBySkuFactory generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []
[2020-08-21 07:58:39] report.CRITICAL: Class Magento\InventoryCatalogAdminUi\Model\GetSourceItemsDataBySkuFactory\Proxy does not exist [] []`

We are running on Magento Cloud and we did a full setup and di:compile.

**Comment by tig-jaspersmits** [comment]
Hi @martijnrmediact ,

Thanks for letting us know. I've added this to our backlog so we can get it solved.
Keep an eye on the release notes here: https://docs.tig.nl/x/3YSC

Kind regards,
Jasper
TIG

**Comment by martijnrmediact** [comment]
@tig-jaspersmits thanx, any idea already when it has been solved? we are wondering if we need to plan it in our next sprint to fix it our selfs or wait until there is an offical version.

**Comment by tig-jaspersmits** [comment]
Hi @martijnrmediact ,

It is planned on this sprint: Sprint 145 (25 aug - 7 sep)
But the new versio  will probably take longer before it's released.

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
Hi @martijnrmediact ,

The fix is still in internal review, but I'd like to share it with you and other people who might come across this issue.
Opening the file TIG/PostNL/Service/Order/Compatibility/SourceItemsDataBySkuProxy.php and adding the following to the constructor should force the proxy being loaded by DI:
        GetSourceItemsDataBySku $proxy

**Comment by igorwulff** [comment]
Can you give us an estimate when this is going to be released? @tig-dennisvanderhammen

**Comment by tig-dennisvanderhammen** [comment]
Hi @igorwulff,

While I can't give a definitive date, we're doing our best to get a release out early next week!

**Comment by tig-dennisvanderhammen** [comment]
Hi @martijnrmediact and @igorwulff , a fix for the generated folder issues was added in PostNL v1.9.5. This version was just released.
Thank you again for pointing this out!
