### ISSUE TITLE
[BUG] On order is cancellation tig_postnl_order options get reused for remaining quote

### ISSUE THREAD

**Issue by EgorDm** [tig-nl/postnl-magento2#201]
**To Reproduce**
1. Configure TOG PostNL module to use Evening Shipping and Daytime Shipping (both with a different price)
2. Place products in your cart
3. Press checkout
4. Select evening delivery option
5. Proceed with checkout, select payment method and Click pay
6. On the page of payment provider press cancel, which redirects you to the cart
7. The cart products / quote is restored and tig_postnl_order table has a new row with quote id and cancelled order id
8. Press checkout
9. Select daytime delivery option

Tested payment providers: Multisafepay, Adyen

**Expected result**
The delivery price changes to daytime delivery price

**Actual result**
The delivery price does not change

**Workaround**
None

**Details**
It seems that the module tries to create a new entry in tig_postnl_order for the newly selected option.
Meanwhile the fee is calculated based on on the first retrieved entry:
Fee calculation code: https://github.com/tig-nl/postnl-magento2/blob/master/Plugin/Quote/Address/Total/Shipping.php#L152
Tig Current order retrieval: https://github.com/tig-nl/postnl-magento2/blob/master/Service/Order/CurrentPostNLOrder.php#L85
I belive adding a desc sort order on entity id to the criteria would solve the problem.

** Please complete the following information**
- Magento version: 2.3.3-p1
- PHP version: 7.2
- TIG PostNL version: 1.9.2.1

Thanks in advance

**Comment by tig-jaspersmits** [comment]
Hi @EgorDm ,

Thanks for contacting us. Could you try updating the PostNL extension and see if it still happens?

Kind regards,
Jsasper
TIG

**Comment by EgorDm** [comment]
Hi @tig-jaspersmits,

I am still having this issue on 1.9.4.1 version of the module.
The proposed solution in the issue description seems to fix is. I have created a pr for it at: https://github.com/tig-nl/postnl-magento2/pull/203

Thanks in advance

**Comment by tig-jaspersmits** [comment]
Hi @EgorDm ,

Thanks for sharing the PR with us.
I'll inform our developers about it.

Kind regards,
Jasper

**Comment by tig-jaspersmits** [comment]
I'll let someone from our team follow up on your PR.
If there is any follow up needed, someone from our team will contact you about that.

Kind regards,
Jasper
TIG
