### ISSUE TITLE
License model 

### ISSUE THREAD

**Issue by pimjansen** [tig-nl/postnl-magento2#204]
I am reviewing this plugin and i notice that it is licensed under a `CC-BY-NC-ND-3.0` license. This means that the software is free to use and distribute with the following terms:

- Mandatory to mention its vendor name
- Not allow to modify its content
- Only for non-commercial use

But how can you use a commercial service for non-commercial use? On your website nothing is mentioned about licensing and so on

Cheers

**Comment by tig-jeffreybranderhorst** [comment]
Hey @pimjansen

Heb dit overlegd met PostNL en daar kwam het volgende uit, hopelijk heb ik je hiermee voldoende geïnformeerd:
Het gaat erom dat de software van de plug-in niet gebruikt mag worden om bijvoorbeeld verkocht te worden. Dus dat wij als PostNL zijnde de plug-in gratis aanbieden maar dat een ander bedrijf geld vraagt aan klanten om gebruik te maken van deze plug-in.

**Comment by pimjansen** [comment]
@tig-jeffreybranderhorst dank voor de verheldering. 

Dit staat niet echter duidelijk vermeld in de licentie want daar gaat het over commerciele doeleinden en dat is uiteraard een webshop altijd.
https://creativecommons.org/licenses/by-nc-nd/3.0/nl/
