### ISSUE TITLE
[QUESTION] Please summarize your question here

### ISSUE THREAD

**Issue by dheesbeen** [tig-nl/postnl-magento2#205]
**Question**
Is it possible to disable javascript console logging output? For example this message

Invalid locations response, more information can be found in the PostNL log files.

**Comment by tig-jaspersmits** [comment]
Hi @dheesbeen ,

Thanks for contacting us. There is currently no option to disable this.
Why do you want to disable this if I may ask?

Kind regards,
Jasper
TIG

**Comment by dheesbeen** [comment]
Hi @tig-jaspersmits 

Request of a client.  But if there is no option we will leave it this way.

Derrick
