### ISSUE TITLE
[BUG] Support Magento 2.4

### ISSUE THREAD

**Issue by PascalBrouwers** [tig-nl/postnl-magento2#209]
**To Reproduce**
Upgrade to Magento 2.4 using composer

**Expected result**
No problem

**Actual result**
- tig/postnl-magento2 1.9.4.1 requires magento/framework >=100.1.0,<=100.1.18|>=101.0.0,<=101.0.11|~102.0 -> satisfiable by magento/framework[102.0.5-p2, 100.1.4, 100.1.8, 100.1.14, 100.1.15, 100.1.17, 101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc30, 101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.6, 101.0.7, 101.0.9, 101.0.11, 102.0.0, 102.0.1, 102.0.3, 102.0.4, 102.0.4-p1, 102.0.4-p2, 102.0.5, 102.0.6, 100.1.0-rc1, 100.1.0-rc2, 100.1.6, 100.1.12, 100.1.18, 101.0.0-rc23, 101.0.4, 101.0.5, 101.0.8, 101.0.10, 102.0.2-p2, 102.0.3-p1, 100.1.3, 100.1.10, 100.1.5, 100.1.2, 100.1.16, 102.0.2, 100.1.13, 100.1.0, 100.1.7, 100.1.9, 100.1.11, 100.1.1, 100.1.0-rc3].
    - tig/postnl-magento2 1.9.4.1 requires magento/framework >=100.1.0,<=100.1.18|>=101.0.0,<=101.0.11|~102.0 -> satisfiable by magento/framework[102.0.5-p2, 100.1.4, 100.1.8, 100.1.14, 100.1.15, 100.1.17, 101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc30, 101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.6, 101.0.7, 101.0.9, 101.0.11, 102.0.0, 102.0.1, 102.0.3, 102.0.4, 102.0.4-p1, 102.0.4-p2, 102.0.5, 102.0.6, 100.1.0-rc1, 100.1.0-rc2, 100.1.6, 100.1.12, 100.1.18, 101.0.0-rc23, 101.0.4, 101.0.5, 101.0.8, 101.0.10, 102.0.2-p2, 102.0.3-p1, 100.1.3, 100.1.10, 100.1.5, 100.1.2, 100.1.16, 102.0.2, 100.1.13, 100.1.0, 100.1.7, 100.1.9, 100.1.11, 100.1.1, 100.1.0-rc3].
    - tig/postnl-magento2 1.9.4.1 requires magento/framework >=100.1.0,<=100.1.18|>=101.0.0,<=101.0.11|~102.0 -> satisfiable by magento/framework[102.0.5-p2, 100.1.4, 100.1.8, 100.1.14, 100.1.15, 100.1.17, 101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc30, 101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.6, 101.0.7, 101.0.9, 101.0.11, 102.0.0, 102.0.1, 102.0.3, 102.0.4, 102.0.4-p1, 102.0.4-p2, 102.0.5, 102.0.6, 100.1.0-rc1, 100.1.0-rc2, 100.1.6, 100.1.12, 100.1.18, 101.0.0-rc23, 101.0.4, 101.0.5, 101.0.8, 101.0.10, 102.0.2-p2, 102.0.3-p1, 100.1.3, 100.1.10, 100.1.5, 100.1.2, 100.1.16, 102.0.2, 100.1.13, 100.1.0, 100.1.7, 100.1.9, 100.1.11, 100.1.1, 100.1.0-rc3].

**Comment by tig-dennisvanderhammen** [comment]
Hi @PascalBrouwers,

It could be that your PostNL version is locked to 1.9.4.1. We released version 1.9.5 earlier this week which contains support for Magento 2.4.

**Comment by PascalBrouwers** [comment]
Ok, didn't see that.
