### ISSUE TITLE
Magento 2.2 Compatibility

### ISSUE THREAD

**Issue by danslo** [tig-nl/postnl-magento2#21]
This module has a hard requirement on ``"magento/framework": "100.1.*"``. Magento 2.2 was released today and it would be nice to have compatibility for this new Magento version.

**Comment by tig-michielgerritsen** [comment]
Hi Daniel,

Thanks for pointing this out. We have it already on our backlog, i just made the issue public:
https://jira.tig.nl/projects/POSTNLM2/issues/POSTNLM2-325

The compatibility with Magento 2.2 especially needs a more thorough test, as there are some relevant changes.

**Comment by jghaanstra** [comment]
I would have assumed TIG would have done the thorough testing on a Magento 2.2 release candidate so the extension would have been Magento 2.2 ready the moment it came out.

Is there any estimate on when this will become available and is there already an idea on what will fail if I remove the dependency and install it on Magento 2.2 anyway?

**Comment by tig-michielgerritsen** [comment]
Hello @danslo and @jghaanstra,

Yesterday we released v1.1.5 which includes support for Magento 2.2:
https://github.com/tig-nl/postnl-magento2/releases/tag/v1.1.5-alpha

**Comment by jghaanstra** [comment]
@tig-michielgerritsen 
When doing composer require tig/postnl-magento2 on Magento 2.2 I get the following error:

`Could not find package tig/postnl-magento2 at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
`

**Comment by tig-michielgerritsen** [comment]
Just tested this, i am able to install the latest version on a clean Magento 2.2 installation. Please make sure that:

- You are using php 7.0 or 7.1.
- You have lowered the minimum-stability requirement in your composer.json. You can do this by running this command:
`composer config minimum-stability alpha`
