### ISSUE TITLE
[BUG] M.2.4.1 upgrade & Class TIG\PostNL\Service\Framework\ValidationState does not exist

### ISSUE THREAD

**Issue by seansan** [tig-nl/postnl-magento2#210]
**To Reproduce**
1. M 241 via composer on php 7.4
2. Update to https://github.com/tig-nl/postnl-magento2/releases/tag/v1.9.5

**Expected result**
Works

**Actual result**
`php bin/magento` no longer works

with error

```
php bin/magento
Magento CLI 2.4.0

In ServiceManager.php line 1129:

  An abstract factory could not create an instance of magentosetupconsolecommanddbstatuscommand(alias: Magento\Setup\Console\Command\DbStatusCommand).


In ServiceManager.php line 940:

  An exception was raised while creating "Magento\Setup\Console\Command\DbStatusCommand"; no instance returned


In ClassReader.php line 26:

  Class TIG\PostNL\Service\Framework\ValidationState does not exist
```

**Workaround**
Probably exists, but we like to stick to core

**Comment by tig-jeffreybranderhorst** [comment]
Hi Sean,

Could you try and clean your generated folder, redis cache and cache? We have deleted some files that where not needed anymore in the extension. 

Have a great day,
Jeffrey

**Comment by seansan** [comment]
We always run (via script) i$ is our web dir

Am I missing something to flush here?

```
    # Note, not sure if we can also clear -rf $i/var/composer_home/*
    rm -rf $i/var/cache/* $i/var/session/* $i/var/log/* $i/var/tmp/*
$i/var/generation/* $i/var/page_cache/* $i/var/view_preprocessed/*
$i/pub/static/* $i/generated/*
      echo "* All cache and generation folders cleared"

    redis-cli -p 6380 -n 4 flushdb > /dev/null      # Flush cache db
    redis-cli -p 6380 -n 3 flushdb > /dev/null      # Flush session db
    echo "* Flushed redis DB:3:session + DB:4:Cache"
```

**Comment by tig-jeffreybranderhorst** [comment]
Hey @seansan,

We tested it to be sure, we upgradet to 1.9.5 and this server does not have any external caching and our bin/magento still works after the upgrade.  With the update the file change of di.xml came along where we deleted ValidationState preference. We are thinking that some of your xaching mechanics is caching the di.xml and that the new edits are not live yet on your site.  
You could check the di.xml to be sure. 

![image](https://user-images.githubusercontent.com/23314965/96445517-53d24d00-1210-11eb-9003-13a317ad1113.png)

Have a great day,
Jeffrey

**Comment by seansan** [comment]
maybe its because we cant clear the cache anymore? that statement is broken
...

**Comment by tig-jaspersmits** [comment]
Hi @seansan ,

You can't clear cache any more? Because the php bin/magento command doesn't work for you? Maybe you could try magerun2. Or maybe I don't understand your response. If that's the case, please clarify.

Kind regards,
Jasper
TIG

**Comment by seansan** [comment]
I cannot flush the cache any way due to the PostNL error

[m2_dev]$ php bin/magento cache:flush

There are no commands defined in the "cache" namespace.

[m2_dev]$ mr2 cache:flush

In ClassReader.php line 26:

  Class TIG\PostNL\Service\Framework\ValidationState does not exist

**Comment by tig-jeffreybranderhorst** [comment]
Hi @seansan,

Did you check the di.xml for validation state? Because there should be no refrerence anymore same for. 
![image](https://user-images.githubusercontent.com/23314965/96452698-acf2ae80-1219-11eb-8127-853c140f6772.png)

Could you check this, I think this is active in your files.

**Comment by seansan** [comment]
![image](https://user-images.githubusercontent.com/652395/96453432-c47e6700-121a-11eb-9798-3971577ab2a5.png)

**Comment by tig-jeffreybranderhorst** [comment]
Hi @seansan,

What you could try is to put the validationstate inside your vendor map and then clean cache and after that delete it again: 
https://github.com/tig-nl/tig-extension-tig-postnl-magento2/blob/v1.9.4.1/Service/Framework/ValidationState.php

If still still does not work afterwards i would like to ask you to contact PostNL so we can pick this up as a support issue.

Have a nice day,
Jeffrey

**Comment by tig-jaspersmits** [comment]
I will close this issue.
If there is anything else, feel free to reopen the issue or create a new one.

Kind regards,
Jasper
TIG
