### ISSUE TITLE
[BUG]  Call to a member function getShipAt() on null / Multiple shipping providers not taken into account.

### ISSUE THREAD

**Issue by thioz** [tig-nl/postnl-magento2#211]
<!-- ################################################################
        IGNORING THE TEMPLATE BELOW WILL RESULT IN ISSUE CLOSURE AS INCOMPLETE
        ################################################################ 

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.

- If you want support with installing the PostNL extension, please contact digitaleklantsupport@postnl.nl for free support, or contact us directly at support@tig.nl for paid support plans.

- Please **verify** and **assure** that you are running the latest version of the TIG PostNL Magento extension. See https://tig.nl/postnl-magento-extensies/ for the latest version.

**To Reproduce**
1. Place multiple order with multipl shipping methods 
2. Run the order:sync cron
3. Look at error logs

**Expected result**
Order grid being synchronized without errors

**Actual result**
Cron processed crashes

**Workaround**
Monkey patched the class Plugin/AsyncPlugin.php 

** Please complete the following information**
- Magento version: [e.g. Magento Commerce 2.3.5-p2]
- PHP version: [e.g. 7.3.0]
- TIG PostNL version: 1.9.4.1

In general the module does not take into account that there can be multiple shipping providers, when doing a mass package slip print it will crash on orders that are not shipped with PostNL and will throw an exception with a non-descript error message. 
When the cron syncs the OrderGrid the plugin blindly loads orders without even checking if they could be found or are to be send with another shipping method.

**Comment by tig-jaspersmits** [comment]
Hi @thioz ,

Please provide additional information by using the template we have for submitting a bug like this.

Kind regards,
Jasper
TIG
