### ISSUE TITLE
[BUG] Call to a member function getShipAt() on null / Multiple shipping providers not taken into account.

### ISSUE THREAD

**Issue by thioz** [tig-nl/postnl-magento2#212]
**To Reproduce**
1. Create multiple orders with different shipping methods
2. Run the cron that synchronized the order grids

**Expected result**
Synchronizing the order grid without any exceptions

**Actual result**
the cron terminated with an exception

**Workaround**
None

** Please complete the following information**
- Magento version: Magento Commerce 2.3.5-p2
- PHP version: php 7.3
- TIG PostNL version: 1.9.4.1

A version of this error also happens when printing labels and some orders that are shipped with another shipping service are selected in a bulk operation. The module should have better checks if an order actually is applicable and else ignore the orders instead of terminating the batch.

**Comment by tig-jaspersmits** [comment]
Hi @thioz ,

Thanks for submitting this. I'll discuss this with the development team.
When I have more information about this, I'll let you know.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
@thioz p.s. about the multiple shipping methods, can I just all the shipping options available in a default Magento environment? Or are you using 3rd party extensions for this?

**Comment by tig-jaspersmits** [comment]
Hi @thioz , due to no receiving a reply I'll close this issue.
If you could still follow up on this, feel free to reopen and reply.

Kind regards,
Jasper
TIG

**Comment by markvds** [comment]
@tig-jaspersmits This is still an issue. A client of mine uses PostNL for packets and the 'tablerate' method for _brievenbuspost_. It produces the mentioned error while indexing orders and/or shipments.

The problems are caused on these two places:
- https://github.com/tig-nl/postnl-magento2/blob/master/Plugin/Order/AsyncPlugin.php#L110
- https://github.com/tig-nl/postnl-magento2/blob/master/Plugin/Shipment/AsyncPlugin.php#L110

If the order that just got indexed is not a PostNL order, the `$postNLOrder` variable is `null`. There should be a check inserted on line 111 in both files (with `$postNLShipment` as variable name in the second file of course):
```php
if ($postNLOrder === null) {
    continue;
}
```

Or at least, that's what seems to solve the problem for us. As @thioz mentions, there are probably more places that are affected by the assumption that all orders will be shipped with the PostNL shipping method.

Please reopen and fix this issue.

**Comment by markvds** [comment]
Sorry, I now see that my proposed solution is exactly in PR #238

**Comment by tig-jeffreybranderhorst** [comment]
Hi @markvds,

We have placed the pull request in our newest version of the extension. This version is in the testing phase after testing we will release the extension with this bug fix! 

Have a great day,
Jeffrey
