### ISSUE TITLE
Is there a variable for the Track & Trace code?

### ISSUE THREAD

**Issue by Kees-kees** [tig-nl/postnl-magento2#215]
Is there a way (e.g. a variable) to let the tracking code display in a custom email template, instead of a button to the Track & Trace URL, when overriding the default Track & Trace template from the module?

**Comment by tig-jaspersmits** [comment]
Hi @Kees-kees ,

Thanks for your message. All available options for the T&T mails are listed here: https://docs.tig.nl/x/q4SC
I think you should be able to use this one: postnlShipment.getMainBarcode()

Kind regards,
Jasper
TIG

**Comment by julianmurillosd** [comment]
Hi @tig-jaspersmits 

Using the variables from https://docs.tig.nl/x/q4SC works as expected when sending the Track&Trace email, after clicking on the option 'Generate Label' for the respective Shipment. 

However, when I try to send the email through Sales - Shipments - Select Shipment - Send Shipment Email, I get empty fields to see. Using the Magento default variables would work as I'd expect, but then I get the same situation from 5 days ago (the Magento default variables are then not recognized when creating the label). 

Do you know a proper solution for this?

**Comment by Kees-kees** [comment]
Hi @tig-jaspersmits

Using the variables from https://docs.tig.nl/x/q4SC works as expected when sending the Track&Trace email, after clicking on the option 'Generate Label' for the respective Shipment.

However, when I try to send the email through Sales - Shipments - Select Shipment - Send Shipment Email, I get empty fields to see. Using the Magento default variables would work as I'd expect, but then I get the same situation from 5 days ago (the Magento default variables are then not recognized when creating the label).

Do you know a proper solution for this?

**Comment by tig-jaspersmits** [comment]
Hi @Kees-kees ,

Just tried to reproduce this, but it does show a T&T link for me in that mail. Could you maybe share a screenshot with me of the e-mail configuration and how the mail looks? Thanks in advance.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @Kees-kees ,

I assume the problem has been solved based on my answer.
Therefor I will close this issue. If there is anything else feel free to submit a new issue on Github.

Kind regards,
Jasper
TIG
