### ISSUE TITLE
Address check doesn't seem to be working

### ISSUE THREAD

**Issue by WesleyJustin** [tig-nl/postnl-magento2#216]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x] This issue does not contain any security sensitive information

---

### If the purpose of your issue is a *feature request*
- As a *..certain type of user..* I’d like to *..describe what you want..* in order to *..write goal(s)..*
- Suggestions and background: 
  If you have ideas for the solution write them down here. Include images, a picture is more worth than 1,000 words. If none, remove this line.

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Step 1, Step 2, ...
Before I describe Step 1, it is good to know we use the OneStepCheckout from onestepcheckout.com, Magento 2 version 2.4.0 and the latest version of TIG Post NL which is 1.9.5. We have the address check enables which does not seem to be working correctly.
Step1) We go to our checkout page, and fill in our postal code and house number. 
Step2) Once we do that, we get 2 errors. One in the console log, and one next to the postal code input field.
The console error is (in Dutch): "Postcode response is niet valide handleResponse @ fields.js:274"
The front-end error (next to the postal code) is (also in Dutch): "Er is een onverwachte fout opgetreden. Vul s.v.p. handmatig uw adresgegevens in." 
- Expected result
We would expect that the street name and the city would be automatically filled based on the postal code and the housenumber.
- Actual result (Please provide screenshots if applicable)
The console error is (in Dutch): "Postcode response is niet valide handleResponse @ fields.js:274"
The front-end error (next to the postal code) is (also in Dutch): "Er is een onverwachte fout opgetreden. Vul s.v.p. handmatig uw adresgegevens in." 
![address_check](https://user-images.githubusercontent.com/15123512/97582392-fa2f0700-19f5-11eb-8b8c-021a765dface.png)

- Workaround (If available, otherwise just write "None")
None

### If the purpose of your issue is about anything else, please describe your issue here
- Explain your issue here

### TIG support
- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.
- If you want support with installing the PostNL extension, please contact digitaleklantsupport@postnl.nl for free support, or contact us directly at support@tig.nl for paid support plans.

**Comment by tig-jaspersmits** [comment]
Hi @WesleyJustin ,

Thanks for submitting this and using the template. I've tested this and wasn't able to reproduce the problem. It seems like it's specific for your environment. I have a few tips/questions.

1. Are you using a PostNL test account? The postalcode check doesn't work for that. You need a PostNL live account with the postalcode service enabled on PostNL's side.

2. In the OSC configuration you need to disable the postalcode field for shipping and billing address. Otherwise you will end up with multiple postalcode fields.

Let me know if this was of any help.

Kind regards,
Jasper
TIG

**Comment by WesleyJustin** [comment]
Hi Jasper Smits,

Thanks for answering. Everything seems to be working perfectly after the recommondations you suggested.

Kinds regards,

Wesley.

**Comment by tig-jaspersmits** [comment]
Hi @WesleyJustin ,

Great to hear and thanks for letting me know!

Kind regards,
Jasper
TIG
