### ISSUE TITLE
[QUESTION] Adress check with SwissUp Firegento

### ISSUE THREAD

**Issue by hans2103** [tig-nl/postnl-magento2#220]
**Question**
https://test.onderdelenexpert.nl add a product to the cart and head over to the checkout.
I've enabled PostNL Address Check and the screenshot is what I see.

<img width="334" alt="Schermafbeelding 2020-11-28 om 17 24 38" src="https://user-images.githubusercontent.com/639822/100520619-f500db80-319e-11eb-8a48-e7bda2469d72.png">

**First question**
Without activation of Address Check, the Address lines are displayed below Company (Bedrijf) field.
With activation of Address Check, the Address lines are replaced with the three fields "Huisnummer", "Toevoeging" and "Postcode". 
I was expecting to see the replacement below Company field, not above. 
How can this be achieved? 

**Second question**
As you can see in the screenshot the order of the fields is "Huisnummer", "Toevoeging" and "Postcode".
How can the order be changed to "Postcode", "Huisnummer" and "Toevoeging"?

**Comment by tig-jaspersmits** [comment]
Hi @hans2103 ,

Thanks for you question. What checkout are you using? What is Swissup Firegento exactly? I couldn't really find anything about it. 

Kind regards,
Jasper
TIG

**Comment by hans2103** [comment]
https://swissuplabs.com/one-step-checkout-extension-for-magento-2.html
http://docs.swissuplabs.com/m2/extensions/firecheckout/

**Comment by tig-jaspersmits** [comment]
Hi @hans2103 ,

I'm sorry but that checkout isn't supported. Therefor I won't be able to provide any support on this.

Kind regards,
Jasper
TIG

**Comment by hans2103** [comment]
What should be done to get this checkout supported?
Should SwissupLabs adjust something in the checkout?

**Comment by tig-jaspersmits** [comment]
@hans2103 ,

FireCheckout did implement compatibility in the past. You could try and contact them about it.

Kind regards,
Jasper
TIG

**Comment by hans2103** [comment]
Contacted SwissUpLabs. They are investigating the issue

**Comment by tig-jaspersmits** [comment]
Thanks for sharing @hans2103 .

Kind regards,
Jasper
TIG

**Comment by hans2103** [comment]
Changed the order of the fields using the documentation on their site. 
http://docs.swissuplabs.com/m2/extensions/firecheckout/customization/move-js/

Classic case of [PEBKAC](http://ars.userfriendly.org/cartoons/?id=19980506). :-)
