### ISSUE TITLE
[BUG] Unable to create shipment barcodes via API

### ISSUE THREAD

**Issue by boldhedgehog** [tig-nl/postnl-magento2#222]
**To Reproduce**
1. Create TiG shipment barcode via API POST request 

Request URI: https://www.webshop.url/rest/all/V1/postnl/shipments/barcode
Body:
```json
{
  "shipmentBarcode": {
    "parent_id": 12345,
    "type": "shipment",
    "number": 1,
    "value": "XXXXX"
  }
}
```

**Expected result**
Shipment barcode is created

**Actual result**
Fatal error `undefined method setParentId in vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php `

**Workaround**
This is caused by  'POSTNLM2-1025 - Updated coding standards to Magento's latest standards'(v 1.9.5 ).
It's the main reason of the issue, because method was refactored and changed in to 'changeParentId' in interface vendor/tig/postnl-magento2/Api/Data/ShipmentBarcodeInterface.php

We have fixed this temporary with a patch:
```patch
diff --git vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php
index 1a7032f660..ea3353d9ff 100644
--- vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php
+++ vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php
@@ -239,7 +239,7 @@ class BarcodeHandler
     {
         /** @var \TIG\PostNL\Model\ShipmentBarcode $barcodeModel */
         $barcodeModel = $this->shipmentBarcodeFactory->create();
-        $barcodeModel->setParentId($shipmentId);
+        $barcodeModel->changeParentId($shipmentId);
         $barcodeModel->setType(ShipmentBarcode::BARCODE_TYPE_SHIPMENT);

         if ($isReturnBarcode) {
```

**Please complete the following information**
- Magento version: Magento Commerce 2.4.1
- PHP version: 7.4.8
- TIG PostNL version: 1.9.5

EDIT: added patch with a workaround/fix, fixed MD syntax.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @boldhedgehog ,

Thank you for submitting this, we will test your fix and investigate it thank you!

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment]
Hi @boldhedgehog ,

Thank you for the provided solution, it was added to the 1.9.6 release of the plugin.

Have a nice day!

Greetings

Vincent
