### ISSUE TITLE
[QUESTION] How to sort the checkout fields after activating address check?

### ISSUE THREAD

**Issue by hans2103** [tig-nl/postnl-magento2#225]
## Order of checkout fields when _Use Postcode Check_ = No
<img width="545" alt="Schermafbeelding 2020-12-21 om 13 43 35" src="https://user-images.githubusercontent.com/639822/102778323-a821b680-4392-11eb-902d-acb3826fb3d2.png">

## Order of checkout fields when _Use Postcode Check_ = Yes
<img width="541" alt="Schermafbeelding 2020-12-21 om 13 42 59" src="https://user-images.githubusercontent.com/639822/102778321-a6f08980-4392-11eb-9c33-1f66b560fa17.png">

## Question
- _Checkout usage_ = Two Step Checkout Luma.

- Why does _Bedrijf_ appear after _Huisnummer, Huisnummer Toevoeging, Postcode_ ?
  I was expecting to see the field before, not after these three items
- Why is _Postcode_ rendered last and not at first item?
  I was expecting to see the postcode first followed by house number followed by housenumber suffix.

What can I do to get the needed display?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103 ,

In de following file should be able to edit the postcode sort order: vendor/tig/postnl/Plugin/Postcodecheck/LayoutProcessor.php

Rest of the sort orders are from magento self and you should also be able to edit those so you can have the checkout how you want.

Have a great day,
Jeffrey

**Comment by hans2103** [comment]
might be js. Closing issue
