### ISSUE TITLE
[BUG] Mageplaza OSC 4.0.x compatibility in TIG module 1.9.6

### ISSUE THREAD

**Issue by jeroenbalk-adwise** [tig-nl/postnl-magento2#227]
**To Reproduce**
1. Have Mageplaza OSC installed with newest Magento2 version
2. Login with your customer account
3. Make sure customer account has multiple addresses
3. Add product to cart
4. Navigate to OSC
5. Notice the address blocks when you click them

**Expected result**
An XHR call is made and an event is triggered when selecting an other address

**Actual result**
Nothing happens, the event is not fired

**Workaround**
There is none, current solution is to overwrite this file:
`/vendor/tig/postnl-magento2/view/frontend/web/template/Compatibility/mageplaza_osc/shipping-address/address-renderer/default.html`
Change:
`<div class="shipping-address-item" data-bind="css: isSelected() ? 'selected-item' : 'not-selected-item'">`
to
`<div class="shipping-address-item" data-bind="css: isSelected() ? 'selected-item' : 'not-selected-item', click: selectAddress">`

So probably you have to update your compatibility with newer versions of osc.

** Please complete the following information**
- Magento version: 2.4.1
- PHP version: 7.4.1
- TIG PostNL version: 1.9.6

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jeroenbalk-adwise,

Thank you for contacting us and helping us make the extension even better!
I will talk about this fix with the team! Thank you again you will hear from us.

Have a nice day,
Jeffrey

**Comment by tig-vincentthart** [comment]
@jeroenbalk-adwise 

kan jij aangeven of dit probleem voor jou nog speelt in de laatste versie van de plugin?
