### ISSUE TITLE
[QUESTION] change flat rate price on store view

### ISSUE THREAD

**Issue by hans2103** [tig-nl/postnl-magento2#228]
**Question**
Ask your question in an arbitrary form without insulting someone. Please make sure it's worded well enough to be understood and remove this line.

Using PostNL I want to be able to change the price for flat rate on scope = Store view. 
How can this be achieved?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103 ,

You can change the shipping cost on default and store scope., on store view scope there is no option to change shipping cost in Magento. 

Have a nice day,
Jeffrey

**Comment by hans2103** [comment]
The Store Scope cannot be selected from the dropdown to change scopes. 
Therefor the price field is only visible on default. 
How to change the price on store scope?

**Comment by hans2103** [comment]
@tig-jeffreybranderhorst do you have an answer on my follow-up?
Is it possible to add this on the list of feature requests?

- allow shopping cost to be configured on scope store view

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103 

I thought I answered on this, my mistake, but I will put this on the backlog, and we will talk about this with PostNL!
Thank you for submitting this and helping us improve the extension. 

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment]
Hi @hans2103 

In most Magento webshops store views are setup to support different languages of the store. Could you describe a use case in which the setting of the shipping costs on store view level would be need, which cannot be accomplished using the tables rates or matrix rates?

Greetings

Vincent

**Comment by hans2103** [comment]
@tig-vincentthart in this case the store view was used for one particular client creating orders using the API. 
We've solved the issue creating a new store for him. 
It would have been easier if it was possible to adjust the shipping costs per store view

**Comment by tig-vincentthart** [comment]
@hans2103 

thank you for the clarification and happy to hear you found a work around.. 
For now it is not something we will add to the plugin, so I will close the issue.

Greetings

Vincent
