### ISSUE TITLE
[BUG] Wrong Address details used

### ISSUE THREAD

**Issue by JoostWan** [tig-nl/postnl-magento2#230]
- Magento version: 2.3.6
- PHP version: 7.3
- TIG PostNL version: 1.9.6
- Number of Lines in a Street Address option: 3

**Case:**

When a customer opens the checkout he gets the default country, in this case thats NL. But the customer is from Belgium and uses auto fill. It will fill in the details with country id NL like this screenshot;

![Screenshot 2021-02-05 at 14 27 33](https://user-images.githubusercontent.com/5435412/107039735-8f445780-67be-11eb-8586-507eae7ee49c.png)

Now you need to change the country from NL to BE. Now the address fields are changed because there is no postcode check for Belgium. Now we need to fill in again the house number on the second line. See this screenshot. 

![Screenshot 2021-02-05 at 14 28 42](https://user-images.githubusercontent.com/5435412/107039753-953a3880-67be-11eb-97bc-c8a38bbfb6a6.png)

Now when we go to the next step both the house numbers are visible. 

![Screenshot 2021-02-05 at 14 29 16](https://user-images.githubusercontent.com/5435412/107039762-98cdbf80-67be-11eb-95a2-75e32f641988.png)

Now open the order in the backend and the order is placed with housenumber 1 and not 99. 

![Screenshot 2021-02-05 at 14 31 23](https://user-images.githubusercontent.com/5435412/107039933-d3cff300-67be-11eb-9c44-35d9fd89d2a4.png)

**Comment by tig-jeffreybranderhorst** [comment]
Hey @JoostWan ,

Thank you for submitting this issue, I'm putting it on the backlog to fix and investigate it further!
Thank you again for submitting this and helping us make the extension even better!

Have a nice day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
hey @JoostWan ,

We made a fix that is in testing fase now and will be added in the next version!

Have a great day,
Jeffrey

**Comment by TechNick66** [comment]
@tig-jeffreybranderhorst 

Will this fix also cover the situation where the 'Pickup' (Afhaalpunt) for Belgium is enabled and a check for available locations is done?

Regards, Nick.

**Comment by tig-jeffreybranderhorst** [comment]
Hey @TechNick66 ,

We made it so that the housenumber will be empty, so you need to fill in housenumber again and then the options will be loaded again for Belgium. If it does not fix it for you we would like to ask you to contact us at support@tig.nl so we can investigate why it is not working for you.

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment]
@JoostWan & @TechNick66 

The fix was added to the 1.9.8 release. If you still run into any issues with this, feel free to contact teh support team.

Greetings

Vincent
