### ISSUE TITLE
[BUG] Invalid price shown

### ISSUE THREAD

**Issue by pimjansen** [tig-nl/postnl-magento2#234]
**To Reproduce**
1. Place an order
2. Go to checkout page with the postNL widget
3. Open prices

**Expected result**
The prices should be equal

**Actual result**
The price 7.20 and 5.95 are shown. The price 5.95 is the valid one from the Matrix file 
Seems like the 7.20 price is the original price with an extra 21% VAT

**Workaround**
None

**Screenshots**
![postnl](https://user-images.githubusercontent.com/1457219/109313493-9522db00-7848-11eb-8624-5ee91d7adf38.png)

- Magento version: 2.4.0
- PHP version: 7.4.11
- TIG PostNL version: 1.9.6

**Comment by tig-jeffreybranderhorst** [comment]
Hi @pimjansen ,

Could you contact us at support@tig.nl with you matrix rates, so we can reproduce this on our test sites?

Have a great day,
Jeffrey

**Comment by pimjansen** [comment]
Email sent. I also add it here in case someone sees a problem with it

**Comment by tig-jeffreybranderhorst** [comment]
Hey @pimjansen ,

We received your mail and are supporting you further via our support system! thank you!

Have a great day,
Jeffrey

**Comment by pimjansen** [comment]
Confirmed that this is a bug. Bummer that there is no workaround though

**Comment by tig-vincentthart** [comment]
@pimjansen 

a fix for this issues has been added to the latest release of the plugin (v1.9.9). For now I will close the issue.

If you have any follow up questions, you can contact the PostNL support.

Greetings

Vincent
