### ISSUE TITLE
[BUG] sender address on label is always The Netherlands

### ISSUE THREAD

**Issue by akosglue** [tig-nl/postnl-magento2#236]
**To Reproduce**
1. Go to 'Sales / Order'
2. Click on 'Create Shipment'
3. Click on 'PostNL - Print Label' on that shipment

**Expected result**
I expect to have the sender country in the sender address. However, it can't be changed via the magento admin panel.

**Actual result**
THE NETHERLANDS remains in the sender address.

**Workaround**
I just made a patch to hotfix my issue.
`diff --git a/vendor/tig/postnl-magento2/Webservices/Api/Customer.php b/vendor/tig/postnl-magento2/Webservices/Api/Customer.php
index c7007a52..946045dd 100644
--- a/vendor/tig/postnl-magento2/Webservices/Api/Customer.php
+++ b/vendor/tig/postnl-magento2/Webservices/Api/Customer.php
@@ -112,7 +112,7 @@ class Customer
             'HouseNrExt'  => $this->addressConfiguration->getHousenumberAddition($this->storeId),
             'Zipcode'     => strtoupper(str_replace(' ', '', $this->addressConfiguration->getPostcode($this->storeId))),
             'City'        => $this->addressConfiguration->getCity($this->storeId),
-            'Countrycode' => 'NL',
+            'Countrycode' => 'BE',//originally it was NL
             'Department'  => $this->addressConfiguration->getDepartment($this->storeId),
         ];
 
`

**Screenshots**
Not applicable, the address is shown on the label.

** Please complete the following information**
- Magento version: 2.3.6
- PHP version: 7.2.34
- TIG PostNL version: 1.9.7

**Comment by tig-jeffreybranderhorst** [comment]
Hi @akosglue ,

At this moment the PostNL extension only uses product codes for the Netherlands, that is also the reason why you cannot change your sender country. This is something that is on our backlog and in the future this will be added to the extension, currently we don't have an ETA for this yet.

Have a nice day,
Jeffrey

**Comment by tig-vincentthart** [comment]
Hi @akosglue ,

Within the latest versions of the plugin this has been resolved.

Have a nice day!
Vincent
