### ISSUE TITLE
when there is a space in the zipcode there are no delivery options 

### ISSUE THREAD

**Issue by JosRomateFashcom** [tig-nl/postnl-magento2#245]
When there is an space in the zipcode, there are no shipping options. 
The postnl postcode checker works fine

1. go to the checkout
2. set zipcode with a space(example 7441 GJ) and house number
3. There are no shipping options shown. When I remove the space there a shipping options.

**Expected result**
I expect shipping options with and without a space in the zipcode

**Actual result**
No shipping options when there is an space in the zipcode

**Workaround**
None

**Screenshots**
https://drive.google.com/file/d/1UrraLL5ZChgV3LJh9MyWupuKIVwEnygV/view?usp=sharing

** Please complete the following information**
- Magento version: 2.3.6
- PHP version: 7.3.27
- TIG PostNL version: 1.9.7

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JosRomateFashcom 

Thank you for submitting this, we fixed this in our development version. With the next release this will be added. 

Have a great day,
Jeffrey

**Comment by JosRomateFashcom** [comment]
@tig-jeffreybranderhorst when do you expect the next release to be released?

**Comment by tig-jeffreybranderhorst** [comment]
Hey @JosRomateFashcom ,

The ETA for the release is not yet known. But you could place the fix yourself, the following screenshot shows the fix you could edit:
![image (1)](https://user-images.githubusercontent.com/23314965/112982380-b5ea9300-915c-11eb-9bc6-7684d3a372a3.png)

If placing the fix is giving you trouble don't hesitate to contact us at support@tig.nl

Have a great day,
Jeffrey

**Comment by jwbos-uhg** [comment]
Hi @tig-jeffreybranderhorst,  There are also no shipping options when only one address line is enabled, is this also fixed?

**Comment by tig-jeffreybranderhorst** [comment]
Hey @jwbos-uhg ,

this is also something we are investigating, we indeed are trying to also get this in the next update.

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment]
@jwbos-uhg 

this has been resolved in v1.9.8. If you still run into any issues, please contact our support.

Have a nice day!

Vincent
