### ISSUE TITLE
[QUESTION] Customs + SKU not found

### ISSUE THREAD

**Issue by ruthgeridema** [tig-nl/postnl-magento2#248]
**Question**
Wij ervaren problemen met het 'customs' segment. Ondanks alle data lijkt hij de customs node niet toe te voegen.
Alle settings zijn ingevuld maar toch komt deze er niet bij. Gaat om de juiste zendingen.

Sommige zendingen gaan wel goed, kan dat iets te maken hebben met configurable products?
https://i.postimg.cc/dQkKV8J5/c0faf843-01d5-4e90-bd4b-d2f3437c56d6.jpg

Daarnaast de vraag; is er een methode om voor gewijzigde SKU's nog labels te kunnen printen?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ruthgeridema ,

We are not aware of any problems with globalpack. Could you contact us at support@tig.nl so we can support you further. 

Have a great day,
Jeffrey
