### ISSUE TITLE
Wrong translation for "Post office location:"

### ISSUE THREAD

**Issue by experius-nl** [tig-nl/postnl-magento2#25]
Hi there,

I'm just reporting a small bug in the translation strings. The string "Post office location:" that is used in template: view/frontend/web/template/Pakjegemak/Address.html does not correspond with the translation in your CSV: "Post Office Location:" i18n/nl_NL.csv.

**view/frontend/web/template/Pakjegemak/Address.html**
`<span data-bind="i18n: 'Post office location:'"></span>`
 **i18n/nl_NL.csv**
`"Post Office Location:","Postkantoor Adres:"`

Thank you.

**Comment by tig-jeffreybranderhorst** [comment]
Hello Experius,

First of all, thank you for contacting us with this improvement for our extension.
I have talked to one of our programmers about this and he said he was gonna fix instantly. 
So in our next version, this will be fixed, thanks again for contacting us.

Sincerely,
Jeffrey Branderhorst.
