### ISSUE TITLE
[BUG] error: Customs segment is required - on a US delivery

### ISSUE THREAD

**Issue by abvdveen** [tig-nl/postnl-magento2#258]
We get an error when trying to generate the label on a delivery to the US, in critical.log:

 <ExceptionData>
              <Description i:nil="true"/>
              <ErrorMsg>Validation failed for shipment: CL504882049NL, Messages:
                CL504882049NL: {[16301] Customs segment is required}
            </ErrorMsg>
              <ErrorNumber>16301</ErrorNumber>
 </ExceptionData>

Click on 'PostNL - Print label'

**Expected result**
A generated label

**Actual result**
[POSTNL-0252] - Er zijn geen valide labels gegenereerd. Bekijk de logs voor meer informatie.

- Magento version: 2.3.6-p1
- PHP version: 7.4
- TIG PostNL version: 1.9.7

**Comment by tig-jeffreybranderhorst** [comment]
Hi @abvdveen ,

The error is saying you did not fill in your barcode settings under worldwide shipping, if you did fill these in then maybe something with saving them went wrong, if that is the case I would like to ask you to contact digitaleklantsupport@postnl.nl for further support. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @abvdveen ,

We will close this issue, if our support is still needed we would like to ask you to contact digitaleklantsupport@postnl.nl for further support.

Have a great day,
Jeffrey
