### ISSUE TITLE
[BUG] No barcode for delivery to Cyprus

### ISSUE THREAD

**Issue by abvdveen** [tig-nl/postnl-magento2#259]
The generated label for a delivery to Cyprus doesn't have a barcode.

**To Reproduce**
Click on 'PostNL - Print label'

** Please complete the following information**
- Magento version: 2.3.6-p1
- PHP version: 7.4
- TIG PostNL version: 1.9.7

**Comment by tig-jeffreybranderhorst** [comment]
Hi @abvdveen ,

We tried to reproduce this on our test site but it worked with no problems at our test site. There must be something else going wrong why cyprus is not working for you, could you contact digitaleklantsupport@postnl.nl  for further support?

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @abvdveen ,

We will close this issue, if our support is still needed we would like to ask you to contact digitaleklantsupport@postnl.nl for further support.

Have a great day,
Jeffrey
