### ISSUE TITLE
[BUG] Letterbox packages not being processed properly in KnockoutJS and /postnl/deliveryoptions/save

### ISSUE THREAD

**Issue by thompalstra** [tig-nl/postnl-magento2#260]
**To Reproduce**
1. Create a product with a `postnl_max_qty_letterbox` > 0
2. Go to the frontend, add the product to the cart
3. Go to the checkout

**Expected result**
Letterbox is shown, selectable and when selected applies the correct price from the matrixrate (when configured) and doesn't cause any frontend or backend errors.

**Actual result**
Selecting letterbox causes a 500 error on the server side:
`Exception #0 (Exception): Notice: Undefined index: date in /app/code/TIG/PostNL/Controller/DeliveryOptions/Save.php on line 195`

**Workaround**
None

**Screenshots**
None, due to customer sensitive data

** Please complete the following information**
Magento 2.3.2
- PHP version: 7.2.0
- TIG PostNL version: 1.9.8

**Comment by tig-jeffreybranderhorst** [comment]
Hi @thompalstra ,

We tested this on our own test site and we did not have any issues, we got a label without error. Could you contact digitaleklantsupport@postnl.nl for further support?

Have a nice day,
Jeffrey

**Comment by thompalstra** [comment]
@tig-jeffreybranderhorst where is this "test" site of yours because I don't believe that this functionality works at all.

**Comment by thompalstra** [comment]
@tig-jeffreybranderhorst can you show me the payload your test environment sent to the backend so I can compare what's being sent on our dev environment?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @thompalstra ,

Could you please contact digitaleklantsupport@postnl.nl so we can support you further? Then you will go into our support flow and we will find out together why it is not working. 

Have a nice day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @thompalstra ,

I tested this again with colleagues and we can reproduce it now, don't know why I did not see it the first time. But we placed it on our backlog to fix, thank you for submitting.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @thompalstra ,

This is fixed in our newest release of the extension!

Have a great day,
Jeffrey
