### ISSUE TITLE
M2.2: logged in customers can't select PostNL shipping method

### ISSUE THREAD

**Issue by Tjitse-E** [tig-nl/postnl-magento2#27]
Currently we are running Magento 2.2 and we encounter the following problem with the PostNL Magento 2 module, extension version 1.1.5 - Alpha.

When a logged in customer tries to order something and chooses ‘Verzenden via PostNL’ the following message pops up when placing the order: ‘Geef een verzendmethode op’ --> Please select a shipping method (see screenshot). This not only happens with the One Step Checkout (as seen on the screenshot below) from Magestore but also with the native checkout. This problem does not occurs only when a use is logged in.

![schermafbeelding_2017-10-23_om_15_30_45](https://user-images.githubusercontent.com/14849044/31892228-c9f4b9e2-b808-11e7-98dd-62036e288900.png)

**Comment by tig-jaspersmits** [comment]
Hi Tjitse,

We are aware of this issue and a fixed should be rolled out this week (most likely today). Please keep an eye on our Github page and our release notes: https://confluence.tig.nl/display/TIGSD/Release+notes+van+de+PostNL+Magento+2+extensie

Kind regards,

Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
Hi Tjitse,

First of all, thank you for creating this issue. We always welcome bug reports in our Github page. I would like to inform you that we fixed the issue concerning logged in customers that aren't able to go through the checkout with Magento version 2.2.

We also released a hotfix of this issue, from now on you can install alpha version v1.1.6 with composer which contains the fix on the bug that you reported.
