### ISSUE TITLE
[BUG] Post Office locations not working in 2.4.3

### ISSUE THREAD

**Issue by thijsdewitt** [tig-nl/postnl-magento2#270]
Logged in customers cannot use Post Office locations because the location is not saved in the Order. Instead the customers address is used.

When you checkout as guest, the Post Office locations is properly saved.

**To Reproduce**
1. Clean install Magento 2.4.3 & Install PostNL
3. Activate PostNL delivery settings
4. Create Customer account & Login
5. Add product to cart & Proceed to checkout
6. Under Shipping Methods select PostNL -> 'Afhalen' and select a location.
7. Complete checkout process

**Expected result**
The order Shipping Address would be te selected Post Office location

**Actual result**
The order Shipping Address is the customers billbing address

**Workaround**
"None"

** Please complete the following information**
- Magento version: 2.4.3
- PHP version: 7.4.15 
- TIG PostNL version: 1.9.9

**Comment by tig-jeffreybranderhorst** [comment]
Hi @thijsdewitt ,

Thank you for submitting this, we just reproduced it, and we will place it on our backlog. Could you submit this issue to PostNL as well via digitaleklantsupport@postnl.nl

Have a great day,
Jeffrey

**Comment by DuckThom** [comment]
We also ran into this issue after upgrading to 2.4.3 and created the following patch for this as a workaround:

```
diff --git a/vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php b/vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php
index a358ba31..ee6d6f8a 100644
--- a/vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php
+++ b/vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php
@@ -163,6 +163,15 @@ class PickupAddress
         $houseNr = $address['HouseNr'];
         $houseNrExt = isset($address['HouseNrExt']) ? $address['HouseNrExt'] : null;

-        return [$address['Street'], $houseNr, $houseNrExt];
+        $street = [
+            $address['Street'],
+            $houseNr,
+        ];
+
+        if (!empty($houseNrExt)) {
+            $street[] = $houseNrExt;
+        }
+
+        return $street;
     }
 }
```

**Comment by tig-jeffreybranderhorst** [comment]
Hi @DuckThom ,

Thank you! I will add this to the backlog issue. 

Have a great day,
Jeffrey

**Comment by thijsdewitt** [comment]
> We also ran into this issue after upgrading to 2.4.3 and created the following patch for this as a workaround:
> 
> ```
> diff --git a/vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php b/vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php
> index a358ba31..ee6d6f8a 100644
> --- a/vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php
> +++ b/vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php
> @@ -163,6 +163,15 @@ class PickupAddress
>          $houseNr = $address['HouseNr'];
>          $houseNrExt = isset($address['HouseNrExt']) ? $address['HouseNrExt'] : null;
> 
> -        return [$address['Street'], $houseNr, $houseNrExt];
> +        $street = [
> +            $address['Street'],
> +            $houseNr,
> +        ];
> +
> +        if (!empty($houseNrExt)) {
> +            $street[] = $houseNrExt;
> +        }
> +
> +        return $street;
>      }
>  }
> ```

I can confirm this patch is working on our end. Thanks!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @thijsdewitt ,

Thank you for confirming it works! 

Have a great day,
Jeffrey
