### ISSUE TITLE
[BUG] Shipment Type: "Domestic" after selecting post office location 

### ISSUE THREAD

**Issue by thijsdewitt** [tig-nl/postnl-magento2#271]
When customers have selected a post office location and the order has failed due to payment issues. Customers are redirected back to our shop and can try again. When the payment goes well, the shipment type changes from post office to domestic standard shipment in Magento. This generates a normal shipping label instead of a shipping label for collection points. The collection points do not accept the normal shipping labels and refuse it at the door so that the package is returned.

**To Reproduce**
1. Add product to cart and proceed to checkout.
2. Fill in your shipping address and select a post office location for shipping.
3. During payment, cancel your order. You will be redirected to you shopping cart.
3. Fill in your shipping address and select a post office location for shipping.
4. Now complete your payment.

**Expected result**
The order's Shipment Type to be Post Office

**Actual result**
The order's Shipment Type is Domestic

**Workaround**
None

** Please complete the following information**
- Magento version: 2.4.3
- PHP version: 7.4.15
- TIG PostNL version: 1.9.9

**Comment by tig-jeffreybranderhorst** [comment]
Hi @thijsdewitt ,

This is a known issue, we have this issue on our backlog and are fixing this! Thank you for submitting.

Have a great day,
Jeffrey

**Comment by thijsdewitt** [comment]
Hi Jeffrey ,
Thanks for the fast response. Great to hear! When do you expect this fix to be released? (1 week+ or 1 month+). Otherwise we will look for a (temporary) fix ourself.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @thijsdewitt ,

Unfortunately I don't have a time indication yet.  We are trying to fix and test it asap and then the release will follow.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @thijsdewitt ,

This should be fixed in 1.10. 

Have a great day,
Jeffrey
