### ISSUE TITLE
[BUG] 500 error for postnl/deliveryoptions/save/ action

### ISSUE THREAD

**Issue by boris1988** [tig-nl/postnl-magento2#273]
Sometimes I got a 500 error for action **postnl/deliveryoptions/save/**

**To Reproduce**
1. Go to Details Product Page and add product to the cart
2. Go to the Checkout page and fill shipping information
3. Select the  Shipping via PostNL method
4. Select Pick-up point from the list without House Nr. Ext. 
![Screenshot from 2021-10-13 14-56-27](https://user-images.githubusercontent.com/2422927/137127965-d4473c8e-b020-4e1d-b60d-abc611c3a6f3.png)

**Expected result**
postnl/deliveryoptions/save/ should return 200 status and pick up point saved

**Actual result**
postnl/deliveryoptions/save/ return 500 status with the error 
_Exception #0 (Exception): Notice: Array to string conversion ..._
![Screenshot from 2021-10-13 14-57-26](https://user-images.githubusercontent.com/2422927/137128173-ba8cf7e4-80af-4e58-9f9a-71ae0c693aac.png)

**Workaround**
I got an error only for pick-up points without  House Nr. Ext.
The issue was caused by vendor/tig/postnl-magento2/Helper/DeliveryOptions/PickupAddress.php::164
and vendor/magento/module-customer/Model/Address/AbstractAddress.php::_implodeArrayValues.
According to PickupAddress.php we can get NULL in the last element in Street Array.
NULL is not a scalar value, AbstractAddress.php::_implodeArrayValues return array instead of string.
**Solution**:  change the default value to empty string instead of NULL
![Screenshot from 2021-10-13 15-05-31](https://user-images.githubusercontent.com/2422927/137129099-02718882-246f-44ef-a136-48c1cacf3802.png)

** Please complete the following information**
- Magento version: 2.4.3
- PHP version: 7.4
- TIG PostNL version: 1.9.5

**Comment by tig-jeffreybranderhorst** [comment]
Hi @boris1988 ,

Do you have an example address for us where we can test with? Because I cannot reproduce it until now. So I would like to test with address where this happens with. 

Have a great day,
Jeffrey

**Comment by boris1988** [comment]
Hi @tig-jeffreybranderhorst 
I cant get pick up points today
But you can check the address on a screenshot
![Screenshot from 2021-10-14 10-19-28](https://user-images.githubusercontent.com/2422927/137270543-212983b2-ad49-4ca5-8e90-0f7732d15190.png)
I don't know why but today pickup points are not available
Regards,
Boris
