### ISSUE TITLE
[BUG] Housenumber missing from new shipping addresses not in  NL

### ISSUE THREAD

**Issue by ainigma32** [tig-nl/postnl-magento2#274]
**To Reproduce**
1. Go to checkout
2. Create a new address not in the Netherlands (e.g. Belgium, Germany)
3. Complete the order
4. View order in the backend

**Expected result**
A shipping address with a housenumber

**Actual result**
A shipping address without a housenumber

**Workaround**
"None"

**Screenshots**
On the checkout:
![nieuw_adres_fr](https://user-images.githubusercontent.com/4005641/137492002-b6cd7094-1f20-4c6a-abbb-6eabc1e4e639.png)

In the backend:
![backend_adres_fr](https://user-images.githubusercontent.com/4005641/137492220-39675183-5811-4f8b-a326-32b9a18fd3cd.png)

- Magento version:  Magento 2.4.3-p1
- PHP version: 7.4.24
- TIG PostNL version: 1.9.9

Please note: we are also using the Mageplaze OneStepCheckout and the postcode check provided by your module.

**Comment by tig-jeffreybranderhorst** [comment]
Hey @ainigma32 ,

I also pinged our contact at PostNL about this issue! Hopefully I can soon give more information. 

Have a great day,
Jeffrey

**Comment by ubedarab** [comment]
This module is not work from customer/account/create use address or 
edit address from my account customer/address/edit/id/
There is no housernumber and additional housernumber save.

**Comment by ubedarab** [comment]
NOTICE: UNDEFINED INDEX: STREET IN /VENDOR/TIG/POSTNL-MAGENTO2/PLUGIN/POSTCODECHECK/MANAGEMENT/CUSTOMERFORM.PHP ON LINE 90

I got this error on customer/account/create with using address.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ubedarab,

Thank you for contacting us, could you also send this to digitaleklantsupport@postnl.nl, so they can give you support on your issue? 

Met vriendelijke groet / Kind regards / Mit freundlichen Grüßen / 最好的祝福,

Jeffrey Branderhorst
CUSTOMER CARE SPECIALIST
020 - 21 81 000

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ubedarab,

We will close this issue because we have faith that PostNL will be able to help you! 

Have a great day,
Jeffrey
