### ISSUE TITLE
[BUG] Can not make a label for Global Pack shipment because of error

### ISSUE THREAD

**Issue by richardreen** [tig-nl/postnl-magento2#276]
Let a customer make and order for Germany or make a test order for Germany was dit een bestelling naar Duitsland
And make now a send label in the backend. This will fail wit an error and no information is written to logs!!

**To Reproduce**
1. Go to Sales and Shipments '...'
2. Select shipment and click then PostNL - Print label and confirm shipments
3. Screen goes blank and goes back with error lines in top
4 Go to critical and debug.log....both have  no information about this error.
 

**Expected result**
A shipments label and a confirmed shipments 
\
**Actual result**
No label and no confirmation, only two red lines. with error 0070 and 0252

**Workaround**
None

**Screenshots**

![Schermafbeelding 2021-10-24 om 10 01 30](https://user-images.githubusercontent.com/18627705/138586057-b6dd32f9-22d4-4736-b95c-e49dbe1ec8e8.png)
![Schermafbeelding 2021-10-24 om 10 04 54](https://user-images.githubusercontent.com/18627705/138586082-9156d809-2c25-4ebd-979e-00f4d16d5e93.png)

** Please complete the following information**
- Magento version: 2.4.3
- PHP version: 7.3.0
- TIG PostNL version: 1.10.0

**Comment by tig-jeffreybranderhorst** [comment]
Hi @richardreen,

We assume you contacted PostNL and are working on a solution or already have one! We will close this issue because of that, and we did not hear anything back! 

Have a great day,
Jeffrey
