### ISSUE TITLE
`ship_at` not filled when an order is created

### ISSUE THREAD

**Issue by Mark-Sherpaan** [tig-nl/postnl-magento2#28]
Our extension fetches orders from Magento and applies some business logic based on the shipping date. The PostNL extension for Magento1 has a field called `confirm_date` for this, the Magento2 version uses  `ship_at`.

But it looks like the `ship_at` field (`Shipping date` column in Sales/Orders list) is filled after creating a shipment. Is it possible to fill this field right after the order is created? 

Now there is no way to see when to ship an order before creating the shipment. This feels wrong, because this way the shipping date of a magento shipment could be days before the actual shipping date.

Related issue: https://jira.tig.nl/projects/POSTNLM2/issues/POSTNLM2-365

**Comment by tig-michielgerritsen** [comment]
Hello Mark,

Thanks for pointing this out. This feature has already been created as part of a bigger release. It is expected to be shipped out in the next few weeks.

**Comment by tig-michielgerritsen** [comment]
Hello @Mark-Sherpaan,

Yesterday we've released a new version which fills the `ship_at` column when an new order is placed:
https://github.com/tig-nl/postnl-magento2/releases/tag/v1.2.0
