### ISSUE TITLE
[BUG] Create Order Through API Performance Issue

### ISSUE THREAD

**Issue by kaplansin** [tig-nl/postnl-magento2#280]
**To Reproduce**
1. Create 10K order through API
2. While creating orders performance will drop in time.
**Expected result**
Performance can change in time, but its continuously dropping. Avg Required time should be stable.

**Actual result**
performance issue.

**Workaround**
None

**Screenshots**
time required to create Order through API at first few request.
![Screenshot from 2021-11-19 11-56-27](https://user-images.githubusercontent.com/894917/142594944-112d6ced-f701-4872-b35d-182dff29ed45.png)

time reqired to create Order through API at first 2K requets.
![Screenshot from 2021-11-19 11-56-49](https://user-images.githubusercontent.com/894917/142595053-ae70134a-bd0b-4130-990c-abf1e5a8c013.png)

- Magento version: [e.g. Magento 2.4.3-p1]
- PHP version: [e.g. 7.4.21]
- TIG PostNL version: [e.g. 1.10.0]

**Comment by tig-jeffreybranderhorst** [comment]
Hi @kaplansin ,

Could you give us more info about this? Do you see PostNL taking a lot of time? 

Have a great day,
Jeffrey

**Comment by kaplansin** [comment]
While creating New Order through API,
there is no user session and post data does not contain order_id as expected.

Observer/SalesOrderSaveAfter/CreatePostNLOrder.php Observer tries to find existing postnl order record  
\TIG\PostNL\Observer\SalesOrderSaveAfter\CreatePostNLOrder::getPostNLOrder

through provided order_id or quote_id saved on session
\TIG\PostNL\Model\OrderRepository::getByQuoteWhereOrderIdIsNull 
Because we dont have user session quote_id is also null, tig order getList run without filter, and get all created tig_postnl_orders 
```
 $filter = $this->filterBuilder->setField('quote_id');
 $filter->setValue($quoteId);
 $this->searchCriteriaBuilder->addFilters([$filter->create()]);

 $list = $this->getList($this->searchCriteriaBuilder->create());`
```

**Comment by kaplansin** [comment]
We have created a PR for this issue,
there is no need to query tig_postnl_orders table if there is no quote_id 
https://github.com/tig-nl/postnl-magento2/pull/281

**Comment by tig-jeffreybranderhorst** [comment]
hi @kaplansin ,

We have seen your PR, thank you for this. Our developers are looking at your PR. When they have a verdict, they will react to your PR.  Thank again for thinking along!

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment]
Hi @kaplansin 

As shared in your PR, your update has been included within the plugin. Thanks again for helping getting the plugin better.

Have a nice day!
Vincent
