### ISSUE TITLE
[BUG] Issue with latest update and configurable products with qty of child item

### ISSUE THREAD

**Issue by JoostWan** [tig-nl/postnl-magento2#282]
With the latest version (1.10.0) there is a issue with configurable products and the qty of the child product. 

Steps.

1. Place a order with a configurable product with a QTY of 2 
2. Place the order and select a PostNL Shipping method

Now the item of the child product has a qty of 4 in the database instead of 2. You can check it in table `sales_order_item`

When you have a QTY of 4 the child gets a QTY of 16. 

In our case we used the `qty_ordered` for the fulfilment company, so the customer get two free products. 

![Screenshot 2021-11-25 at 13 47 25](https://user-images.githubusercontent.com/5435412/143444534-c4105330-06c5-49b8-817a-6f5aab7a6b92.png)

When we disable this line the problem is "solved" 

https://github.com/tig-nl/postnl-magento2/blob/master/Service/Shipping/LetterboxPackage.php#L211

This issue is related I think, https://github.com/tig-nl/postnl-magento2/issues/278

- Magento version: 2.3.7-p1
- PHP version: 7.4
- TIG PostNL version: 1.10.0

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JoostWan ,

We are aware of this being an issue right now. We are working hard on a solution for this issue! The plan is to roll out a solution in a few days.  Thank you for submitting this.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi, 

we have made a 1.10.1 release with a change in the configurable products. Can you test @JoostWan if this also solves your problem?

Have a great day,
Jeffrey

**Comment by memen45** [comment]
The update 1.10.1 does not show up with composer. It seems the composer.json file was not updated with the new version number. `composer show tig/postnl-magento2` shows 1.10.0 as latest version.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @memen45,

Thank you for giving us a heads up, we updated the version number! 

Have a great day,
Jeffrey

**Comment by memen45** [comment]
Thanks, I think I was able to install the new version. I cannot verify in admin panel as it still shows 1.10.0, but that is probably [this line](https://github.com/tig-nl/postnl-magento2/blob/a5655a67023482eb5d756b392d8307d0c15405f8/Block/Adminhtml/Config/Support/SupportTab.php#L41) that was also not updated. 

Will test if the update works.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @memen45,

Your update should have worked, but you are correct that the label in the backed did not update. We understand that this can be confusing, we going to change this. Thank you for notifying us! 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @memen45,

Small update, the next version will have the correct labels in the backend. Thanks again for bringing this to our attention.

Have a great day,
Jeffrey
