### ISSUE TITLE
V11.1 RC1 is suddenly installed and contains errors

### ISSUE THREAD

**Issue by richardreen** [tig-nl/postnl-magento2#285]
To Reproduce

Composer update..

This morning is tried to upgrade some extensions for Magento 2.4.3 and suddenly the extension of PostNL upgraded to v11.1.0 RC1.

Later I discovered that his version contains and big error. When we made shipments for our orders in the backend  the only available shipment method is EU Pack while we have shipments for the Netherlands. So we could not made the shipment and we reverted back to version 1.10.1 and all is correct again.

But when we do "composer update"  the version 1.11.0 RC1 is installed again and the error is in place again.
So this version is really not ready for a proaction environment and should me removed for the repo.

**Comment by TIG-Lucas-Hoeffnagel** [comment]
Hi @richardreen,

The RC1 was not supposed to be installed as a stable release. Is it perhaps possible that your minimum-stability is set to dev? To avoid any new problems we have removed the RC from Packagist for now.

Kind regards,

Lucas Hoeffnagel
