### ISSUE TITLE
[QUESTION] Trying to import Matrix table results in invalid country codes error

### ISSUE THREAD

**Issue by ThomasMW** [tig-nl/postnl-magento2#286]
I am trying to import a matrix table but when doing so I am presented with a list of errors specifying that the country codes are invalid even though they are identical to the country codes specified in the manual linked by your documentation [here](https://docs.tig.nl/display/SDPOSTNL/PostNL+Matrix+rates+instellen+in+Magento+2).

Country codes are specified [here](https://www.postnl.nl/Images/Handleiding-zendingen-en-adressen-importeren_tcm10-18728.pdf) on page 31.

I'm having no problem doing a Table Rate import but I would like to use a Matrix because of country, weight and subtotal combinations.

![Screenshot from 2022-01-04 11-36-57](https://user-images.githubusercontent.com/3084213/148050420-e4b0db99-12d6-4c55-ab20-f1f87fab9221.png)

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ThomasMW ,

We have seen this before, the reason then was that in general -> general at the Allow Countries options the countries were not selected, so they were not allowed.  You can check if this is also the reason in your environment. If it is not, I would like to ask you to contact PostNL at digitaleklantsupport@postnl.nl so we and PostNL can assist you further with this!

Have a great day,
Jeffrey

**Comment by ThomasMW** [comment]
Hi Jeffrey,

Thanks for the quick feedback. This indeed seemed to be the case. I was under the impression that setting 'Ship to Applicable Countries' to 'Specific Countries' would have the same effect.

Thanks again!
