### ISSUE TITLE
[BUG] Versions 1.9.4 up to latest are not compatible with Magento 2.3.4

### ISSUE THREAD

**Issue by fmm-rwalraven** [tig-nl/postnl-magento2#287]
**To Reproduce**
1. Set up a clean Magento 2.3.4 install
2. Install this module `composer require tig/postnl`
3. run `./bin/magento`

**Expected result**
Magento not crashing with weird Zend errors

**Actual result**
Class 'Zend\ServiceManager\AbstractPluginManager' not found

**Workaround**
Manually downgrade to version 1.9.3

**Screenshots**
N/A

- Magento version: 2.3.4
- PHP version: 7.3.29
- TIG PostNL version: 1.9.4 up to latest

**Comment by tig-jeffreybranderhorst** [comment]
Hi @fmm-rwalraven ,

I just tried to install TIG PostNL version: 1.9.4 on Magento version 2.3.4. And this was successful, we did not get any ZEND error. Magento version 2.3.4 is also a little old, maybe you can also update your Magento version?  If this error keeps persisting, I would like to ask you to contact PostNL at digitaleklantsupport@postnl.nl for further support.

Have a great day,
Jeffrey

**Comment by fmm-rwalraven** [comment]
@tig-jeffreybranderhorst Installing is not the issue for me either. Did you also run the magento binary after? Either way this is more of a heads-up that the latest versions of this plugin are incompatible with older Magento versions, the fix is literally already stated under "Workaround"

**Comment by tig-jeffreybranderhorst** [comment]
Hi @fmm-rwalraven,

Thank you for the reaction, We did run the Magento binary. We will keep this issue and the work-a-round in mind, thank you for submitting this! 

Have a great day,
Jeffrey
