### ISSUE TITLE
[BUG] Track and Trace URL pickup point

### ISSUE THREAD

**Issue by JoostWan** [tig-nl/postnl-magento2#288]
When a track and trace e-mail is send to the customer it use the wrong postcode for the track and trace url. It' uses this shipment postcode but that url is not working. When you change it to the billing postcode from the order it's working. In the backend in the shipment from the order the url is fine. But only in the track and trace e-mail the url is with the wrong postcode. 

** Please complete the following information**
- Magento version: 2.3.7
- PHP version: 7.4
- TIG PostNL version: 1.10.0

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JoostWan,

Thank you for submitting this issue, we are going to investigate this. Could you also contact PostNL about this issue on digitaleklantsupport@postnl.nl?  This way, we can give you further support on the issue! 

Have a great day,
Jeffrey

**Comment by JoostWan** [comment]
@tig-jeffreybranderhorst why is this closed? Can it be reproduced or it's fixed?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JoostWan,

We have closed this issue because the first line of support is handled by PostNL. PostNL can forward this issue to us when needed. If that happens, we will be in contact with you about this issue. Did you already contact digitaleklantsupport@postnl.nl for the support?

Have a great day,
Jeffrey

**Comment by JoostWan** [comment]
@tig-jeffreybranderhorst Yes, our customer has contacted PostNL about this issue.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JoostWan,

Great! In that case, I'm sure it will all work out.  Thank you for the update.

Have a great day,
Jeffrey

**Comment by JoostWan** [comment]
@tig-jeffreybranderhorst This is still an issue, can you help us fix this issue? 

https://github.com/tig-nl/postnl-magento2/blob/master/Helper/AbstractTracking.php#L170

Here the shipping address is used but for Pickup point delivery the track a trace url needed the postcode of the billing address. 

https://github.com/tig-nl/postnl-magento2/blob/master/Helper/AbstractTracking.php#L207

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JoostWan ,

I still need to direct you to digitaleklantsupport@postnl.nl for support on this issue. The shipping address postcode should be used according to the PostNL employee I just spoke to.

Have a great day,
Jeffrey
