### ISSUE TITLE
magento2 version:

### ISSUE THREAD

**Issue by Ralfefernandes** [tig-nl/postnl-magento2#29]
By installing this extension on Magento ver. 2.2.0
I get this error: Fatal error: Class 'FPDI' not found in /home/exemple/public_html/exemple.com/app/code/TIG/PostNL/Service/Pdf/Fpdi.php on line 39
exemple@am28 [~/public_html/exemple.com]# 

This error appear by running  Magento compile command. php bin magento/ setup:di:compile

**Comment by tig-michielgerritsen** [comment]
Hello @Ralfefernandes,

You installed the extension the wrong way. Please remove the app/code/TIG folder, and install the extension using composer:
`composer require tig/postnl-magento2`

**Comment by Ralfefernandes** [comment]
ra@hp:/var/www/html/magento2$ composer require tig/postnl-magento2
Using version ^1.2 for tig/postnl-magento2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing setasign/fpdi (1.6.1): Downloading (100%)         
  - Installing setasign/fpdf (1.8.1): Downloading (100%)         
  - Installing tig/postnl-magento2 (v1.2.0): Downloading (100%)         
setasign/fpdi suggests installing setasign/fpdi-fpdf (Use this package to automatically evaluate dependencies to FPDF.)
setasign/fpdi suggests installing setasign/fpdi-tcpdf (Use this package to automatically evaluate dependencies to TCPDF.)
Writing lock file
Generating autoload files

Please re-run Magento compile command. Use the command "setup:di:compile"
ralfe@hp:/var/www/html/magento2$ sudo php bin/magento setup:di:compileCompilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% < 1 sec 50.0 Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 52.0 Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec Repositories code generation... 2/7 [========>-------------------]  28% 2 secs 1Service data attributes generation... 2/7 [========>-------------------]  28% 2 Service data attributes generation... 3/7 [============>---------------]  42% 2 Application code generator... 3/7 [============>---------------]  42% 2 secs 154Application code generator... 4/7 [================>-----------]  57% 5 secs 174Interceptors generation... 4/7 [================>-----------]  57% 5 secs 174.0 Interceptors generation... 5/7 [====================>-------]  71% 9 secs 190.0 Area configuration aggregation... 5/7 [====================>-------]  71% 9 secsArea configuration aggregation... 6/7 [========================>---]  85% 13 secInterception cache generation... 6/7 [========================>---]  85% 13 secs 256.0 MiBErrors during compilation:
	PHPCuong\Region\Model\ResourceModel\Region\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \PHPCuong\Region\Model\ResourceModel\Region\Grid\connection; File: 
/var/www/html/magento2/vendor/php-cuong/magento2-regions-manager/Model/ResourceModel/Region/Grid/Collection.php

Total Errors Count: 1

                                           
  [Magento\Framework\Validator\Exception]  
  Error during compilation                 
                                           

setup:di:compile


I still have the same problem, even using the composer command

**Comment by tig-michielgerritsen** [comment]
Hello @Ralfefernandes,

You have an error on the class `PHPCuong\Region\Model\ResourceModel\Region\Grid\Collection`, which does not belong to the PostNL extension. This error is caused by some other extension in your Magento store.
