### ISSUE TITLE
[QUESTION] Adding costs for same day delivery in the checkout

### ISSUE THREAD

**Issue by ThomasMW** [tig-nl/postnl-magento2#290]
I understand that you can add Same Day delivery to the checkout by setting the shipping duration to 0 days with a preferred cutoff time. I have met these requirements, but no options appear in the checkout for same day deliveries. Are there any more requirements that I am missing?

I'm using an existing address from a big city so I assume the delivery option is available for this zipcode.

Since we are working with PostNL fulfilment which charges added costs for this type of delivery I want to add this to the total shipping cost at the checkout. However, although I can find an easy way to add an extra cost for evening deliveries I see no such option for same day deliveries.

How are these costs suppose to be added, by matrix perhaps?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ThomasMW,

Thank you for contacting us. It seems like you configured it correctly, with the information I got, I would say it should work. For the shipping cost, a matrix should work if you get same day displayed because of the different product code.  Can you contact PostNL directly about this, so they can assist you further, if needed they will send the support through to us, so we can assist you further! You can contact PostNL at:  digitaleklantsupport@postnl.nl  

Have a nice day,
Jeffrey

**Comment by treeofinformation** [comment]
Hi @tig-jeffreybranderhorst,

Thank you for the feedback. I've already contacted PostNL about this at the email address you suggested, I've even called them but they suggested I send in an email instead. They first sent me a copy paste from the Magento 1 documentation and then they couldn't tell me how to configure the matrix and said they would be contacting the developer (so TIG) but I haven't heard anything back for a few days.

I'm looking at the documentation here: https://docs.tig.nl/display/SDPOSTNL/PostNL+Matrix+rates+instellen+in+Magento+2

When configuring the matrix there a multiple columns; 
Country, Province/state, Zipcode,Weight (and higher), Shipping price (and higher), Amount (and higher), Parcel type, price, Instructions.

I'm assuming I need to specify a specific Parcel type, but which one? The documentation suggests you can only use: 
- regular
- pakjegemak
- extra@home
- letterbox_package

This doesn't suggest that I can specify a same day delivery package. Am I missing something?

**Comment by ThomasMW** [comment]
Hi @tig-jeffreybranderhorst,

Thank you for the feedback. I've already contacted PostNL about this at the email address you suggested, I've even called them but they suggested I send in an email instead. They first sent me a copy paste from the Magento 1 documentation and then they couldn't tell me how to configure the matrix and said they would be contacting the developer (so TIG) but I haven't heard anything back for a few days.

I'm looking at the documentation here: https://docs.tig.nl/display/SDPOSTNL/PostNL+Matrix+rates+instellen+in+Magento+2

When configuring the matrix there a multiple columns; 
Country, Province/state, Zipcode,Weight (and higher), Shipping price (and higher), Amount (and higher), Parcel type, price, Instructions.

I'm assuming I need to specify a specific Parcel type, but which one? The documentation suggests you can only use: 
- regular
- pakjegemak
- extra@home
- letterbox_package

This doesn't suggest that I can specify a same day delivery package. Am I missing something?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ThomasMW,

You are not missing something, the same day is not writing down in the documentation I see. In Magento 2 same day is not a loose option. But I expect with the 0 days shipping duration, it will get a different product ID. When PostNL contacted us about this issue, we will investigate this further with you!  Maybe you can contact PostNL again asking for the status of your issue. 

Have a great day,
Jeffrey

**Comment by ThomasMW** [comment]
Hi @tig-jeffreybranderhorst,

So just to be clear, this is being looked into by TIG at the moment?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ThomasMW,

Not yet, PostNL need to send the support request first. The moment we receive the request, we will pick this up and investigate it further with you.  

Have a great day,
Jeffrey

**Comment by ThomasMW** [comment]
Hi @tig-jeffreybranderhorst,

Thank you for the feedback, back to PostNL I go.
