### ISSUE TITLE
[BUG] Amasty amasty/module-single-step-checkout >= 4.0.1 not working anymore

### ISSUE THREAD

**Issue by martijn-bigbridge** [tig-nl/postnl-magento2#295]
If the support is still needed for the amasty checkout then it don't work anymore with the latest amasty version.

- amasty/module-single-step-checkout >= 4.0.1 
- Magento version: 2.4.x
- TIG PostNL version: 1.10.1

File: vendor/tig/postnl-magento2/view/frontend/web/js/Compatibility/amasty_checkout/shipping-mixin.js

I guess that the following files don't exist anymore:
        'Amasty_Checkout/js/view/utils',
        'Amasty_Checkout/js/model/payment/payment-loading',
        'Amasty_Checkout/js/action/get-totals',
        'Amasty_Checkout/js/model/shipping-registry',
        'Amasty_Checkout/js/model/address-form-state',
        'Amasty_Checkout/js/model/events',

**Comment by tig-jeffreybranderhorst** [comment]
Hi @martijn-bigbridge,

Thank you for contacting us. At this moment PostNL extension does not support any checkout yet, except the default Magento checkout. PostNL gives the primary support on the extension could you contact PostNL directly about this? You can contact PostNL via digitaleklantsupport@postnl.nl. In this way you can let them now that support for third party checkouts is wished for. 

Have a great day,
Jeffrey

**Comment by martijn-bigbridge** [comment]
Hi,

Is it then an idea that you remove vendor/tig/postnl-magento2/view/frontend/web/js/Compatibility/amasty_checkout because it won't work with the latest versions, and there is no support? I guess that is better than keeping that extra file, and other people will mention it here again in the future.

Thanks

**Comment by tig-jeffreybranderhorst** [comment]
Hi @martijn-bigbridge and @peterjaap,

Thank you both for thinking along. We can see how this can be confusing. I will place this and the pull request attached on our backlog.  
Thank you for submitting this. 

Have a great day,
Jeffrey

**Comment by peterjaap** [comment]
I fixed the original error instead of removing support. This is the new PR: https://github.com/tig-nl/postnl-magento2/pull/313

Works for us!
