### ISSUE TITLE
[BUG] Logger declaration compatibility in Magento 2.4.4

### ISSUE THREAD

**Issue by jeroen-dhm** [tig-nl/postnl-magento2#299]
**To Reproduce**
1. Install TIG_PostNL in Magento
2. Do anything

**Expected result**
No errors

**Actual result**
An error is thrown stating that TIG\PostNL\Loggin\Log::addRecord is not compatible with Monolog\Logger::addRecord

```PHP Fatal error:  Declaration of TIG\PostNL\Logging\Log::addRecord($level, $message, array $context = Array) must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = Array): bool in /data/web/magento2/vendor/tig/postnl-magento2/Logging/Log.php on line 67```

**Workaround**
None

** Please complete the following information**
- Magento version: 2.4.4
- PHP version: 7.4.8
- TIG PostNL version: 1.12.0

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jeroen-dhm,

Thank you for contacting us, we have not released a version yet that supports the newest Magento's versions because we need to test it before releasing the new version.
Thank you again for already submitting this, I will place it on the backlog, so we can fix this for the new release. 

Have a great day,
Jeffrey

**Comment by richardreen** [comment]
It is some weeks later and still this error is actual. Can not upgrade to 2.4.4 because of this error. When will this be solved?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @richardreen ,

This is correct, we are working on the new release. We made a fix for this issue, but then other issues got our attention that also need to be fixed that is why the release is not out yet. 

Have a great day,
Jeffrey

**Comment by alex-histev** [comment]
Hi @richardreen,

You can change the code in line 67 to follow:

`public function addRecord(int $level, string $message, array $context = []): bool`

**Comment by richardreen** [comment]
> Hi @richardreen,
> 
> You can change the code in line 67 to follow:
> 
> `public function addRecord(int $level, string $message, array $context = []): bool`

Tried it, but same result!! But I am still on 2.4.3!!

**Comment by richardreen** [comment]
> Hi @jeroen-dhm,
> 
> Thank you for contacting us, we have not released a version yet that supports the newest Magento's versions because we need to test it before releasing the new version. Thank you again for already submitting this, I will place it on the backlog, so we can fix this for the new release.
> 
> Have a great day, Jeffrey

We are more then 2 months after the release of 2.4.4. Only this extension is not updated and not compatibel with 2.4.4. It is getting annoying now!! You can write ...you can turn this extension off...but that is not a option as we are using PostNL to send the order...and this is the only extension that can do it with Magento2
