### ISSUE TITLE
[BUG] Saving addresses from admin results in data loss

### ISSUE THREAD

**Issue by Paasi-gs** [tig-nl/postnl-magento2#309]
Saving addresses from admin (and i guess also API) with country code NL will result in data loss of second and third street values (house number and addition)

See: https://github.com/tig-nl/postnl-magento2/blob/master/Plugin/Postcodecheck/Management/CustomerForm.php#L74

        $housenumber     = $request->getPostValue('tig-housenumber');
        $housenrAddition = $request->getPostValue('tig-housenumber-addition');

        $result['street'] = [
            $result['street'][0],
            $housenumber,
            $housenrAddition
        ];

This code replaces the second and third street with a post value that does not exist when saving it though admin or using the API for this. 

**To Reproduce**
1. Go to admin
2. Open customer > Address (with NL country)
3. Save address, second and third street will be vanish

**Expected result**
Second and third street should not be removed

**Actual result**
Second and third street should are removed

**Temp solution**
Added a check on AreaCode for now to not lose this data:

        if ($this->state->getAreaCode() == 'adminhtml') {
            return $result;
        }

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Paasi-gs ,

Maybe you have already seen it, but we updated our extension where this is fixed. Thank you again for submitting and if you come across other problems you can always contact us.

Have a great day,
Jeffrey
