### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by henk-hypershop** [tig-nl/postnl-magento2#31]
After upgrading to 1.2.0, we cannot compile. Compiler get stuck on:

[ReflectionException]
Class TIG\PostNL\Service\Order\ProductCode does not exist

**Comment by tig-michielgerritsen** [comment]
Hello @henk-hypershop,

Can you reproduce this on a clean install? Please make sure you have cleaned all caches. The compilation is tested with every commit in Continues Integration. This is most likely a local problem.

**Comment by henk-hypershop** [comment]
No, we are updating on an existing store and facing this error:
Class TIG\PostNL\Service\Order\ProductCode does not exist

Still persist after clearing all caches.

**Comment by henk-hypershop** [comment]
Has been fixed!
