### ISSUE TITLE
[BUG] Letterbox shipment created for Belgian order

### ISSUE THREAD

**Issue by WalterSmulders** [tig-nl/postnl-magento2#311]
When "Activate Letterbox Package" is set to Yes and "Calculation mode" is set to Automatic there was an order with an Belgian shipping address that automatically got a letterbox shipment created. This should not be the case since letterbox packages should only be shipping inside The Netherlands?

To Reproduce

Go to admin
Enable Letterbox package and set it to automatic calculation mode
Create an order that is eligible for Letterbox package inside The Netherlands
Use a Belgian shipment address

Expected result
Shipment should not be Letterbox package

Actual result
Shipment gets Letterbox package

Temp solution
Unknown

PostNL version: 1.12.1
Magento version: 2.3.7

**Comment by tig-vincentthart** [comment]
Hi @WalterSmulders 

We will close this issue, the PostNL support should be able to help you with your issue.

When needed they will raise it with us for further investigation.

Have a nice day!
Vincent
