### ISSUE TITLE
[BUG] Billing housenumber missing after update to 1.12.2

### ISSUE THREAD

**Issue by ZIPITRO** [tig-nl/postnl-magento2#317]
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
[x] I've **verified**

### What is the purpose of your *issue*?
[x] Bug report (encountered problems with the TIG PostNL Magento extension)
[x] This issue does not contain any security sensitive information

### If the purpose of your issue is a *bug report*

You can reproduce with below steps:
(only guests experience this)

1. Add product to basket
2. Go to checkout
3. Fill in your email, name, address and phone number
4. Summary shows the billing house number

![checkout-summary-ok](https://user-images.githubusercontent.com/22952492/176131145-477ca3c8-24df-4588-bd28-58f1a0990303.png)

After completing the order it shows the billing house number empty( non expected result )

![order-billing-hn-missing](https://user-images.githubusercontent.com/22952492/176131668-6dba0c14-e817-4b43-8e53-c97e5e9c5402.png)

Expected result

![order-billing-hn-expected-result](https://user-images.githubusercontent.com/22952492/176132858-9d15d84e-e726-4a1e-8d7e-505ba1d7357a.png)

Images are for reference only and shown addresses may mix up, but it shows the result, which is different than the expected result.

Please check and let us know if there is any workaround available.

Have a great day!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ZIPITRO ,

We just tested on a clean Magento, and we could not reproduce this issue. We think this happens because you are using a One step checkout?  We would recommend to contact PostNL directly to talk about the One step checkout support. You can contact them via digitaleklantsupport@postnl.nl

Have a great day,
Jeffrey

**Comment by ZIPITRO** [comment]
Hi Jeffrey,

Thank you for your feedback, but the previous versions were not an issue, we already stopped using the PostNL address check which introduced other trouble which was luckily fixed by using another address checker.

We have a One Page checkout and had zero issues for a little while till this version, I will talk to my clients and contact PostNL.

**Comment by ZIPITRO** [comment]
Its not fixed, I made a workaround for our existing export and I will till there is an update have to manually change the billing house number to have proper invoices, this causes a lot of work.

Which code is responsible for the billing house number?

**Comment by ZIPITRO** [comment]
Works only good when the address check of the poscode module is used, does not work anymore when you have a third party module in use for postcode checks.
Please improve third party compatibility.

**Comment by ZIPITRO** [comment]
Good morning Jeffrey,

We fixed it,

if it ain't broke, don't fix it
