### ISSUE TITLE
500 error on mass shipment creation

### ISSUE THREAD

**Issue by henk-hypershop** [tig-nl/postnl-magento2#32]
Selecting a few orders to create PostNL shipment results in PHP 500 error:

Module version: 1.2.0 and previous versiosn.

--------

[13-Nov-2017 19:39:48 UTC] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to TIG\PostNL\Webservices\Endpoints\SentDate::setParameters() must implement interface TIG\PostNL\Api\Data\OrderInterface, null given, called in /var/domains/***-staging.***.nl/application/vendor/tig/postnl-magento2/Service/Handler/SentDateHandler.php on line 82 and defined in /var/domains/***-staging.***.nl/application/vendor/tig/postnl-magento2/Webservices/Endpoints/SentDate.php:127
Stack trace:
#0 /var/domains/***-staging.***.nl/application/vendor/tig/postnl-magento2/Service/Handler/SentDateHandler.php(82): TIG\PostNL\Webservices\Endpoints\SentDate->setParameters(Object(Magento\Sales\Model\Order\Address), '1', NULL)
#1 /var/domains/***-staging.***.nl/application/vendor/tig/postnl-magento2/Observer/TIGPostNLShipmentSaveAfter/CreatePostNLShipment.php(154): TIG\PostNL\Service\Handler\SentDateHandler->get(Object(Magento\Sales\Model\Order\Shipment))
#2 /var/domains/***-staging.***.nl/application in /var/domains/***-staging.***.nl/application/vendor/tig/postnl-magento2/Webservices/Endpoints/SentDate.php on line 127

**Comment by tig-michielgerritsen** [comment]
Hello @henk-hypershop,

Could you please provide us with a test scenario on how to reproduce this error?

**Comment by henk-hypershop** [comment]
I think you need to have SSH and backend access to our staging in order to reproduce this error. Please let me know how i can provide these to you.

**Comment by henk-hypershop** [comment]
The error is thrown in the following situation:

1. I place an order with an account.
2. Go to checkout and place order
3. Pay order and return to success page
4. Go into backend, order has shipping date and type
5. Place another order with same account (same steps)
6. Go into backend. First order has no shipping date and type anymore. New order does have shipping date and type.

Please look at attachment.
![screen shot 2017-11-15 at 13 28 32](https://user-images.githubusercontent.com/24226635/32836086-ed19c040-ca08-11e7-9265-d52cde6be169.png)

**Comment by SilvanLaroo** [comment]
@henk-hypershop we're facing the same issue in combination with MultiSafepay, did you find a solution to make this work with MultiSafepay?

**Comment by henk-hypershop** [comment]
No, not yet. This issue had been chasing us for some time. Seems that MSP does not work well on M2 with PostNL. Therefore we are considering right now to switch to Buckaroo, also developed by TIG.
