### ISSUE TITLE
[BUG] Amasty OSC quantity update in checkout does not switch between parcel & letter box

### ISSUE THREAD

**Issue by jdereus87** [tig-nl/postnl-magento2#320]
**To Reproduce**
1. Setup a product for letter box and a max quantity for letter box to 2 (or smth). 
2. Put 1 or 2 of that item in your cart and go to the checkout.
3. In the checkout, raise the quantity to 3 or higher

**Expected result**
The Post NL picks up on the quantity and switches to parcel. 

**Actual result**
The shipment stays a letterbox.
It also does not switch in instances when you go from parcel back to letterbox (< 2) or when you remove a product that caused it to be a parcel. 

**Workaround**
The workaround would be for the customer to adjust the quantity, leave the checkout, enter the checkout. However customers don't know / should not be expected to know this workaround. 

** Please complete the following information**
- Magento 2.4.4.
- PHP 8.1
- TIG PostNL version: 1.12.2
- Amasty OSC 4.1.2

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jdereus87 ,

At this moment, PostNL is not compatible with One step checkouts. I suggest you contact PostNL at digitaleklantsupport@postnl.nl to ask them to support this one step checkout so we can make it compatible. 

Have a great day,
Jeffrey

**Comment by jdereus87** [comment]
Hello Jeffrey,

Check. You can close this one.
