### ISSUE TITLE
[BUG] Quote phone number not correctly set when selecting pickup point 

### ISSUE THREAD

**Issue by jdereus87** [tig-nl/postnl-magento2#323]
**To Reproduce**
In the native checkout, place item in cart and go to the checkout. Fill in all credentials except phone number. Select a pickup point from the post nl dropdown. Pressing next step requires you to still enter the phone number. Fill it in and go to the next step.

With the native bank transfer payment you now get an error: an error occured on the server (stack trace below) and the order cant be submitted.
With multisafepay you get a full blown MYSQL error, which I will explain below.

I ran this through xdebug. It seems the quotePgAddress does not pickup the phone number after a pickup point has already been selected. This leads to telephone field being empty in the quotePgAddress.  As seen in the stacktrace below, it will eventually get to the native magento function setTelephone, which has an unchecked trim function. In php8 trim functions can't have NULL as an argument.

The MYSQL error I mentioned earlier is due to the postnl order actually creating its order, but the magento order not being created. This creates a integrity constraint violation since no there is no sales_order entity id for it to connect to. 

Stack trace:
[2022-07-13T09:17:18.582828+00:00] main.CRITICAL: Saving order 000133797 failed: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /data/web/magento2/vendor/magento/module-sales/Model/Order/Address.php on line 604 [] []
[2022-07-13T09:17:18.593213+00:00] main.CRITICAL: Exception: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /data/web/magento2/vendor/magento/module-sales/Model/Order/Address.php on line 604 in /data/web/magento2/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler()
#1 /data/web/magento2/vendor/magento/module-sales/Model/Order/Address.php(604): trim()
#2 /data/web/magento2/vendor/tig/postnl-magento2/Observer/SalesOrderSaveAfter/AddressToOrder.php(234): Magento\Sales\Model\Order\Address->setTelephone()
#3 /data/web/magento2/vendor/tig/postnl-magento2/Observer/SalesOrderSaveAfter/AddressToOrder.php(129): TIG\PostNL\Observer\SalesOrderSaveAfter\AddressToOrder->createOrderAddress()
#4 /data/web/magento2/vendor/tig/postnl-magento2/Observer/SalesOrderSaveAfter/AddressToOrder.php(106): TIG\PostNL\Observer\SalesOrderSaveAfter\AddressToOrder->addPgAddress()
#5 /data/web/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): TIG\PostNL\Observer\SalesOrderSaveAfter\AddressToOrder->execute()

**Expected result**
No errors when submitting the order

**Actual result**
Errors in the checkout. Which one depends on the payment method being used.

**Workaround**
The simplest workaround seems to patch the vendor/magento/module-sales/Model/Order/Address.php setTelephone function with an if statement on the trim function. 
However: I am not sure what the functional consequences are to the telephone number not being set properly for the quote and pgAddress?

** Please complete the following information**
- Magento 2.4.4.
- PHP 8.1
- TIG PostNL version: 1.12.2

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jdereus87 ,

I am able to reproduce this issue, I will place this on our backlog. Thank you for submitting this issue and thinking along! 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jdereus87 ,

Maybe you have already seen the update, we released a new version of the extension with the fix included. 
If you come across other problems, you can always contact us.

Have a great day,
Jeffrey
