### ISSUE TITLE
[BUG] API Credentials validation issue for multisite

### ISSUE THREAD

**Issue by gjportegies** [tig-nl/postnl-magento2#324]
**To Reproduce**
1. Setup a Magento 2 multi site environment.
2. Fill in different API-keys for every site.
3. Validate the API-credentials.
4. Validation fails.

**Expected result**
The validation should be successful for every store.

**Actual result**
Our customer has a multisite setup. For every store they have different PostNL-credentials (API-key, Customer code, etc.) On the default settings the validation of the API Credentials are successful. When switching stores/sites in the Admin and validate the API Credentials for that particular store it fails. 

**Extra information**
I've done some debugging and found that in the `Controller/Adminhtml/Config/Validate/ApiCredentials.php` file we're always getting the default store ID in the execute method.

```
    public function execute()
    {
        ... 

        $this->soap->updateApiKey($store->getId()); // $store->getId() always returns the default store ID

        ...
    }
```

**Workaround**
None

** Please complete the following information**
- Magento version: 2.4.3
- PHP version: 7.4.28
- TIG PostNL version: 1.12.2

**Comment by tig-jeffreybranderhorst** [comment]
Hi @gjportegies ,

Thank you for submitting this and contacting us. I can reproduce this, so I have placed it on our backlog, and we are going to fix this bug. 

Have a great day,
Jeffrey

**Comment by gjportegies** [comment]
Hi @tig-jeffreybranderhorst,

Is there any indication of a time frame on when this will be fixed?

Thanks in advance.

Have a great day,
Guus

**Comment by tig-jeffreybranderhorst** [comment]
Hi @gjportegies ,

Unfortunately, I don't have an estimation. I did just update the issue to ask if this can be fixed soon. PostNL decides which bug have priority, but I will try to get this bug fixed soon! 

Have a great day,
Jeffrey

**Comment by gjportegies** [comment]
Hi @tig-jeffreybranderhorst,

Thanks for your follow-up and effort to get this fixed.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @gjportegies ,

And if it is going to be possible, I will send you a Patch sooner than the release. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @gjportegies ,

This should be fixed in the newest version of the extension. If you notice anything else, please inform us! 
Thanks again for submitting this issue. 

Have a great day,
Jeffrey
