### ISSUE TITLE
[QUESTION] Obtain pdf through REST API

### ISSUE THREAD

**Issue by memen45** [tig-nl/postnl-magento2#326]
Is it possible to obtain a PDF file containing the shipping label (and packing slip) through a rest API endpoint?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @memen45 ,

I have internally talked about your question and through the API this is not possible, in the Magento backend it is an option to add the PostNL label to the packing slip. Through the API these are 2 different calls, it will not be merged into 1 PDF. 

Have a great day,
Jeffrey

**Comment by memen45** [comment]
Thanks for your help!

> Through the API these are 2 different calls, it will not be merged into 1 PDF.

Which API calls can be used for this?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @memen45 ,

I misunderstood, the packingslip as pdf is not available through API.  It is the magento shipment label. 
You can use the follow calls for that. 
PostNL: GET /V1/postnl/shipments/label/{id}
Magento:  GET /V1/shipment/{id}/label

Hopefully I have informed you enough.

Have a nice day,
Jeffrey

**Comment by memen45** [comment]
Yes, thanks a lot! I was able to retrieve the postnl shipping label. The second endpoint (`Magento: GET /V1/shipment/{id}/label`) returns an empty string on my backend every time. Not sure why or what label I would expect there.

Thanks again for your help!
