### ISSUE TITLE
[BUG] Warning messages about self-closing elements in sticky.html

### ISSUE THREAD

**Issue by Epo123** [tig-nl/postnl-magento2#330]
**To Reproduce**
1. Go to 'Magento backend, Sales > Orders'
2. Open developer console in browser
3. See warning message about 'HTML tags must be properly nested and closed:'

**Expected result**
No warnings

**Actual result**
A warning about view/base/web/template/grid/sticky/sticky.html containing self-closing html tags

**Workaround**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/5468632/190979362-f31669eb-1c20-413e-a7c7-aa336d8dc1fb.png)

** Please complete the following information**
- Magento version: 2.4.4-p1
- PHP version: 7.4
- TIG PostNL version: 1.12.3

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Epo123 ,

Thank you for bringing this to our attention, we are going to change this and add the closing tags. Thank you for thinking along, this will be placed on our backlog. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Epo123 ,

This should be fixed in our newest version of the extension. 
If you come across something else, don't hesitate to message us. 

Have a great day,
Jeffrey
