### ISSUE TITLE
Letterbox packages outside of NL

### ISSUE THREAD

**Issue by jdereus87** [tig-nl/postnl-magento2#333]
**Question**
A client is experiencing that the automatic assignement of letterbox packages only works for shipments in NL, but not for BE/EU shipments. Is this correct behavior of the plugin or are we missing a configuration somewhere?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jdereus87 ,

This is correct, it is only available in the Netherlands. 

Have a nice day,
Jeffrey
