### ISSUE TITLE
[QUESTION] 1.12.4 not available on packagist

### ISSUE THREAD

**Issue by DuckThom** [tig-nl/postnl-magento2#335]
**Question**
I noticed a new 1.12.4 release was made yesterday, however, it's not showing up on Packagist. 

It looks like the version field in the composer.json file still needs to be updated as that's still on 1.12.3 and this field overrules versions in git tags. If this field is omitted, the version is automatically parsed from branch names and tags.

https://github.com/tig-nl/postnl-magento2/blob/0f948b0867d81c7935fa62c77f2dbc84d90c00b2/composer.json#L14

**Comment by tig-jeffreybranderhorst** [comment]
Hi @DuckThom ,

Thank you for your message. We are looking into this! 

Have a great day,
Jeffrey

**Comment by DuckThom** [comment]
I see a new commit has been pushed and the version is now visible on Packagist, thanks!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @DuckThom ,

We indeed fixed this, seems like you already discovered it! 
Thanks again for submitting this issue.

Have a great day,
Jeffrey
