### ISSUE TITLE
Implement T&T link in customer account

### ISSUE THREAD

**Issue by JeroenVanLeusden** [tig-nl/postnl-magento2#34]
Would be nice to see a Track&Trace link in the customer account section (http://cloud.h-o.nl/ntHW) and not only in the shipment emails.

**Comment by tig-jeffreybranderhorst** [comment]
Hello JeroenVanLeusden,

That is a great idea, I made an improvement issue with this idea. 
You can keep track of it via https://jira.tig.nl/projects/POSTNLM2/issues/POSTNLM2-412
Hopefully, I have informed you enough this way.

Sincerely,
Jeffrey Branderhorst

**Comment by tig-jeffreybranderhorst** [comment]
Hello JeroenVanLeusden,

My colleague just told me this is a standard Magento option. That it just need to be turned on. And the track and trace will only appear when the shipment is "voorgemeld" and the track and trace is active.

Kind regards,
Jeffrey Branderhorst
