### ISSUE TITLE
[BUG] not proceeding from status "processing" to status "complete".

### ISSUE THREAD

**Issue by DjangoZeelig** [tig-nl/postnl-magento2#342]
**To Reproduce**
1. Go to 'Sales-orders'
2. Select order with status: "processing".
3. Click on actions: PostNL create shipment.
4. See that the order is being labeled as shipped. But status remains in "processing".

**Expected result**
Expectation would be that the status would be updated to "complete".

**Actual result**
Status remains in: "processing".

**Workaround**
None

**Screenshots**

** Please complete the following information**
- Magento version: 2.4.2
- PHP version: 7.3.
- TIG PostNL version: 1.10

**Comment by tig-jeffreybranderhorst** [comment]
Hi @DjangoZeelig ,

The order supposed to go to completed after the order has a shipment and an invoice. The order that stays in processing does this order have a paid invoice? 

Have a great day,
Jeffrey

**Comment by DjangoZeelig** [comment]
Hi,
This order has a paid invoice. 

I navigate to Sales -> Orders -> "the specific order" -> Order View -> Shipments. 
The items in the orders are being listed in "Items Shipped"
I navigate to Sales -> Orders -> "the specific order" -> Order View -> Information.
In "Items Ordered", the ordered items are being listed as Ordered, Invoiced, but not as "paid".

At the bottom page of this page there is a summary, 
In the summary, the payment is being labeled as completed.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @DjangoZeelig ,

That is strange, the moment the order has a shipment and paid invoice it should go to complete. We are not aware of any issues with this, and were also not able to reproduce it in our test environments. Could you contact support via digitaleklantsupport@postnl.nl to investigate this further on your environment.

Have a great day,
Jeffrey

**Comment by DjangoZeelig** [comment]
This issue couldn't be reproduced anymore in live environment. Customer did find an effective work-around for existing orders which seemed to be effected with this issue. This ticket can be closed.
