### ISSUE TITLE
In latest version the new attr. tig_postnl_smart_return_email causing failures

### ISSUE THREAD

**Issue by richardreen** [tig-nl/postnl-magento2#343]
After upgrade  to module 1.12.5 and clicking in the shipments grid on the new column. tig_postnl_smart_return_email the grid screen is not visible anymore (is now a blank and the poppup screen is saying "Something went wrong"

In the log the following error message is shown:

Next Zend_Db_Statement_Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tig_postnl_smart_return_email' in 'order clause', query was: SELECT `main_table`.* FROM `sales_shipment_grid` AS `main_table` ORDER BY tig_postnl_smart_return_email ASC
 LIMIT 50 in /home/u58658p55525/domains/4youwear.nl/public_html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:109

This happens also in the order grid when clicking on the new column. The grid screen is also blank and the log mentioned:

Next Zend_Db_Statement_Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tig_postnl_smart_return_email' in 'order clause', query was: SELECT `main_table`.*, `braintree_transaction_details`.`transaction_source`, `swissup_deliverydate`.`date` AS `delivery_date`, `swissup_deliverydate`.`timerange` AS `delivery_time` FROM `sales_order_grid` AS `main_table`
 LEFT JOIN `braintree_transaction_details` ON braintree_transaction_details.order_id = main_table.entity_id
 LEFT JOIN `swissup_deliverydate` ON swissup_deliverydate.order_id = main_table.entity_id ORDER BY tig_postnl_smart_return_email ASC
 LIMIT 100 in /home/u58658p55525/domains/4youwear.nl/public_html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:109
Stack trace:

After this the order grid and shipment grid can not be viewed anymore because of the persistent error!!!

** Please complete the following information**
- Magento version: 2.4.5
- PHP version: 7.4.28
- TIG PostNL version: 1.12.5

**Comment by tig-jeffreybranderhorst** [comment]
Hi @richardreen ,

Thank you for submitting this issue, I have placed it on our backlog. So we can fix this issue in an upcoming version. If your order grid is still loading, you could access your database and find the query in the table ui_bookmark for your user. If you remove this query it should go back to default.   Before you do any changes in the database please backup the table to be sure. 

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment]
Hi @richardreen,

Thanks again for submitting the issue. We added a fix for this in the latest version of the plugin v1.12.6

I will close this issue.

Have a nice day!

Vincent
