### ISSUE TITLE
[BUG] Enabling the option 

### ISSUE THREAD

**Issue by pascalexperius** [tig-nl/postnl-magento2#346]
**To Reproduce**

**Expected result**

**Actual result**
Describe the actual result

**Workaround**
Describe the temporarily workaround or if none exists write "None"

**Screenshots**

** Please complete the following information**
- Magento version: [e.g. Magento 2.3.1]
- PHP version: [e.g. 7.2.0]
- TIG PostNL version: [e.g. 1.8.1]

**Comment by tig-jeffreybranderhorst** [comment]
Hi @pascalexperius ,

Could you fill in our bug template, so we can see the reproduction steps and try to reproduce this? At this moment only the template has been sent and no additional information.  I guess this was an accident. So I will close this issue, if you found a bug you can fill out the template, so we can reproduce the bug. 

Have a great day,
Jeffrey
