### ISSUE TITLE
[QUESTION] Do you have an version thats compatible with the latest Amasty one step checkout?

### ISSUE THREAD

**Issue by khoang95** [tig-nl/postnl-magento2#349]
**Question**
Hi, we are using the postNL extension in combination with amasty one step checkout. We updated both extension and see that the one step checkout is not compatible with the postNL extension. Amasty changed the one step checkout module in the latest version. Instead of one module they split this in multiple modules. Because of this the postNL extension is not compatible anymore.

Do you guys already have a fix for this? If not, when do you plan to make the postnl compatible with the latest amasty one step checkout ?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @khoang95 ,

The PostNL extension does not support any other third party extensions.  You can contact PostNL via digitaleklantsupport@postnl.nl to ask them to add support for the one step checkout, but at this moment PostNL decided to not support any other extensions. 

Have a great day,
Jeffrey

**Comment by khoang95** [comment]
@tig-jeffreybranderhorst , thanks for the information. Could you maybe check if this is already on your backlog? I already contacted digitaleklantsupport@postnl.nl](mailto:digitaleklantsupport@postnl.nl.
