### ISSUE TITLE
[FEATURE] Dangerous goods option for packages

### ISSUE THREAD

**Issue by cslagboom** [tig-nl/postnl-magento2#351]
**Please rephrase the following line:**

As a company who sells a lot of dangerous goods I'd like the option of a checkbox to indicate if the package contains dangerous goods. Right now we are unable to use the PostNL plug-in for 80% of our orders because the option is not included. 
If the send the packages with the Magento plug-in we are risking a fine because the package isn't labeled as a dangerous goods package. 

**Suggestions and background**

It would be best if the option of dangerous goods is implemented somewhere just before creating the shipment, because then the order is packed in our warehouse and we know what is inside the package.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @cslagboom ,

Thank you for this feature request, I will place this on our backlog and together with PostNL we will look into this. The more product option the better, thank you for thinking along and making the extension better! 

Have a great day,
Jeffrey
