### ISSUE TITLE
[BUG] A zero order while creating a new customer during checkout causes an exception

### ISSUE THREAD

**Issue by Hnto** [tig-nl/postnl-magento2#354]
**To Reproduce**
1. Add a free product to shopping cart
2. Make sure the shipping costs are zero as well
3. Choose an email that is not available in the shop and click on "Create new account"
4. Choose for PostNL shipping
5. You don't have any payment methods, which is fine because it's a free order
6. Click on "Pay" or whatever the button is to finalize the order in your shop

**Expected result**
A success page after completing the order

**Actual result**
No entity with quoteId = 59....

**Workaround**
No

**Screenshots**
![Scherm­afbeelding 2022-12-28 om 15 55 03](https://user-images.githubusercontent.com/6788268/209830663-10543ab3-0a9c-4d9f-8b87-f2a0c8a98a33.png)

** Please complete the following information**
- Magento version: enterprise 2.4.5
- PHP version: 8.1 (also used 8.0)
- TIG PostNL version: 1.12.3 and 1.12.6.1

** Extra info
All other shipping methods work. The issue only applies when using the "create customer" during checkout in combination with a free order and a PostNL shipping method.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Hnto ,

I have tried to reproduce this, but I cannot reproduce this, we finish the orders without any problems or errorrs.  It could happen if you are using a non default checkout and that there is a conflict. Could you send a email to digitaleklantsupport@postnl.nl for further support. Then we can test this on your system. 

Have a great day,
Jeffrey
