### ISSUE TITLE
[BUG] Exception hit when adding new Matrix rates in production mode

### ISSUE THREAD

**Issue by ThomasMW** [tig-nl/postnl-magento2#356]
I'm running into the issue where I cannot add new Matrix rates using the new Matrix rate grid. In production mode I get a blank screen with the text 'An error has happened during application run. See exception log for details.'. No error message is logged however. When I switch Magento into developer mode the functionality works and I can add a new Matrix rate.

Any help would be appreciated.

**To Reproduce**
1. Go to PostNL in main menu -> Matrix Rates - Add new matrix rate

**Expected result**
To see the page to add a new Matrix rate

**Actual result**
Blank screen with the message 'An error has happened during application run. See exception log for details.'. No actual error message is logged in the exception log.

**Workaround**
Set Magento in Developer mode, then you can access the page correctly without any issues.

** Please complete the following information**
- Magento version: 2.4.2-p2
- PHP version: 7.4
- TIG PostNL version: 1.12.5

**Comment by tig-vincentthart** [comment]
Hi @ThomasMW 

are you still able to add new lines using the csv upload? If so, could you share your current csv so we can see if we can reproduce the issue you encounter.

Greetings

Vincent

**Comment by ThomasMW** [comment]
Hi @tig-vincentthart 

I can in fact still add rates using the CSV upload. The new rate is correctly shown in the Matrix rates grid after upload.

This is the current [Matrix Rates CSV](https://github.com/tig-nl/postnl-magento2/files/10377478/matrixrate.csv).

**Comment by tig-vincentthart** [comment]
Ho @ThomasMW 

We were able to reproduce the issue and found a solution for it which we will include in the next release.

Thank you for bringing this to our attention.

Greetings

Vincent

**Comment by tig-vincentthart** [comment]
Hi @ThomasMW 

We have released version v1.12.7 which includes a fix for the issue you encountered.

Greetings,

Vincent

**Comment by treeofinformation** [comment]
Hi @tig-vincentthart 

Thank you for the update. I'll test it out today and report back.

**Comment by ThomasMW** [comment]
Hi @tig-vincentthart 

Thank your for the update. I updated and tested the new release and everything seems to work perfectly, cheers!
