### ISSUE TITLE
Cart price rule with free shipping is not working for Post NL matrix (price vs destination) shipping method

### ISSUE THREAD

**Issue by erikbakker** [tig-nl/postnl-magento2#357]
**Question**
Cart price rule with free shipping is not working for Post NL matrix (price vs destination) shipping method, this rule works fine with the built-in table rates (price vs destination) method. Is this a known issue?

Magento ver. 2.4.5
PHP version: 8.1
TIG PostNL version: 1.12.3

**Comment by tig-vincentthart** [comment]
Hi @erikbakker 

I was able to reproduce this situation and I will create a backlog item for it.

Thank yo for sharing this with us.

**Comment by tig-vincentthart** [comment]
Hi @erikbakker,

We have included a fix for this within the latest release.

Have a nice day!

Vincent
