### ISSUE TITLE
Delivery options

### ISSUE THREAD

**Issue by lyusya-nnn** [tig-nl/postnl-magento2#38]
It is not possible to select delivery options on checkout.

OS - macOS High Sierra, v. 10.13
browser - chrome v. 62.0.3202.94

To replicate the problem:
1.Add product to cart
2. Go to checkout, login, use your existing address

Expected results:
It is possible to select any delivery option

Actual result:
There is loading image shown on delivery options table, can select part of options:
![postnl](https://user-images.githubusercontent.com/8502721/33931807-d992187c-dff9-11e7-9239-719a222a8c3b.png)

And there is js error:
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in O
    at isArrayLike (jquery.min.js:39)
    at Function.each (jquery.min.js:28)
    at new <anonymous> (Location.min.js:1)
    at Pickup.min.js:7
    at Object.arrayMap (../knockoutjs/knockout.min.js:26)
    at UiClass.<anonymous> (Pickup.min.js:7)
    at fire (jquery.min.js:212)
    at Object.fireWith [as resolveWith] (jquery.min.js:218)
    at done (jquery.min.js:628)
    at XMLHttpRequest.callback (jquery.min.js:655)

**Comment by tig-jaspersmits** [comment]
Hi lyusya-nnn,

The error doesn't seem to be related to PostNL. But what i would recommend is that you contact PostNL about this and explain the problem you are experiencing. If they conclude it is related to the extension they will forward the problem to us and then we can investigate if for you.

You can contact PostNL by e-mail on citservicedesk@postnl.nl or call them on phone number 088-2255652. 

With kind regards,

Jasper
TIG

**Comment by lyusya-nnn** [comment]
Hi,
How is that possible that it is not related with PostNL extension if there are errors in TIG_PostNL/js/Renderer/DeliveryOptions/Pickup.min.js and TIG_PostNL/js/Models/Location.min.js files?

**Comment by lyusya-nnn** [comment]
![afrekenen](https://user-images.githubusercontent.com/8502721/33933782-7d24e9e2-dfff-11e7-938e-83cd99dc4e2e.png)

And try to enter address that doesn't exist. It shows just loading image.

And there is an error
"Check CIFException in the detail section\n\n- 1019: Adres\u00a0is\u00a0onbekend.\n\n<<<< Request XML >>>>\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<env:Envelope xmlns:env=\"http:\/\/www.w3.org\/2003\/05\/soap-envelope\" xmlns:ns1=\"http:\/\/postnl.nl\/cif\/domain\/TimeframeWebService\/\" xmlns:ns2=\"http:\/\/schemas.microsoft.com\/2003\/10\/Serialization\/Arrays\" xmlns:ns3=\"http:\/\/postnl.nl\/cif\/services\/TimeframeWebService\/\">\n  <env:Body>\n    <ns3:GetTimeframes>\n      <ns1:Message>\n        <ns1:MessageID>343fda82b80998737ad91a5570d9db1c<\/ns1:MessageID>\n        <ns1:MessageTimeStamp>13-12-2017 11:15:51<\/ns1:MessageTimeStamp>\n      <\/ns1:Message>\n      <ns1:Timeframe>\n        <ns1:CountryCode>NL<\/ns1:CountryCode>\n        <ns1:EndDate>20-12-2017<\/ns1:EndDate>\n        <ns1:HouseNr>345<\/ns1:HouseNr>\n        <ns1:Options>\n          <ns2:string>Daytime<\/ns2:string>\n          <ns2:string>Evening<\/ns2:string>\n        <\/ns1:Options>\n        <ns1:PostalCode>1000AA<\/ns1:PostalCode>\n        <ns1:StartDate>14-12-2017<\/ns1:StartDate>\n        <ns1:SundaySorting>true<\/ns1:SundaySorting>\n      <\/ns1:Timeframe>\n    <\/ns3:GetTimeframes>\n  <\/env:Body>\n<\/env:Envelope>\n\n\n<<<< Response XML >>>>\n<?xml version=\"1.0\"?>\n<s:Envelope xmlns:a=\"http:\/\/postnl.nl\/cif\/domain\/TimeframeWebService\/\" xmlns:b=\"http:\/\/schemas.microsoft.com\/2003\/10\/Serialization\/Arrays\" xmlns:s=\"http:\/\/schemas.xmlsoap.org\/soap\/envelope\/\">\n   <s:Body>\n      <s:Fault>\n         <faultcode>s:CIF Framework Message Interceptor<\/faultcode>\n         <faultstring xml:lang=\"en-US\">Check CIFException in the detail section<\/faultstring>\n         <detail>\n            <CifException xmlns=\"http:\/\/postnl.nl\/cif\/services\/common\/\" xmlns:i=\"http:\/\/www.w3.org\/2001\/XMLSchema-instance\">\n               <Errors>\n                  <ExceptionData>\n                     <Description i:nil=\"true\"\/>\n                     <ErrorMsg>Adres&#xA0;is&#xA0;onbekend.<\/ErrorMsg>\n                     <ErrorNumber>1019<\/ErrorNumber>\n                  <\/ExceptionData>\n               <\/Errors>\n            <\/CifException>\n         <\/detail>\n      <\/s:Fault>\n   <\/s:Body>\n<\/s:Envelope>\n"

Request URL:https://***/postnl/deliveryoptions/timeframes/
Request Method:POST
Status Code:503 Service Unavailable

**Comment by tig-jaspersmits** [comment]
Hi lyusya-nnn,

I understand. Are you using Magento 1 or 2? And are you using the default checkout or a third party checkout? I would still recommend contacting PostNL about this like mentioned in my previous reaction.

With kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi lyusya-nnn,

I just discussed this with my colleague and he mentioned that this is already on our backlog to be fixed. So i would like to apologize for my incorrect reaction. There is no reason to contact PostNL about this, we are aware of the problem. To keep track of the issue you can follow it trough this link: https://jira.tig.nl/projects/POSTNLM2/issues/POSTNLM2-291

This will be solved in one of our upcoming releases.

With kind regards,

Jasper
TIG

**Comment by lyusya-nnn** [comment]
OK. Thanks!

**Comment by tig-jeffreybranderhorst** [comment]
Hi lyusya-nnn,
This is fixed in our newest version, our newest version right now is 1.3.
Best regards,
Jeffrey
