### ISSUE TITLE
Magento 2.2.2 support

### ISSUE THREAD

**Issue by govereem** [tig-nl/postnl-magento2#39]
Please update composer:
Composer "magento/framework": ">=100.1.0,<=100.1.10|101.0.0|101.0.1",
Not allowing to install 101.0.2 framework.

Does this module work on Magento 2.2.2?

**Comment by tig-rikjonkmans** [comment]
Hi @govereem,

This module will support Magento 2.2.2 in the upcoming release. Which will come at the end of this week or at most begin of next week. We also have a develop branch which can be used in the meantime. Use dev-develop in your composer require.

**Comment by tig-rikjonkmans** [comment]
Hi @govereem,

We have just released V1.3.0 which is compatible with Magento 100.1.11 and 101.0.2.

**Comment by govereem** [comment]
Thank you for fixing this issue and the quick response.
