### ISSUE TITLE
Migratie van module van Magento1 naar Magento2

### ISSUE THREAD

**Issue by schaapkabap** [tig-nl/postnl-magento2#4]
Ik heb een migratie uitgevoerd en kreeg veel foutmeldingen te zien die van deze module af kwamen.
Is er ondersteuning om de data te migreren van Magento1 naar Magento2? Of een andere manier om de data van de Magento1 module naar de Magento2 module te migreren?

**Comment by tig-jaspersmits** [comment]
Good morning,

My apologies for this very late reaction. You can take a look at this support article if you still need help with this: https://confluence.tig.nl/display/TIGSD/Migreren+van+Magento+1+naar+2+i.c.m.+de+PostNL+extensie

Jasper
