### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by LexKoomen** [tig-nl/postnl-magento2#42]
Hoi,

Wij gebruiken TIG PostNL in combinatie met OneStepCheckout https://www.onestepcheckout.com/

Wat wij merken is dat wanneer er extra fee's worden toegevoegd aan bijvoorbeeld avondbezorgingen binnen de PostNL Module dat deze niet via Ajax worden geupdatet in de sidebar bij de verzendkosten.

![schermafbeelding 2018-02-15 om 10 41 53](https://user-images.githubusercontent.com/11296575/36250024-e3fb1f5a-123c-11e8-9beb-dff9cd1978f4.png)

Pas nadat je de pagina reload of gaat afrekenen merk je dat je de extra fee moet betalen. 
Komt er ondersteuning voor deze fee's in combinatie met die module?

Met vriendelijke groet,

Lex

**Comment by tig-dennisvanderhammen** [comment]
This was discussed between TIG and LexKoomen. The conclusion is that as of 16th of Februari we do not support any third party extensions. iDev OneStepCheckout did release a new version that is compatible with the PostNL Magento 2 extension.
