### ISSUE TITLE
Compatibility with danslo CleanCheckout

### ISSUE THREAD

**Issue by JeroenVanLeusden** [tig-nl/postnl-magento2#43]
We'd like to use [danslo/CleanCheckout](https://github.com/danslo/CleanCheckout). Are there plans to make PostNL compatible? Both modules made changes in `view/frontend/web/template/shipping.html` although the changes in [danslo/CleanCheckout](https://github.com/danslo/CleanCheckout) seem to be minor.

**Comment by tig-jeffreybranderhorst** [comment]
Good morning JeroenVanLeusden,

Until now we don't support any checkout.  This is a feature that will come in the future. 
But I know that that the OneStepCheckout from iDEV is working with the PostNL extension. 
Their website is: https://www.onestepcheckout.com/

Hopefully in informed you enough.

Beste regards,
Jeffrey Branderhorst

**Comment by danslo** [comment]
I just came across this issue by chance. It shouldn't be too hard to make it compatible yourself. Just override that file in your theme by copying over the file from this module (TIG PostNL), as I assume that's where more changes were done.

Then apply the same changes I made in CC. Here's a diff between core magento and my version:
```patch
--- /home/daniel/Code/magento2/app/code/Magento/Checkout/view/frontend/web/template/shipping.html
+++ /home/daniel/Desktop/shipping_cc.html
@@ -32,17 +32,20 @@
         <!-- Inline address form -->
         <render if="isFormInline" args="shippingFormTemplate" />
     </div>
+    <br class="clearfix" />
 </li>
 
-<!--Shipping method template-->
 <li id="opc-shipping_method"
     class="checkout-shipping-method"
-    data-bind="fadeVisible: visible(), blockLoader: isLoading"
+    data-bind="fadeVisible: visible(), blockLoader: !shouldHideShipping() && isLoading"
     role="presentation">
     <div class="checkout-shipping-method">
+
+        <!-- ko ifnot: shouldHideShipping() -->
         <div class="step-title"
              translate="'Shipping Methods'"
              data-role="title" />
+        <!-- /ko -->
 
         <each args="getRegion('before-shipping-method-form')" render="" />
 
@@ -57,7 +60,9 @@
                   submit="setShippingInformation"
                   novalidate="novalidate">
 
+                <!-- ko ifnot: shouldHideShipping() -->
                 <render args="shippingMethodListTemplate"/>
+                <!-- /ko -->
 
                 <div id="onepage-checkout-shipping-method-additional-load">
                     <each args="getRegion('shippingAdditional')" render="" />
```


And unless you really care about hiding shipping methods, you don't even need to apply this patch at all probably.

**Comment by JeroenVanLeusden** [comment]
@danslo We've already made it compatible ourselves. But, if all it does is hiding shipping methods we might remove it again for better maintainability when upgrading. Thanks for the info!

**Comment by danslo** [comment]
If I need to do anything in Clean Checkout to make that compatibility cleaner, let me know!

**Comment by tig-jeffreybranderhorst** [comment]
Hey Danslo,

Today we released a new version of the PostNL extension and this one should be compatible with the checkout! 

Kind regards,
Jeffrey Branderhorst
