### ISSUE TITLE
Compatibility with 2.2.3

### ISSUE THREAD

**Issue by danslo** [tig-nl/postnl-magento2#44]
Magento 2.2.3 just released with some important security updates, this module blocks upgrade to that version. Maybe it's an idea to loosen the requirements of patch version number (allow 2.2.*).

**Comment by tig-jeffreybranderhorst** [comment]
Hello danslo,

We are already testing the extension on the newest patches.  If we tested the extension on the newest version we will update the public branches that they will accept 2.2.3.

I think and I hope we will release the new version today.
