### ISSUE TITLE
Upgrade to Magento 2.2.4 failed because TIG/Postnl extension

### ISSUE THREAD

**Issue by richardreen** [tig-nl/postnl-magento2#48]
Hello,

Tried to upgrade to Magento 2.2.4 but that failed because of Tig/PostNL extension.
Following messages appear after composer upgrade command:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tig/postnl-magento2 v1.3.4 requires magento/framework >=100.1.0,<=100.1.12|>=101.0.0,<=101.0.3 -> satisfiable by magento/framework[101.0.3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12].
    - tig/postnl-magento2 v1.3.2 requires magento/framework >=100.1.0,<=100.1.12|>=101.0.0,<=101.0.3 -> satisfiable by magento/framework[101.0.3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12].
    - tig/postnl-magento2 v1.3.3 requires magento/framework >=100.1.0,<=100.1.12|>=101.0.0,<=101.0.3 -> satisfiable by magento/framework[101.0.3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12].
    - tig/postnl-magento2 v1.3.4 requires magento/framework >=100.1.0,<=100.1.12|>=101.0.0,<=101.0.3 -> satisfiable by magento/framework[101.0.3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12].
    - tig/postnl-magento2 v1.3.0 requires magento/framework >=100.1.0,<=100.1.11|>=101.0.0,<=101.0.2 -> satisfiable by magento/framework[100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2].
    - tig/postnl-magento2 v1.3.1 requires magento/framework >=100.1.0,<=100.1.11|>=101.0.0,<=101.0.2 -> satisfiable by magento/framework[100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2].
    - Can only install one of: magento/framework[101.0.4, 101.0.3].
    - Can only install one of: magento/framework[101.0.4, 101.0.0].
    - Can only install one of: magento/framework[101.0.4, 101.0.1].
    - Can only install one of: magento/framework[101.0.4, 101.0.2].
    - Can only install one of: magento/framework[101.0.4, 101.0.3].
    - Can only install one of: magento/framework[101.0.4, 100.1.0].
    - Can only install one of: magento/framework[101.0.4, 100.1.1].
    - Can only install one of: magento/framework[101.0.4, 100.1.2].
    - Can only install one of: magento/framework[101.0.4, 100.1.3].
    - Can only install one of: magento/framework[101.0.4, 100.1.4].
    - Can only install one of: magento/framework[101.0.4, 100.1.5].
    - Can only install one of: magento/framework[101.0.4, 100.1.6].
    - Can only install one of: magento/framework[101.0.4, 100.1.7].
    - Can only install one of: magento/framework[101.0.4, 100.1.8].
    - Can only install one of: magento/framework[101.0.4, 100.1.9].
    - Can only install one of: magento/framework[101.0.4, 100.1.10].
    - Can only install one of: magento/framework[101.0.4, 100.1.11].
    - Can only install one of: magento/framework[101.0.4, 100.1.12].
    - magento/product-community-edition 2.2.4 requires magento/framework 101.0.4 -> satisfiable by magento/framework[101.0.4].
    - Installation request for magento/product-community-edition 2.2.4 -> satisfiable by magento/product-community-edition[2.2.4].

**Comment by tig-jaspersmits** [comment]
Hi Richard,

We are working on a release which supports 2.2.4. This release is scheduled for this morning. When i have more information about this i will let you know.

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi Richard,

Version 1.3.5 has been released. When you install this version you should be able to update to 2.2.4. Instructions on how to update the extension can be found here: https://confluence.tig.nl/x/3oSC

Kind regards,

Jasper
TIG
