### ISSUE TITLE
Feature: Select Delivery / Pickup as default selection

### ISSUE THREAD

**Issue by JeroenVanLeusden** [tig-nl/postnl-magento2#49]
Possibility to select `Delivery` / `Pickup` as default selection (http://cloud.h-o.nl/rQzu) in checkout. Also add validation that either on should be selected so it can't be empty.

**Comment by tig-jaspersmits** [comment]
Hi Jeroen,

Sorry for this delayed response. Thank you for your feature request, but because of technical reasons we won't follow trough on adding this to the extension.

Kind regards,

Jasper
TIG
