### ISSUE TITLE
Extension breaks sales order grid

### ISSUE THREAD

**Issue by SilvanLaroo** [tig-nl/postnl-magento2#5]
Hi TIG,

We've installed your extension, but it breaks the sales order grid in some cases.

Steps to reproduce
--
1. On Magento 2.1.7
2. Open Sales Order grid in admin
3. Type in a keyword in the shown search bar (left to the filters button)

Expected result
--
1. The sales order grid with the keyword as filter active

Actual result
--
1. A pop-up with the messages 'Attention Something went wrong'
2. I can see in my console that there is an error message shown: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')))))' at line 1, query was: SELECT COUNT(*) FROM `tig_postnl_shipment` AS `main_table` WHERE ((((()))))

EDIT
---
This error is also shown if I activate filters.

**Comment by tig-berendlantink** [comment]
Hi Sil,

Thank you for the clear description!
We gonna check this issue and keep you posted.

**Comment by tig-berendlantink** [comment]
Hi Sil,

Bug confirmed!
Internal issue: POSTNLM2-242

This will be fixed in a new release.

**Comment by SilvanLaroo** [comment]
Hi Berend,

Thanks for the update. Can you give an estimation when this new version will be released, or is there a quick-fix in the meantime?

**Comment by tig-berendlantink** [comment]
Hi Sil, 

For now I can't give you an estimation, but we develop active on this extension so it won't be long.

**Comment by magefan** [comment]
Have the same issue.

**Comment by magefan** [comment]
@SilvanLaroo , can you try to use this fix 4010f6a ?

**Comment by SilvanLaroo** [comment]
@magefan thanks, yes this does fix the issue for me.

**Comment by tig-vincentthart** [comment]
@SilvanLaroo 

I see @magefan already helped you solve this issue for you. 

Within our latest release [v1.1.4-alpha](https://github.com/tig-nl/postnl-magento2/releases/tag/v1.1.4-alpha) we have also solved this issue. Thank you for bringing this issue to our attention.
