### ISSUE TITLE
Getting logged out when I am trying to open tabs

### ISSUE THREAD

**Issue by robbertstevens** [tig-nl/postnl-magento2#51]
When I open tabs  Configuration > Sales >postnl I get logged out and this is shown. 

![image](https://user-images.githubusercontent.com/726557/40649445-3be5afa6-6331-11e8-8976-6a8a03f02e97.png)

Anyone know what causes this?

I am using Magento 2.2.2 and the module version 1.4.0

**Comment by tig-jaspersmits** [comment]
Hi Robbert,

Thank you for your question. Unfortunate to hear that you are experiencing this problem. Just tried to reproduce this, but i don't see this problem happening. Maybe it's some sort of conflict with another extension. If you want you can send your Magento login information to sd@tig.nl, then we can take a look at it.

Kind regards,

Jasper
TIG

**Comment by robbertstevens** [comment]
@tig-jaspersmits probably some weird magento caching thing, cuz now i can just select options and save it.
