### ISSUE TITLE
Extension gives problem with magento 2.2.5

### ISSUE THREAD

**Issue by richardreen** [tig-nl/postnl-magento2#56]
Tried to upgrade to magento 2.2.5 but  gvies problems due to tig postnl extension
Following problems are reported

  Problem 1
    - tig/postnl-magento2 1.4.0 requires magento/framework >=100.1.0,<=100.1.13|>=101.0.0,<=101.0.4 -> satisfiable by magento/framework[101.0.4, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc23, 101.0.0-rc30, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12, 101.0.3, 100.1.13].
    - tig/postnl-magento2 1.4.0 requires magento/framework >=100.1.0,<=100.1.13|>=101.0.0,<=101.0.4 -> satisfiable by magento/framework[101.0.4, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc23, 101.0.0-rc30, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12, 101.0.3, 100.1.13].
    - tig/postnl-magento2 1.4.2 requires magento/framework >=100.1.0,<=100.1.13|>=101.0.0,<=101.0.4 -> satisfiable by magento/framework[101.0.4, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc23, 101.0.0-rc30, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12, 101.0.3, 100.1.13].
    - Can only install one of: magento/framework[101.0.5, 101.0.4].
    - Can only install one of: magento/framework[101.0.5, 100.1.0-rc1].
    - Can only install one of: magento/framework[101.0.5, 100.1.0-rc2].
    - Can only install one of: magento/framework[101.0.5, 100.1.0-rc3].
    - Can only install one of: magento/framework[101.0.5, 100.1.0].
    - Can only install one of: magento/framework[101.0.5, 100.1.1].
    - Can only install one of: magento/framework[101.0.5, 100.1.2].
    - Can only install one of: magento/framework[101.0.5, 100.1.3].
    - Can only install one of: magento/framework[101.0.5, 100.1.4].
    - Can only install one of: magento/framework[101.0.5, 100.1.5].
    - Can only install one of: magento/framework[101.0.5, 100.1.6].
    - Can only install one of: magento/framework[101.0.5, 100.1.7].
    - Can only install one of: magento/framework[101.0.5, 100.1.8].
    - Can only install one of: magento/framework[101.0.5, 101.0.0-rc21].
    - Can only install one of: magento/framework[101.0.5, 101.0.0-rc22].
    - Can only install one of: magento/framework[101.0.5, 101.0.0-rc23].
    - Can only install one of: magento/framework[101.0.5, 101.0.0-rc30].
    - Can only install one of: magento/framework[101.0.5, 100.1.9].
    - Can only install one of: magento/framework[101.0.5, 101.0.0].
    - Can only install one of: magento/framework[101.0.5, 101.0.1].
    - Can only install one of: magento/framework[101.0.5, 100.1.10].
    - Can only install one of: magento/framework[101.0.5, 100.1.11].
    - Can only install one of: magento/framework[101.0.5, 101.0.2].
    - Can only install one of: magento/framework[101.0.5, 100.1.12].
    - Can only install one of: magento/framework[101.0.5, 101.0.3].
    - Can only install one of: magento/framework[101.0.5, 100.1.13].
    - Can only install one of: magento/framework[101.0.5, 101.0.4].
    - magento/product-community-edition 2.2.5 requires magento/framework 101.0.5 -> satisfiable by magento/framework[101.0.5].
    - Installation request for magento/product-community-edition 2.2.5 -> satisfiable by magento/product-community-edition[2.2.5].
    - Installation request for tig/postnl-magento2 ^1.4 -> satisfiable by tig/postnl-magento2[1.4.0, 1.4.2].

**Comment by tig-jaspersmits** [comment]
Goodmorning Richard,

Thank you for letting us know. We are aware of this and will test the extension as soon as possible with this new Magento version. When this is fully tested we will release a new version with support for Magento 2.2.5.

Kind regards,

Jasper
TIG

**Comment by tig-jeffreybranderhorst** [comment]
Goodmorning Richard,

We just released an RC version of the extension. The RC version doesn't have any new features, but it does accept the new Magento versions. We are still testing it now but if you already want it you could update your store with the RC version.

Kind regards,
Jeffrey Branderhorst
TIG
