### ISSUE TITLE
Prijs laat 0 zien

### ISSUE THREAD

**Issue by DeLuuk** [tig-nl/postnl-magento2#59]
Hey,

De extensie heeft altijd gewerkt maar sinds kort laat hij alleen maar 0 zien. Dit bedoel ik daarmee:
![screen shot 2018-07-16 at 09 20 22](https://user-images.githubusercontent.com/26225521/42746708-7e0d05b4-88d9-11e8-97f3-00726825687a.png)
En ik heb 3 items in mijn cart die alle 3 een gewicht hebben.

Mijn instelling zijn als volgt
![screen shot 2018-07-16 at 09 21 14](https://user-images.githubusercontent.com/26225521/42746736-9c2d2934-88d9-11e8-964e-0094943e02e8.png)
En de instellingen van PostNL zijn ingevuld als de test gegevens die op jullie website staan. (op v1.4.3)
En nog een paar andere instellingen waar jullie misschien iets aan hebben
![screen shot 2018-07-16 at 09 23 02](https://user-images.githubusercontent.com/26225521/42746803-f37dcfae-88d9-11e8-8aae-41b7b683d025.png)
![screen shot 2018-07-16 at 09 23 18](https://user-images.githubusercontent.com/26225521/42746807-f4eed72a-88d9-11e8-8d37-16e10767c980.png)

Is dit toevallig een bekend probleem of weten jullie misschien wat dit is? Graag hoor ik van jullie.

**Comment by tig-jeffreypeeters** [comment]
Hey DeLuuk,

Could you send us an e-mail at [sd@tig.nl](mailto:sd@tig.nl) with login credentials for your backend? This way we can take a look at your environment and see if we can fix it. Normally these kind of issues go through PostNL but we can make an exception this time.

We try to keep our github issues readable for everyone that uses our extension so could you use english in the future?

Kind regards,

Jeffrey Peeters
TIG

**Comment by DeLuuk** [comment]
Oke I sent an email!
