### ISSUE TITLE
(Always show) delivery options worden niet getoond

### ISSUE THREAD

**Issue by laurens-shopcommerce** [tig-nl/postnl-magento2#63]
### Systeem:
- Magento: 2.2.4
- Module: tig/postnl-magento2 1.4.2

### Omschrijving reporter:
De bezorg opties van PostNL worden alleen getoond op het moment dat een simple een voorraad groter dan 0 heeft. Klant maakt geen gebruik voorraad.
De TIG/PostNL module heeft hier een instelling voor maar deze lijkt genegeerd te worden.
(Sales > PostNL > Shipping options > Stock options > "Always show delivery options" )

**Door ons getest, met standaard magento2 checkout en luma thema**

orders met producten die manage stock op no hebben met voorraad 0 krijgen de "delivery options" niet te zien.

### Technische Reproductie: 
1. Stop een product in je winkelmand die geen managed stock heeft; verder niets in de winkelmand
2. Ga naar de checkout
3. In de console tik in: window.checkoutConfig.shipping.postnl.shippingoptions_active

Verwacht is true als resultaat, maar we krijgen false

**Verder getraced:**

Issue is vermoedelijk
- Instelling hoort op 'backordered' te staan en TIG\PostNL\Service\Quote\CheckIfQuoteItemsCanBackorder::getValue() geeft false waar true verwacht op een product zonder managed stock.

EN/OF
- Instelling hoort op 'in_stock' te staan en TIG\PostNL\Service\Quote\CheckIfQuoteItemsAreInStock::getValue() geeft false waar true verwacht op een product zonder managed stock.

**Comment by tig-jeffreybranderhorst** [comment]
Goodday Laurens,

Something that happens to me alot with this option is that i forget to deselect the "use system defaults". Because because of that selection the stock options switches back to "only in stock products". Is this maybe also happening with you?

Met vriendelijke groet / Kind regards / Mit freundlichen Grüßen / 最好的祝福,

Jeffrey Branderhorst
CUSTOMER CARE SPECIALIST
020 - 21 81 000

**Comment by laurens-shopcommerce** [comment]
No this is not the case that 'use system defaults' is selected.
I hope TIG can also look deeper for resolving this issue as described above.

Kind regards,
Laurens

**Comment by tig-jeffreybranderhorst** [comment]
Hi Laurens,

Ahh okay, we want to investigate it further for you then. Could you mail us at servicedesk@tig.nl then we will going with the investigation of the error. You don't have to type it all again you could just mail us the github issue that would be enough.

Met vriendelijke groet / Kind regards / Mit freundlichen Grüßen / 最好的祝福,

Jeffrey Branderhorst
CUSTOMER CARE SPECIALIST
020 - 21 81 000

**Comment by tig-rikjonkmans** [comment]
@laurens-shopcommerce ,
This issue has been solved within the 1.5.1 release.
