### ISSUE TITLE
Generated track-and-trace URL contains wrong postal code for post office shipments

### ISSUE THREAD

**Issue by kaybeudeker** [tig-nl/postnl-magento2#64]
### Preconditions
- magento/product-community-edition 2.2.2
- tig/postnl-magento2 v1.4.0

### Steps to reproduce
- Frontend: Create an order with a post office shipment
- Backend: Create the shipment (print label + confirm)
- Click the generated track-and-trace URL in the track-and-trace mail and/or the URL in the order grid

### Expected result
- Generated track-and-trace URL should show the track-and-trace information at the PostNL website.

### Actual result
- A page that tells you it couldn't find track-and-trace information for the barcode + postal code combination

### Solution (?)
- Changing the postal code in the one used for the invoice address instead of the one used for the shipping address. Changing this at the URL at the PostNL website returns the expected result

**Comment by tig-jaspersmits** [comment]
Good morning Kay,

Thanks for informing us about this! Just tested your scenario and you are right, the postal code should be the one from the invoice address to make the Track&Trace link work from the backend and mail. I just created a backlog issue for this so my colleagues can work on a solution.

When i have more information available i will let you know!

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi Kay,

There is a fix currently in code review. This will be release in an upcoming new version of the PostNL extension. Please keep in an eye on the release notes (you can also subscribe to that page to receive updates) to see when this new version will be released: https://confluence.tig.nl/x/3YSC

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
p.s. if you want i can subscribe you to the release notes page if you are willing to share your e-mail address.

**Comment by kaybeudeker** [comment]
That would be great; info[at]kaybeudeker.nl

**Comment by tig-jaspersmits** [comment]
Zojuist toegevoegd! Je ontvangt een e-mail zodra de nieuwe release beschikbaar is.
