### ISSUE TITLE
[POSTNL-0252] - There are no valid labels generated. Please check the logs for more information

### ISSUE THREAD

**Issue by maartenv1** [tig-nl/postnl-magento2#7]
Er kunnen geen labels geprint worden. Error [POSTNL-0252] - There are no valid labels generated. 
No information in Log file. The error is also in https://confluence.tig.nl/display/TIGSD/PostNL+Magento+2+meldingen

**Comment by tig-dennisvanderhammen** [comment]
Hoi Maarten,

Wij zijn bekend met dit probleem en de developers zijn druk bezig om dit werkend te krijgen in een volgende versie. Wat ik adviseer is om jezelf als watcher op te nemen op de [release notes](https://confluence.tig.nl/x/3YSC) pagina van de extensie.

Ook is de melding op onze KB ook bijgewerkt [https://confluence.tig.nl/x/AYAVAQ](https://confluence.tig.nl/x/AYAVAQ). Het zou wel mogelijk moeten zijn om labels te printen met een live account.

Mocht het wenselijk zijn dan kan ik ook hier een reminder sturen zodra dit opgelost is.
