### ISSUE TITLE
postnlShipment.getDeliveryDateFormatted() in email template not correct

### ISSUE THREAD

**Issue by kaybeudeker** [tig-nl/postnl-magento2#71]
### Preconditions
- magento/product-community-edition 2.2.6
- tig/postnl-magento2 1.5.1

### Issue
- For orders created via the frontend, the generated value of _postnlShipment.getDeliveryDateFormatted()_ is partly correct; date is correct, time always has the value '02:00:00' (not correct).
- For orders created via the backend the value of _postnlShipment.getDeliveryDateFormatted()_ is the same as the date and time of the created shipment, so not correct at all.

postnlShipment.getDeliveryDateFormatted() isn't mentioned at all [over here](https://confluence.tig.nl/pages/viewpage.action?pageId=8553643)?

**Comment by tig-rikjonkmans** [comment]
Hi @kaybeudeker ,

Thanks for reporting this issue. We are aware of the time which is always 02:00:00, this is always the response from the getDeliveryDate web-service of PostNL. You can change the template by only returning the date, like postnlShipment.getDeliveryDateFormatted('d-m-Y') we will make this default in the upcoming release. 

For the orders created in the backend we need to do some more research, but for what i know is that the deliveryDate web-service is only called when a customer selects an delivery date in the checkout. 
So when creating the order in the backend the delivery_date value in the database will be NULL. And in that case the timezoneInterface of Magento (which we use to format dates) will return the current date. `new \DateTime('now', new \DateTimeZone($timezone));`

I shall contact PostNL to discuss the best solution for this issue.

**Comment by tig-jaspersmits** [comment]
Because of a clean-up action we will close this ticket. The ticket has been on our backlog but has been closed. This indicates that it is either solved or PostNL decided to not give priority to this case.
