### ISSUE TITLE
Verzendmail wordt niet verstuurd als verzending wordt aangemaakt via een mass-action

### ISSUE THREAD

**Issue by JeroenVanLeusden** [tig-nl/postnl-magento2#72]
Wellicht een configuratie toevoegen zodat zelf bepaalt kan worden of deze mails verstuurd moeten worden?

**Comment by tig-dennisvanderhammen** [comment]
Hi @JeroenVanLeusden,

I personally feel like this should be working already, and (note, I could be wrong about this!) I feel like you might have encountered a bug. I'll have discuss this with my colleague to see if this is indeed a bug. I will make a new comment once I have more information for you!

**Comment by PascalBrouwers** [comment]
Any update on this? I would like to be able to use the mass-action too.

**Comment by tig-dennisvanderhammen** [comment]
Hi @JeroenVanLeusden and @PascalBrouwers,
First of all, I'm sorry that I'm a tad late with my response.

I've set up a new environment (PostNL v1.5.1 & Magento 2.2.6) and I didn't manage to reproduce your issue.

I placed two orders. I confirmed one by clicking on the order, creating a shipment and using the "confirm & print label" button. I confirmed the other one by selecting it in the order grid, clicking on "Actions" and using the option "PostNL - Create shipments, print labels & confirm".

After using both these actions, I correctly received two track & trace e-mails in my mailbox.

Could you both tell me more about your environment settings? (PHP version, PostNL version, Magento version etc..)
Are you taking a different approach on trying to send out the e-mails?

I hope to hear from you!

**Comment by PascalBrouwers** [comment]
Apparently we missed a setting "Send Track and Trace email" in the module that blocks the sending of all shipment emails.

**Comment by tig-dennisvanderhammen** [comment]
I'm glad to hear you found the solution. Have a nice day!
