### ISSUE TITLE
[1.5.1][Magento 2.2.6] getShippingMethod on null when massAction includes orders that don't have a PostNL shipping method

### ISSUE THREAD

**Issue by CsSatter** [tig-nl/postnl-magento2#76]
When trying to ship orders through massAction for the following controllers:
`TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsAndPrintPackingSlip`
`TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintPackingSlip`
`TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels`

And an order is not a validPostNL order the following exception is thrown (anonymized file paths):
`Fatal error: Uncaught Error: Call to a member function getShippingAddress() on null in /vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php:138 Stack trace: #0 /vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php(129): TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels->loadLabel(NULL) #1 /vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php(105): TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels->createShipmentsAndLoadLabels() #2 /vendor/magento/framework/App/Action/Action.php(107): TIG\PostNL\Controller\Adminhtml\Order\CreateShipmentsConfirmAndPrintShippingLabels->execute() #3 /vendor/tig/postnl-magento2/Controller/Adminhtml/Order/CreateShipmentsConfirmAndPrintShippingLabels.php on line 138`

This is due to `execute` method in the controller:
`$shipment = $this->createShipment->create($shipment);
$this->loadLabels($shipment);`

This is because `$shipment` in this case has a null value passed to the `loadLabels` method to `getShippingAddress()`, in `TIG\PostNL\Service\Shipment\CreateShipment` the `create` method returns null when the `isValidOrder()` method returns false. `isValidOrder()` in this case returns false due to `TIG\PostNL\Helper\Data:isPostNLOrder()`.
Understandably this method will return true if the shipping method specified for the order has been configured for PostNL shipments as well.

However due to user error being a thing an unsuspecting user can (accidently) come across this exception.

Steps to reproduce error:
1. Create order as customer, use a shipping method not configured for PostNL shipments
2. Try to ship the created order through PostNL

**Comment by tig-jaspersmits** [comment]
Hi @CsSatter,

This looks to be related to this issue: https://github.com/tig-nl/postnl-magento2/issues/75
Correct? We would like to continue communication trough that issue. I will add your description to that issue so it can be used for reference.

Kind regards,

Jasper
TIG
