### ISSUE TITLE
Feature request: add 'ASAP-status' for 'backorder-orders'

### ISSUE THREAD

**Issue by kaybeudeker** [tig-nl/postnl-magento2#77]
The M1-extension showed the selected timeframe (not on the order-grid) for an order when the order could be completely fulfilled from the shop's inventory. When the order did contain backorders, the timeframe wasn't available so you, as a merchant, knew that the order wasn't ready to ship right away.

The M2-extension doesn't show this timeframe so merchants have to check the stock (qty) manually to make sure if an order is ready to ship right away or not.

Maybe it's possible to make an 'ASAP-status' for the order(-grid) so merchant can see this if an order isn't ready for shipping right away, because not all items -in the requested qty- are available in the merchant's inventory.
Currently, orders with a backorder item get the 'today' (under shipment date) status in the order grid, which isn't correct and confusing. The 'ASAP-status' would make things more clear for the merchant.

Thanks in advance ;)

**Comment by tig-jeffreybranderhorst** [comment]
Good morning Kay,

In my opinion it is a nice extra feature, therefore I added it to the Post NL Magento 2 backlog. We will consult this idea with Post NL, they decide the priority of the backlog mostly. Thank you for thinking with us to improve the extension!

You could add yourself to the watch list of this page:  https://confluence.tig.nl/x/3YSC
Then you will get a message when a new release will be released.

Kind regards,
Jeffrey Branderhorst
