### ISSUE TITLE
Compatibility with Magento 2.3

### ISSUE THREAD

**Issue by tig-dennisvanderhammen** [tig-nl/postnl-magento2#78]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [ X ] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [ X ] Feature request (request for a new functionality)
- [ ] Bug report (encountered problems with the TIG PostNL Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *feature request*
- As a merchant I would like to be able to install PostNL on the upcoming Magento 2.3 version in order to stay up-to-date with the latest security patches.

### If the purpose of your issue is about anything else, please describe your issue here
- Magento 2.3 has a lot of changes, especially in the frontend. Magento version 2.3 will most likely break the extension in its current form. Changes will be required to make the extension compatible with the latest version.

**Comment by patvdleer** [comment]
Any clue/indication on when this will be ready?

**Comment by tig-rikjonkmans** [comment]
Hey @patvdleer,

We are currently working on it, also making it compatible with PHP7.2 which requires updates on the fpdi library as well. 

It will be combined with some other features which are currently in testing stage. The date of the release is still unknown and will be determined after the testing stage is completed and accepted by PostNL. 

I will update this issue as soon a indication can be made.

**Comment by tig-rikjonkmans** [comment]
Good news, we are now compatible with Magento 2.3. Version 1.7.0 is just released. 

Please use the following command to update `composer update tig/postnl-magento2 --with-dependencies`
