### ISSUE TITLE
choosing delivery time does not survive page reload 

### ISSUE THREAD

**Issue by speedupmate** [tig-nl/postnl-magento2#8]
when choosing postnl shipping method and selecting delivery options. delivery options choices are not selected after checkout page is reloaded 

and this causes issues in default checkout: 
* price is reflected in quote (totals)  , reflecting options are not selected 
* address changed, shipping methods reloaded, options are reloaded but not selected , wrong price reflected in shipping method area and in totals

causes issues in other checkout methods: 
* when shipping methods  are (or full page is) reloaded , price is reflected in totals , options are not selected 

in m2 checkout is async and shipping methods are set up as observables , any change in this observable causes frontend to re-render or subscribers to evoke actions on changed values and this extension will always load new delivery options over ajax when this happens , not storing or reselecting already selected values results in wrong totals and user has to make choices over and over, Ui -s  seem broken

**Comment by tig-dennisvanderhammen** [comment]
Thank you for your suggestion. I passed your comment on to the developers. To provide our developers with more information I would like to ask at which point you encounter this problem. Generally a normal user will never refresh the page.

I would like to hear from you.

**Comment by speedupmate** [comment]
i encountered this when testing with OneStepCheckout (that can evoke your actions n times (and this was on customer site)  however to simplify this for you i replicated the same issues with default checkout and created this ticket 

this extension takes actions on observables , normal person does not know what observable is I agree but m2 extension developer can't be sure what/when or why something triggers a observable value change so thats why you need persistency here be it a reload, event , observable, navigation etc

**Comment by tig-jaspersmits** [comment]
Good morning,

You can follow our backlog for the PostNL M2 extension over here: https://jira.tig.nl/projects/POSTNLM2/issues

Also keep an eye on our release notes: https://confluence.tig.nl/display/TIGSD/Release+notes+van+de+PostNL+Magento+2+extensie

I would like to thank you for informing about this.

Jasper
