### ISSUE TITLE
Support for Magento 2.2.7

### ISSUE THREAD

**Issue by igorwulff** [tig-nl/postnl-magento2#80]
- [X ] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

---

### Description of your *issue*, suggested solution and other information

Magento released a security update for Magento 2.2.7. Can you create a new release and at least a RC for this as soon as possible?

**Comment by tig-rikjonkmans** [comment]
Hi @igorwulff ,

We released version 1.6.0 a couple of days ago, which supports 2.2.7.

**Comment by PascalBrouwers** [comment]
Had an issue with 2.2.7 too. Using version 1.7.0.
My issue is that Magento\Sales\Model\ResourceModel\GridInterface cannot be used anymore directly. Please change to Magento\Sales\Model\ResourceModel\GridPool

**Comment by tig-rikjonkmans** [comment]
HI @PascalBrouwers ,

Where do you get this error, what steps do you take before Magento shows this ?

Strange thing is that Magento does not tell us anything about not using it directly
https://devdocs.magento.com/guides/v2.2/release-notes/backward-incompatible-changes/

Next to that, i can not reproduce it on version 2.2.7 or 2.3.0.

**Comment by PascalBrouwers** [comment]
Hi Rik,

It only happens in production mode. I found it very strange too.
We upgraded our magento to 2.2.7 and then the error happened.

Changing the class to GridPool and using `refreshByOrderId` fixes it.

**Comment by PascalBrouwers** [comment]
PS. the error is `Cannot instantiate interface Magento\Sales\Model\ResourceModel\GridInterface`

**Comment by tig-rikjonkmans** [comment]
Hi @PascalBrouwers ,
Can you check if you have asynchronous grid indexing enabled ?

In developer mode, you can find this setting in the config -> advanced -> grid settings tab. 
Otherwise you can find it within the database in the table core_config_data -> path = 'dev/grid/async_indexing' 

This setting should be disabled, for a possible workaround.

**Comment by PascalBrouwers** [comment]
This setting is disabled by default. So no, this is not enabled.

**Comment by tig-rikjonkmans** [comment]
Ok, too bad, because that was my last thought, which could possibly have been the problem.
We tried to reproduce this on local and production servers but we did not receive the error. 

Could you try running di:compile ?

**Comment by PascalBrouwers** [comment]
di:compile always runs in production mode ;)

**Comment by PascalBrouwers** [comment]
I checked, no errors during di:compile.

**Comment by PascalBrouwers** [comment]
oh, I figured it out. You can still use the Grid but the argument was missing for TIG\PostNL\Observer\SalesOrderSaveAfter\UpdateOrderGrid
```
    <type name="TIG\PostNL\Observer\SalesOrderSaveAfter\UpdateOrderGrid">
        <arguments>
            <argument name="orderGrid" xsi:type="object">PostNLOrderGridAggregator</argument>
        </arguments>
    </type>
```

**Comment by tig-rikjonkmans** [comment]
Hi @PascalBrouwers ,

Not sure what you mean, which argument was missing ?

**Comment by tig-rikjonkmans** [comment]
That explains a lot ;) Could that also mean issue [84](https://github.com/tig-nl/postnl-magento2/issues/84) is solved ?
