### ISSUE TITLE
Postnl 1.6 upgrade: Base table of view not found "core_config_data"

### ISSUE THREAD

**Issue by sduif** [tig-nl/postnl-magento2#81]
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [X ] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- **Prerequisite**: Use a table prefix in your magento 2 database
- When updating to the 1.6 version of the extension, you'll get an error while executing **bin/magento setup:upgrade**: SQLSTATE[42S02]: Base table or view not found: 1146 Table '<db>.core_config_data' doesn't exist, query was: UPDATE `core_config_data` SET `path`...

### Cause & Solution
- Setup/V160/Data/ConfigurationData.php contains the following code:
```
$setup->getConnection()->update(
                'core_config_data', $data,
                ["path = '$oldPath'"]
            );
```

- When changed to the following it'll properly work when working with a database table prefix:

```
$setup->getConnection()->update(
                $setup->getTable('core_config_data'), $data,
                ["path = '$oldPath'"]
            );
```

**Comment by tig-dennisvanderhammen** [comment]
Hi @sduif,

Thank you for posting your issue. We are already aware of this issue and we have since fixed this in our private repository. This version is currently going through our test phases. We are expecting the upcoming release to be released in the beginning of next year.

**Comment by sduif** [comment]
Great, good to know! Thanks!
