### ISSUE TITLE
Notice: Undefined index during setup:upgrade

### ISSUE THREAD

**Issue by PascalBrouwers** [tig-nl/postnl-magento2#84]
Got the errors on these lines:

https://github.com/tig-nl/postnl-magento2/blob/aa435997c88c326a197ed183057422037b142e7c/Setup/UpgradeSchema.php#L75-L79

https://github.com/tig-nl/postnl-magento2/blob/aa435997c88c326a197ed183057422037b142e7c/Setup/UpgradeData.php#L68

Please fix with an `isset()`

**Comment by tig-dennisvanderhammen** [comment]
Hi @PascalBrouwers, 

The upgradeSchemaObjects are retrieved from the di.xml, in the UpgradeData. If this notice appears, something in the installation is going wrong. Could you try clearing your generated folder and try running the install scripts again?

**Comment by tig-daanvandenbergh** [comment]
As this issue looks abandoned and could not be reproduced, I'm closing this issue.
