### ISSUE TITLE
Cannot create order using guest checkout when billing address is null

### ISSUE THREAD

**Issue by JeroenVanLeusden** [tig-nl/postnl-magento2#85]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- `\TIG\PostNL\Plugin\Postcodecheck\Management\GuestPayment::beforeSavePaymentInformation()` treated `$billingAddress` as a required parameter while it's not. If no billing address is given the code will fail because we cannot fetch extension attributes from null`. This will most likely happen when orders are being imported from another source.
- Expected result: We can create order without setting the billingAddress.
- Actual result: `PHP Fatal error:  Uncaught Error: Call to a member function getExtensionAttributes() on null in /data/web/magento2/vendor/tig/postnl-magento2/Plugin/Postcodecheck/Management/GuestPayment.php:77`
- Workaround: Add statement to check if `$billingAddress` is set.
```PHP
if (!$billingAddress) {
    return [$cartId, $email, $paymentMethod, $billingAddress];
}
```

**Comment by tig-dennisvanderhammen** [comment]
@JeroenVanLeusden,

Thank you for your submission. We just released PostNL Magento 2 version 1.7.0 which includes your fix for the issue your mentioned.

Please use the following command to update:
composer update tig/postnl-magento2 --with-dependencies
