### ISSUE TITLE
upgrade script (1.6.0) does not work on tables with prefix

### ISSUE THREAD

**Issue by GuidoHub** [tig-nl/postnl-magento2#86]
SQLSTATE[42S02]: Base table or view not found: 1146 Table xxxx.core_config_data' doesn't exist, query was: UPDATE `core_config_data` SET `path` = ? WHERE (path = 'tig_postnl/shippingoptions/pakjegemak_active')

**Comment by tig-dennisvanderhammen** [comment]
HI @GuidoHub,

Thank you for your issue request. We just released PostNL Magento 2 version 1.7.0. Version 1.7.0 contains a fix for the issue your mentioned.

Please use the following command to update:
composer update tig/postnl-magento2 --with-dependencies
