### ISSUE TITLE
Extension breaks mass actions dropdown in sales order grid

### ISSUE THREAD

**Issue by JerVoo** [tig-nl/postnl-magento2#88]
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

Running Magento v2.3.0 with module version 1.7.0.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
1. Install the PostNL module
2. Go to the sales order grid
3 . Try to select a mass action

**Expected result**
The mass action dropdown is filled with several options, allowing to perform mass actions on selected orders

**Actual result**
The mass action dropdown is empty, rendering a Javascript error in the browser console

```
knockout.js:3391 Uncaught ReferenceError: Unable to process binding "foreach: function(){return {data:actions,as:'action'} }"
Message: Unable to process binding "text: function(){return label }"
Message: label is not defined
    at text (eval at createBindingsStringEvaluator (knockout.js:2992), <anonymous>:3:57)
    at update (knockout.js:4669)
    at ko.dependentObservable.disposeWhenNodeIsRemoved (knockout.js:3383)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout.js:2183)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.js:2150)
    at Function.evaluateImmediate (knockout.js:2111)
    at Object.ko.computed.ko.dependentObservable (knockout.js:1964)
    at knockout.js:3381
    at Object.arrayForEach (knockout.js:159)
    at applyBindingsToNodeInternal (knockout.js:3353)
```

**Workaround**
None

**Comment by tig-dennisvanderhammen** [comment]
Hi @JerVoo,

Thank you for pointing out this issue. This seems to be the same issue as pointed out in https://github.com/tig-nl/postnl-magento2/issues/87. To keep the information in one issue, I'd like to ask you to follow the above mentioned issue.

**Comment by tig-dennisvanderhammen** [comment]
Hi @JerVoo,

I'm not sure if you'll get an e-mail about the update on issue #87, but we have found the cause of the issue and wanted to share that issue #87 has received an update. We found two possible workarounds that are mentioned in this issue.
