### ISSUE TITLE
Multiple shipping labels for different products in one order

### ISSUE THREAD

**Issue by dennisvandenbroek** [tig-nl/postnl-magento2#91]
- Step 1: create order with multiple items, not being the same (so different items)
- Step 2: create shipping label in backend
- Expected result: 1 shipping label with 1 tracking code on it
- Actual result: shipping label for each different item within the order
- Workaround: checking which tracking code is connected to the order and throw away all other labels??? Very bad workaround.

**Comment by dennisvandenbroek** [comment]
Extra: it seems for some reason the parcel count is no longer 1 for an order. Each unique product adds 1 tot the total parcel count. Workaround temporarily is setting parcel count to 1 in batch mode in Sales->Shipments

**Comment by tig-jeffreybranderhorst** [comment]
Hi @dennisvandenbroek,

It looks like a bug, I will add it to the backlog. Seems like the parcel count is being read out even if it is not a extra@home product. That's probably the reason you are getting multi colli. Does the product have a parcel count filled in? 

Kind regard,
Jeffrey Branderhorst

**Comment by dennisvandenbroek** [comment]
Jeffrey,

We don’t use Extra@Home. This is on a product level what is in the PostNL part

[image1.png]

Can we bulk adjust this maybe as a workaround.

Dennis

Verstuurd vanaf mijn iPhone X

Op 24 jan. 2019 om 13:00 heeft Jeffrey Branderhorst <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi @dennisvandenbroek<https://github.com/dennisvandenbroek>,

It looks like a bug, I will add it to the backlog. Seems like the parcel count is being read out even if it is not a extra@home product. That's probably the reason you are getting multi colli. Does the product have a parcel count filled in?

Kind regard,
Jeffrey Branderhorst

**Comment by tig-jeffreybranderhorst** [comment]
@renehol @dennisvandenbroek  
a work-a-round should be leaving the Parcel count empty. 

Best regards,
Jeffrey Branderhorst

**Comment by renehol** [comment]
@tig-jeffreybranderhorst It has been a few days sinds the last comment. Keeping the parcel count empty is not an option for when this problem is fixed. 

Do you know when a fix is plannend?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @renehol 
We are busy with making the fix. We got a fix now, we are testing this fix. When the fix is approved we will make a new release.  I cannot give you a date for the release yet because we are waiting for the test results.

Met vriendelijke groet / Kind regards / Mit freundlichen Grüßen / 最好的祝福,

Jeffrey Branderhorst

**Comment by tig-jaspersmits** [comment]
Hi @renehol 

We spoke about this on Whatsapp. This has been fixed in version 1.7.3. of the PostNL extension.
Hereby I will close this Github issue. If you have any other questions feel free to contact me through Whatsapp.

Kind regards,

Jasper
