### ISSUE TITLE
Unable to extract the house number

### ISSUE THREAD

**Issue by PascalBrouwers** [tig-nl/postnl-magento2#93]
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

Magento: 2.2.7
PostNL: 1.7.0
---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Steps: Select order (with address "De La Reylaan 43") and choose: PostNL - Create shipments, print packing slip & confirm
- Expected result: Created packing slip
- Actual result: Error: POSTNL-1024 - Unable to extract the house number
- Workaround : none

**Comment by PascalBrouwers** [comment]
I don't see the regex matching either:
http://cloud.h-o.nl/b49f588d157b

**Comment by JeroenVanLeusden** [comment]
Gaat ook om de volgende format:
street[0] -> ***straat
street[1] -> 67
street[2] -> -1 hoog

**Comment by tig-rikjonkmans** [comment]
@PascalBrouwers ,
Sorry i could not reproduce this issue. 
![image](https://user-images.githubusercontent.com/23359911/51749288-40cc3080-20af-11e9-9403-d8d04902d3fe.png)

Also our unit tests do not fail on the given street address
![image](https://user-images.githubusercontent.com/23359911/51749388-838e0880-20af-11e9-8fd8-cd62ac4f2db1.png)

@JeroenVanLeusden 
We have checked this, and indeed this will fail. Will look into it and report back if we know more.
