### ISSUE TITLE
No error while generating a wrong shipping label OR no way to regenerate the shipping label

### ISSUE THREAD

**Issue by PascalBrouwers** [tig-nl/postnl-magento2#94]
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Create an order, but have in the address as postalcode "Moorsel" and as city "9310".
![screen shot 2019-02-01 at 11 54 44](https://user-images.githubusercontent.com/17834386/52119052-31e9fe80-2618-11e9-8cc2-1c8a6f525094.png)
- Print shipping label. Address is empty, possible because postalcode is wrong.
![screen shot 2019-02-01 at 11 53 03](https://user-images.githubusercontent.com/17834386/52118975-07984100-2618-11e9-80c5-0d28dc4448ba.png)
- Change address so postalcode is "9310" and city is "Moorsel".
- Print shipping label again.
- Expected result: A new generated shipping label
- Actual result: the old shipping label
- Workaround: none

**Comment by tig-dennisvanderhammen** [comment]
Hi @PascalBrouwers,

Thank you for giving us the heads up about this issue.

Whenever a label is generated, the label is also saved in the database, in the tig_postnl_shipment_label table to be exact. This is to prevent making calls to the PostNL servers when the data is already available.

What you can do as a workaround is find out which shipment_id has the issue, and remove the row from the tig_postnl_shipment_label. The extension should realise there are no labels available and request a new one from PostNL, this time with the correct data.

I'll place this issue on our backlog to fix this in a future update.

**Comment by PascalBrouwers** [comment]
I tried that, but then I got an error. I figured I was not supposed to delete the record in the database or something.

**Comment by tig-daanvandenbergh** [comment]
Hi @PascalBrouwers,

There is already a function in PostNL M2 which allows you to re-generate a label. 

After clicking 'Change Confirmation', the label is removed. Afterwards you can either 'Confirm & Print' or just 'Print'. You'll see that the new label reflects the changes you made in the shipment address.

After reading your issue I realised 'Change Confirmation' might be an unclear description of the function. That's why in our next release it's called 'Cancel Confirmation'.

I'm closing this issue.

**Comment by PascalBrouwers** [comment]
Ah perfect. Was indeed a bit unclear.
