### ISSUE TITLE
Magento 2.3.1/2.2.8 support

### ISSUE THREAD

**Issue by tig-dennisvanderhammen** [tig-nl/postnl-magento2#98]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)
- [ ] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *feature request*
- As a merchant or developer I’d like to be able to update to Magento 2.3.1 with the PostNL extension installed in order to stay up-to-date with the latest Security patches.

### TIG support

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.
- If you want support with installing the PostNL extension, please contact citservicedesk@postnl.nl for free support, or contact us directly at support@tig.nl for paid support plans.

**Comment by celorodovalho** [comment]
Please! This is very important.

**Comment by tig-dennisvanderhammen** [comment]
We're currently working very hard to get this update out as soon as possible. I'll update this issue once we have a release out.

If you're running on Magento 2.3.1, Magento did provide a patch if a full update is not possible yet. They state something about this on the following page:
https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.html

**Comment by celorodovalho** [comment]
At least for the version 2.2.8.
The version 2.3.1 can wait a little more :D

**Comment by Sil-B** [comment]
Hi guys, what is the status? We can't update all of our shops with the PostNL implementation.

**Comment by tig-dennisvanderhammen** [comment]
Version v1.7.4 of the PostNL extension has just been released. This version contains support for Magento 2.1.17, 2.2.8 and 2.3.1.
